# Testing LSST Feature Extraction via reLAISS

This notebook tests code for extracting lightcurve features from LSST alerts via Antares.

**Goal:** Confirm that `extract_lc_and_host_features` produces the same feature columns that Isolation Forest and DiMMAD models were trained on (`constants.lc_features_const`).

**Workflow:**
1. Run extraction script on one LSST object
2. Compare output columns against the training feature lists
3. Check for missing/extra features before passing to models

## 1. Setup & Imports

In [18]:
import os
import sys

import warnings
import numpy as np
import pandas as pd
from pathlib import Path

warnings.filterwarnings("ignore")

# ── reLAISS path changed from script
import importlib, subprocess

RELAISS_REPO = "/Users/jennakempster-taylor/re-laiss"

if importlib.util.find_spec("relaiss") is None:
    subprocess.run([sys.executable, "-m", "pip", "install", "-e", RELAISS_REPO])

# ── Core imports ──────────────────────────────────────────────────────────────
import antares_client
import gdown
from relaiss.features import extract_lc_and_host_features
from relaiss.relaiss import REFERENCE_DIR, download_sfd_files
from relaiss import constants

print("All imports OK")

All imports OK

## 2. What features did we train on?

Before touching the LSST data, record the exact feature lists from your training notebooks.
These are the **ground truth** we need to match.

In [21]:
# These are the same constants your IsoForest and DiMMAD notebooks pulled from
default_lc_features   = constants.lc_features_const.copy()
default_host_features = constants.host_features_const.copy()

# The training notebooks dropped *_err columns:
def training_overlap(cols, frame):
    """Mirrors the overlap() function in both training notebooks."""
    return [c for c in cols if (c in frame.columns) and (not c.endswith("_err"))]

print(f"LC features defined in constants:   {len(default_lc_features)}")
print(f"Host features defined in constants: {len(default_host_features)}")
print(f"Total before filtering:             {len(default_lc_features) + len(default_host_features)}")
print()
print("LC features:")
print(default_lc_features)
print()
print("Host features:")
print(default_host_features)

LC features defined in constants:   25
Host features defined in constants: 18
Total before filtering:             43

LC features:
['g_peak_time', 'r_peak_time', 'g_rise_time', 'g_decline_time', 'r_rise_time', 'r_decline_time', 'g_duration_above_half_flux', 'r_duration_above_half_flux', 'g_amplitude', 'r_amplitude', 'g_skewness', 'r_skewness', 'g_beyond_2sigma', 'r_beyond_2sigma', 'mean_g-r', 'g-r_at_g_peak', 'mean_color_rate', 'g_max_rolling_variance', 'r_max_rolling_variance', 'g_mean_rolling_variance', 'r_mean_rolling_variance', 'g_rise_local_curvature', 'g_decline_local_curvature', 'r_rise_local_curvature', 'r_decline_local_curvature']

Host features:
['gKronMagCorrected', 'gKronRad', 'gExtNSigma', 'rKronMagCorrected', 'rKronRad', 'rExtNSigma', 'iKronMagCorrected', 'iKronRad', 'iExtNSigma', 'zKronMagCorrected', 'zKronRad', 'zExtNSigma', 'gminusrKronMag', 'rminusiKronMag', 'iminuszKronMag', 'rmomentXX', 'rmomentXY', 'rmomentYY']

## 3. Load your saved model artifacts

Load the fitted imputers, scalers, and feature column lists from training.
This is the safest reference for exactly what columns the models expect.

In [23]:
from joblib import load

# ── Isolation Forest ──────────────────────────────────────────────────────────
# Saved in IsoForestDur.ipynb Cell 32: iforest_artifacts.joblib
# Contains keys: 'iso', 'knn_imp', 'numeric_feature_cols'
ISO_ARTIFACT_PATH = "iforest_artifacts.joblib"  # update path if needed

# ── DiMMAD ────────────────────────────────────────────────────────────────────
# Saved in DimmadTest_cleaned.ipynb: models/dimmad_medmed_relaiss_bundle.joblib
# Contains keys: 'feature_cols', 'imputer', 'scaler', 'model'
DIMMAD_ARTIFACT_PATH = "models/dimmad_medmed_relaiss_bundle.joblib"  # update path if needed

iso_art, dimmad_art = None, None

if Path(ISO_ARTIFACT_PATH).exists():
    iso_art = load(ISO_ARTIFACT_PATH)
    iso_feature_cols = iso_art["numeric_feature_cols"]
    print(f"IsoForest artifact loaded. Expects {len(iso_feature_cols)} features.")
else:
    print(f"WARNING: IsoForest artifact not found at {ISO_ARTIFACT_PATH}")
    print("  -> Will use constants as fallback for feature comparison")
    iso_feature_cols = None

if Path(DIMMAD_ARTIFACT_PATH).exists():
    dimmad_art = load(DIMMAD_ARTIFACT_PATH)
    dimmad_feature_cols = dimmad_art["feature_cols"]
    print(f"DiMMAD artifact loaded.   Expects {len(dimmad_feature_cols)} features.")
else:
    print(f"WARNING: DiMMAD artifact not found at {DIMMAD_ARTIFACT_PATH}")
    dimmad_feature_cols = None

IsoForest artifact loaded. Expects 25 features.
DiMMAD artifact loaded.   Expects 25 features.

## 4. Run the advisor's extraction script

This is your advisor's vibe code, minimally restructured into a callable function
so we can reuse it for multiple LSST objects later.

In [25]:
def extract_features_for_lsst_object(lsst_id: str, base_dir: Path = Path(".")) -> pd.DataFrame:
    """
    Fetch one LSST object from Antares and extract reLAISS features.
    
    Parameters
    ----------
    lsst_id : str
        LSST diaObject ID (e.g. '170019696318349586')
    base_dir : Path
        Working directory for outputs and dust maps.
    
    Returns
    -------
    pd.DataFrame
        One-row DataFrame of reLAISS features for this object.
    """
    sfd_folder       = base_dir / "sfddata-master"
    timeseries_folder = base_dir / "laiss_final" / "timeseries"
    sfd_folder.mkdir(parents=True, exist_ok=True)
    timeseries_folder.mkdir(parents=True, exist_ok=True)

    # Ensure SFD dust maps are present
    download_sfd_files(str(sfd_folder))

    # Ensure reference bank is present (needed for imputation inside reLAISS)
    bank_path = REFERENCE_DIR / "reference_20k.csv"
    if not bank_path.exists():
        print(f"Reference data not found at {bank_path}; downloading...")
        bank_path.parent.mkdir(parents=True, exist_ok=True)
        gdown.download(
            "https://drive.google.com/uc?export=download&id=1uH_03ju50Enb7ZhiduDrmCVTMvTc7bMC",
            str(bank_path),
            quiet=False,
        )

    # Fetch lightcurve from Antares
    print(f"Fetching LSST {lsst_id} from Antares...")
    locus = antares_client.search.get_by_lsst_dia_object_id(lsst_object_id=lsst_id)
    if locus is None:
        raise ValueError(f"Object {lsst_id} not found in Antares")

    lc_df = locus.timeseries.to_pandas()[["ant_passband", "ant_mjd", "ant_mag", "ant_magerr"]]
    
    # NOTE on passband mapping:
    # Your training data used ZTF passbands: 'g' and 'R'.
    # LSST alert passbands from Antares come as 'G' and 'r' (capital G, lowercase r).
    # Previous code maps: 'G' -> 'g'  and  'r' -> 'R'.
    lc_df["ant_passband"] = lc_df["ant_passband"].replace({"G": "g", "r": "R"})
    
    print(f"Lightcurve fetched: {len(lc_df)} alerts, passbands: {lc_df['ant_passband'].unique()}")
    display(lc_df.head())

    # Extract features via reLAISS
    # building_for_AD=True skips host association (PROST), which is what we want
    df_feat = extract_lc_and_host_features(
        ztf_id=lsst_id,                            # used as row label in output
        theorized_lightcurve_df=lc_df,
        path_to_timeseries_folder=str(timeseries_folder),
        path_to_sfd_folder=str(sfd_folder),
        path_to_dataset_bank=str(bank_path),
        building_for_AD=True,
        store_csv=False,
    )

    # Fix object ID column if needed
    if "ztf_object_id" in df_feat.columns:
        df_feat["ztf_object_id"] = lsst_id
    elif df_feat.index.name == "ztf_object_id":
        df_feat = df_feat.reset_index()
        df_feat["ztf_object_id"] = lsst_id

    # Tag with the LSST ID so we can identify rows later
    df_feat["lsst_dia_object_id"] = lsst_id

    print(f"\nExtracted feature row shape: {df_feat.shape}")
    return df_feat


# ── Run on the test object ────────────────────────────────────────────────────
TEST_LSST_ID = "170019696318349586"
df_extracted = extract_features_for_lsst_object(TEST_LSST_ID)

Fetching LSST 170019696318349586 from Antares...
Lightcurve fetched: 134 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 02:21:11.105457            R  61088.098045  23.723501    0.143402
2026-02-19 01:17:06.229662            i  61090.053544  23.417507    0.159649
2026-02-19 01:18:20.914365            i  61090.054409  23.255661    0.149965
2026-02-19 01:20:13.104719            i  61090.055707  23.507910    0.189936
2026-02-19 01:23:21.503963            i  61090.057888  23.510099    0.184778

Extracted lightcurve features for theorized lightcurve in 10.64s!
Engineering features...

Extracted feature row shape: (81, 84)

## 5. Feature alignment check

This is the critical validation step. We compare:
- The columns in `df_extracted` (what reLAISS gave us)
- The columns your models were trained on

**Missing features** = reLAISS didn't compute them for this LSST object (may need to be NaN-filled)  
**Extra features** = reLAISS returned something the model doesn't use (safe to ignore)

In [26]:
extracted_cols = set(df_extracted.columns)

# -- Compare against the full feature set from constants (USE_HOST=True, drop *_err) --
# This mirrors exactly what both training notebooks did with the overlap() function
all_training_lc   = [c for c in default_lc_features   if not c.endswith("_err")]
all_training_host = [c for c in default_host_features if not c.endswith("_err")]
all_training_feats = all_training_lc + all_training_host

missing_from_extraction = [c for c in all_training_feats if c not in extracted_cols]
extra_in_extraction     = [c for c in extracted_cols if c not in all_training_feats
                           and c not in ("ztf_object_id", "lsst_dia_object_id")]

print("=" * 60)
print(f"Training features expected:   {len(all_training_feats)}")
print(f"Features in extracted output: {len(extracted_cols)}")
print()
print(f"MISSING from extraction ({len(missing_from_extraction)}):")
for c in missing_from_extraction:
    print(f"  - {c}")
print()
print(f"EXTRA in extraction (not in training, {len(extra_in_extraction)}):")
for c in extra_in_extraction:
    print(f"  + {c}")
print("=" * 60)

============================================================
Training features expected:   43
Features in extracted output: 84

MISSING from extraction (18):
  - gKronMagCorrected
  - gKronRad
  - gExtNSigma
  - rKronMagCorrected
  - rKronRad
  - rExtNSigma
  - iKronMagCorrected
  - iKronRad
  - iExtNSigma
  - zKronMagCorrected
  - zKronRad
  - zExtNSigma
  - gminusrKronMag
  - rminusiKronMag
  - iminuszKronMag
  - rmomentXX
  - rmomentXY
  - rmomentYY

EXTRA in extraction (not in training, 57):
  + g_n_peaks
  + g_secondary_peak_prominence_err
  + g_peak_mag_err
  + g_dmag_secondary_peak_err
  + g_rise_local_curvature_err
  + r_dt_main_to_secondary_peak
  + r_secondary_peak_prominence_err
  + mean_color_rate_err
  + r_decline_time_err
  + g_dt_main_to_secondary_peak_err
  + r_peak_time_err
  + features_valid_err
  + g_duration_above_half_flux_err
  + r_peak_mag
  + g_decline_local_curvature_err
  + g_beyond_2sigma_err
  + r_max_rolling_variance_err
  + g-r_at_g_peak_err
  + mean_g-r_err
  + r_duration_above_half_flux_err
  + r_peak_mag_err
  + r_beyond_2sigma_err
  + r_rise_time_err
  + r_mean_rolling_variance_err
  + r_secondary_peak_width
  + r_dmag_secondary_peak
  + r_secondary_peak_width_err
  + r_n_peaks_err
  + r_decline_local_curvature_err
  + g_max_rolling_variance_err
  + g_mean_rolling_variance_err
  + t0
  + total_duration_err
  + mjd_cutoff
  + r_dt_main_to_secondary_peak_err
  + r_n_peaks
  + r_secondary_peak_prominence
  + g_dmag_secondary_peak
  + g_dt_main_to_secondary_peak
  + g_peak_time_err
  + g_rise_time_err
  + g_decline_time_err
  + g_peak_mag
  + r_amplitude_err
  + features_valid
  + g_amplitude_err
  + r_dmag_secondary_peak_err
  + r_rise_local_curvature_err
  + g_secondary_peak_width
  + total_duration
  + g_secondary_peak_width_err
  + g_n_peaks_err
  + obs_num
  + r_skewness_err
  + g_skewness_err
  + t0_err
  + g_secondary_peak_prominence
============================================================

In [27]:
# -- If you have the saved model artifacts, also check against their exact column lists --

if iso_feature_cols is not None:
    iso_missing = [c for c in iso_feature_cols if c not in extracted_cols]
    print(f"IsoForest: {len(iso_missing)} features missing from extraction:")
    print(iso_missing if iso_missing else "  None -- all present!")
    print()

if dimmad_feature_cols is not None:
    dim_missing = [c for c in dimmad_feature_cols if c not in extracted_cols]
    print(f"DiMMAD: {len(dim_missing)} features missing from extraction:")
    print(dim_missing if dim_missing else "  None -- all present!")

IsoForest: 0 features missing from extraction:
  None -- all present!

DiMMAD: 0 features missing from extraction:
  None -- all present!

## 6. Inspect the extracted values

Check for NaNs in the training features — too many NaNs in a single row may
cause the KNNImputer to struggle, since it was fit on the training set distribution.

In [31]:
from relaiss import constants

lc_features_no_err = [c for c in constants.lc_features_const if not c.endswith("_err")]
missing_lc = [c for c in lc_features_no_err if c not in df_extracted.columns]
present_lc = [c for c in lc_features_no_err if c in df_extracted.columns]

print(f"LC features present: {len(present_lc)} / {len(lc_features_no_err)}")
print(f"Missing LC features: {missing_lc if missing_lc else 'None -- all present!'}")

LC features present: 25 / 25
Missing LC features: None -- all present!

In [32]:
# Subset extracted df to just the columns the models care about
present_feat_cols = [c for c in all_training_feats if c in extracted_cols]
df_feat_subset = df_extracted[present_feat_cols].copy()

nan_counts = df_feat_subset.isna().sum(axis=1)
print(f"NaN count in extracted feature row: {nan_counts.values[0]} / {len(present_feat_cols)} features")
print(f"({nan_counts.values[0]/len(present_feat_cols)*100:.1f}% missing)")

# Show which features are NaN
nan_cols = df_feat_subset.columns[df_feat_subset.isna().any()].tolist()
if nan_cols:
    print(f"\nFeatures with NaN values ({len(nan_cols)}):")
    for c in nan_cols:
        print(f"  {c}")
else:
    print("\nNo NaN values -- great!")

# Display extracted values for all features
display(df_feat_subset.T.rename(columns={df_feat_subset.index[0]: "extracted_value"}))

NaN count in extracted feature row: 0 / 25 features
(0.0% missing)

No NaN values -- great!

,extracted_value,1,2,3,4,5,6,7,8,9,...,71,72,73,74,75,76,77,78,79,80
g_peak_time,105.009800,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,...,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02,1.050098e+02
r_peak_time,6.008776,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,...,8.016141e+00,8.016141e+00,8.016141e+00,9.995432e+00,9.998044e+00,9.998044e+00,9.998044e+00,9.998044e+00,9.998044e+00,9.998044e+00
g_rise_time,71.026893,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,...,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01,7.102689e+01
g_decline_time,60.757580,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,...,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01,6.075758e+01
r_rise_time,6.008776,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,6.008776e+00,...,7.287798e+00,7.287798e+00,7.287798e+00,6.983283e+00,7.991403e+00,7.991403e+00,7.991403e+00,7.991403e+00,7.991403e+00,7.991403e+00
r_decline_time,0.008742,8.741548e-03,8.741548e-03,8.741548e-03,8.741548e-03,9.760759e-01,9.765096e-01,9.769433e-01,9.778127e-01,9.795482e-01,...,1.972019e+00,1.974233e+00,1.975964e+00,6.210983e+01,6.210983e+01,3.051684e-03,3.490446e-03,4.006399e-03,7.478552e-03,7.478552e-03
g_duration_above_half_flux,6.959105,6.961742e+00,6.970216e+00,6.971954e+00,6.978171e+00,6.984852e+00,6.985286e+00,6.985720e+00,6.986589e+00,6.988325e+00,...,9.988160e+00,9.990374e+00,9.992105e+00,9.995432e+00,9.998044e+00,1.000110e+01,1.000153e+01,1.000205e+01,1.000552e+01,1.094623e+01
r_duration_above_half_flux,6.959105,6.961742e+00,6.970216e+00,6.971954e+00,6.978171e+00,6.984852e+00,6.985286e+00,6.985720e+00,6.986589e+00,6.988325e+00,...,9.988160e+00,9.990374e+00,9.992105e+00,9.995432e+00,9.998044e+00,1.000110e+01,1.000153e+01,1.000205e+01,1.000552e+01,1.094623e+01
g_amplitude,0.000000,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,...,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02,1.323427e-02
r_amplitude,0.551403,5.514028e-01,5.514028e-01,5.514028e-01,5.514028e-01,5.514028e-01,5.514028e-01,5.514028e-01,5.514028e-01,5.514028e-01,...,8.651436e-01,8.651436e-01,8.651436e-01,8.841701e-01,9.375529e-01,9.375529e-01,9.375529e-01,9.375529e-01,9.375529e-01,9.375529e-01
g_skewness,0.265347,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,...,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13,-8.054000e-13
r_skewness,0.057916,5.791558e-02,5.791558e-02,5.791558e-02,5.791558e-02,5.636992e-02,1.110333e-01,1.789598e-01,1.949591e-01,2.548087e-01,...,6.655524e-02,8.973324e-02,1.084689e-01,8.956497e-04,-1.174913e-01,-1.109976e-01,-8.259171e-02,-4.818019e-02,-1.588683e-02,-1.588683e-02
g_beyond_2sigma,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
r_beyond_2sigma,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,5.882353e-02,5.769231e-02,5.660377e-02,5.555556e-02,7.272727e-02,7.142857e-02,7.017544e-02,6.896552e-02,6.779661e-02,6.779661e-02
mean_g-r,0.199303,1.993034e-01,1.993034e-01,1.993034e-01,1.993034e-01,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01,...,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01,6.437301e-01
g-r_at_g_peak,-0.015752,-1.575170e-02,-1.575170e-02,-1.575170e-02,-1.575170e-02,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01,...,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01,6.370172e-01
mean_color_rate,0.043502,4.350163e-02,4.350163e-02,4.350163e-02,4.350163e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
g_max_rolling_variance,0.026538,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,...,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08
r_max_rolling_variance,0.007605,7.605039e-03,7.605039e-03,7.605039e-03,7.605039e-03,5.527455e-03,6.972230e-03,5.537758e-03,5.548094e-03,5.568757e-03,...,2.147025e-02,2.146855e-02,2.146721e-02,2.146465e-02,2.146264e-02,2.146029e-02,2.145995e-02,2.145955e-02,2.145688e-02,2.145688e-02
g_mean_rolling_variance,0.002401,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,...,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08,3.574043e-08
r_mean_rolling_variance,0.000647,6.471001e-04,6.471001e-04,6.471001e-04,6.471001e-04,4.365444e-04,5.091569e-04,4.732481e-04,4.394926e-04,4.880979e-04,...,1.296997e-03,1.316911e-03,1.311108e-03,1.308078e-03,1.328728e-03,1.483916e-03,1.389030e-03,1.352033e-03,1.361569e-03,1.361569e-03
g_rise_local_curvature,-31.662004,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,...,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01,-3.166200e+01
g_decline_local_curvature,-10.574796,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,...,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01,-1.057480e+01
r_rise_local_curvature,0.318861,3.188611e-01,3.188611e-01,3.188611e-01,3.188611e-01,3.188611e-01,3.188611e-01,3.188611e-01,3.188611e-01,3.188611e-01,...,3.324612e-01,3.324612e-01,3.324612e-01,3.324612e-01,3.460614e-01,3.460614e-01,3.460614e-01,3.460614e-01,3.460614e-01,3.460614e-01
r_decline_local_curvature,20214.147996,2.021415e+04,2.021415e+04,2.021415e+04,2.021415e+04,1.010688e+04,-3.784216e-01,1.010688e+04,2.021415e+04,1.010688e+04,...,3.941638e+04,3.802845e-01,2.361931e-02,-5.740185e+01,-5.740185e+01,-5.740185e+01,-1.883156e+05,7.576891e+03,1.649323e+04,1.649323e+04

## 8. Batch processing template

For full list of LSST object IDs, use to loop over and collect all features in one DataFrame.

In [39]:
import os
os.getcwd()

'/Users/jennakempster-taylor/re-laiss'

In [48]:
from tqdm import tqdm
import pandas as pd
from pathlib import Path

# Load your source list
sources = pd.read_csv("data/sources.csv")
lsst_ids = sources["id"].astype(str).tolist()
print(f"Total objects to process: {len(lsst_ids)}")

checkpoint_path = Path("lsst_extracted_features.csv")
failed = []

# Check what's already been done
already_done = []
if checkpoint_path.exists():
    done_df = pd.read_csv(checkpoint_path)
    already_done = done_df["lsst_dia_object_id"].astype(str).tolist()
    print(f"Resuming — {len(already_done)} already extracted, {len(lsst_ids) - len(already_done)} remaining")

for lsst_id in tqdm(lsst_ids, desc="Extracting features"):
    if lsst_id in already_done:
        continue
    try:
        df_row = extract_features_for_lsst_object(lsst_id)
        # Append to CSV incrementally so progress is never lost
        df_row.to_csv(checkpoint_path, mode="a",
                      header=not checkpoint_path.exists(), index=False)
        already_done.append(lsst_id)
    except Exception as e:
        print(f"FAILED: {lsst_id} — {e}")
        failed.append({"lsst_id": lsst_id, "error": str(e)})

print(f"\nDone. Extracted: {len(already_done)} / {len(lsst_ids)}")
print(f"Failed: {len(failed)}")
if failed:
    pd.DataFrame(failed).to_csv("lsst_failed.csv", index=False)
    print("Failed IDs saved to lsst_failed.csv")

Total objects to process: 223
Resuming — 17760 already extracted, -17537 remaining

Extracting features:   0%|                              | 0/223 [00:00<?, ?it/s]

Fetching LSST 170032905875619955 from Antares...
Lightcurve fetched: 9 alerts, passbands: ['R' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-20 04:30:53.256389            R  61091.188116  22.101726    0.031469
2026-02-20 04:32:13.791104            R  61091.189049  22.061426    0.029628
2026-02-20 04:32:53.938786            R  61091.189513  22.064771    0.028741
2026-02-20 04:33:34.181464            R  61091.189979  22.109398    0.029125
2026-02-20 04:34:23.526505            R  61091.190550  22.046966    0.027135

Extracted lightcurve features for theorized lightcurve in 0.71s!
Engineering features...

Extracting features:  37%|███████▊             | 83/223 [00:10<00:18,  7.55it/s]

Extracted feature row shape: (4, 84)
Fetching LSST 170032906681450641 from Antares...
Lightcurve fetched: 13 alerts, passbands: ['R' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-20 04:35:03.440569            R  61091.191012  22.075163    0.027711
2026-02-20 04:35:43.661222            R  61091.191478  22.106305    0.028323
2026-02-20 04:36:23.905365            R  61091.191943  22.089831    0.029295
2026-02-20 04:37:04.207832            R  61091.192410  22.105143    0.028174
2026-02-20 04:37:44.847174            R  61091.192880  22.085045    0.029737

Extracted lightcurve features for theorized lightcurve in 0.69s!
Engineering features...

Extracting features:  38%|███████▉             | 84/223 [00:20<00:40,  3.41it/s]

Extracted feature row shape: (7, 84)
Fetching LSST 314003013678661710 from Antares...
Lightcurve fetched: 6 alerts, passbands: ['R' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-18 07:08:45.541518            R  61058.297749  21.503291    0.019576
2026-01-18 07:09:19.752119            R  61058.298145  21.599251    0.020370
2026-01-18 07:10:45.906332            R  61058.299142  21.556515    0.021445
2026-01-18 07:11:20.033730            R  61058.299537  21.534901    0.020800
2026-01-18 07:12:57.574112            R  61058.300666  21.559937    0.018221

Extracted lightcurve features for theorized lightcurve in 0.10s!
Engineering features...

Extracting features:  38%|████████             | 85/223 [00:28<01:04,  2.13it/s]

Extracted feature row shape: (1, 84)
Fetching LSST 313871013252694140 from Antares...
Lightcurve fetched: 308 alerts, passbands: ['R' 'i' 'z' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:39:04.750680            R  61028.318805  23.536913    0.114998
2025-12-19 07:46:38.413117            R  61028.324056  23.849240    0.148324
2025-12-19 07:57:29.877230            R  61028.331596  23.774465    0.136560
2025-12-19 08:17:34.235436            R  61028.345535  23.971096    0.209593
2026-01-10 04:06:23.207278            R  61050.171102  23.739531    0.226032

Extracted lightcurve features for theorized lightcurve in 28.17s!
Engineering features...

Extracting features:  39%|████████             | 86/223 [01:04<03:44,  1.64s/it]

Extracted feature row shape: (216, 84)
Fetching LSST 170046093472563246 from Antares...
Lightcurve fetched: 5 alerts, passbands: ['g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-23 03:19:37.144117            g  61094.138624  24.084171    0.177881
2026-02-23 04:07:18.209572            g  61094.171739  24.341825    0.205451
2026-02-23 04:10:29.140959            g  61094.173948  24.229341    0.191194
2026-02-24 03:28:53.919406            g  61095.145069  24.560849    0.208873
2026-02-25 04:06:28.736717            R  61096.171166  22.416170    0.044955

Extracted lightcurve features for theorized lightcurve in 0.09s!
Engineering features...

Extracting features:  39%|████████▏            | 87/223 [01:11<04:17,  1.89s/it]

Extracted feature row shape: (1, 84)
Fetching LSST 170019716254926219 from Antares...
Lightcurve fetched: 429 alerts, passbands: ['R' 'z' 'i' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 05:05:15.017236            R  61088.211979  22.915207    0.062342
2026-02-17 05:13:43.058707            z  61088.217859  23.153741    0.198547
2026-02-19 02:35:11.633718            i  61090.107774  22.929326    0.130484
2026-02-19 04:20:44.066323            i  61090.181066  22.919965    0.108974
2026-02-19 04:21:24.241282            i  61090.181531  22.882180    0.111161

Extracted lightcurve features for theorized lightcurve in 58.06s!
Engineering features...

Extracting features:  39%|████████▎            | 88/223 [02:18<12:59,  5.77s/it]

Extracted feature row shape: (417, 84)
Fetching LSST 313853533158376118 from Antares...
Lightcurve fetched: 364 alerts, passbands: ['i' 'R' 'u' 'g' 'y' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 07:41:59.590165            i  61024.320829  23.145603    0.159934
2025-12-15 07:42:42.760641            i  61024.321328  23.323013    0.211387
2025-12-15 07:44:52.352766            i  61024.322828  23.316043    0.192294
2025-12-19 07:46:38.413117            R  61028.324056  23.396013    0.105131
2025-12-19 07:47:21.443547            R  61028.324554  23.456752    0.107815

Extracted lightcurve features for theorized lightcurve in 47.39s!
Engineering features...

Extracting features:  40%|████████▍            | 89/223 [03:14<21:36,  9.68s/it]

Extracted feature row shape: (357, 84)
Fetching LSST 170032901867438158 from Antares...
Lightcurve fetched: 8 alerts, passbands: ['g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-20 04:06:28.604349            g  61091.171164  22.596443    0.038660
2026-02-20 04:07:08.940033            g  61091.171631  22.667244    0.042345
2026-02-20 04:07:49.208442            g  61091.172097  22.649962    0.040762
2026-02-20 04:08:29.288465            g  61091.172561  22.653524    0.040331
2026-02-20 04:09:09.488143            g  61091.173026  22.631296    0.039851

Extracted lightcurve features for theorized lightcurve in 0.09s!
Engineering features...

Extracting features:  40%|████████▍            | 90/223 [03:21<20:57,  9.46s/it]

Extracted feature row shape: (1, 84)
Fetching LSST 170019716461494297 from Antares...
Lightcurve fetched: 51 alerts, passbands: ['R' 'i' 'z' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 05:05:55.134224            R  61088.212444  24.155635    0.198812
2026-02-19 04:20:03.648621            i  61090.180598  23.322302    0.175431
2026-02-19 04:28:47.547931            i  61090.186661  23.693058    0.207782
2026-02-19 05:02:16.326259            R  61090.209911  23.734354    0.185931
2026-02-19 05:02:56.715497            R  61090.210379  23.809391    0.178250

Extracted lightcurve features for theorized lightcurve in 2.31s!
Engineering features...

Extracting features:  41%|████████▌            | 91/223 [03:31<20:58,  9.53s/it]

Extracted feature row shape: (28, 84)
Fetching LSST 170028511771230587 from Antares...
Lightcurve fetched: 41 alerts, passbands: ['i' 'z' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 04:26:06.139446            i  61090.184793  22.799219    0.112979
2026-02-19 04:51:25.365084            z  61090.202377  22.359062    0.169795
2026-02-19 05:09:49.213929            i  61090.215153  22.837112    0.141158
2026-02-19 05:10:29.364036            i  61090.215618  23.040765    0.169698
2026-02-19 05:39:17.559783            z  61090.235620  22.553179    0.189106

Extracted lightcurve features for theorized lightcurve in 1.27s!
Engineering features...

Extracting features:  41%|████████▋            | 92/223 [03:40<20:37,  9.45s/it]

Extracted feature row shape: (19, 84)
Fetching LSST 313980947946012744 from Antares...
Lightcurve fetched: 7 alerts, passbands: ['g' 'R' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-13 05:57:38.073505            g  61053.248357  22.091852    0.031893
2026-01-13 05:58:12.639976            g  61053.248757  22.011044    0.035710
2026-01-13 05:58:46.784585            g  61053.249153  22.001539    0.029958
2026-01-13 05:59:20.935712            g  61053.249548  21.975368    0.031922
2026-01-13 05:59:55.135696            g  61053.249944  21.949322    0.026948

Extracted lightcurve features for theorized lightcurve in 0.13s!
Engineering features...

Extracting features:  42%|████████▊            | 93/223 [03:48<19:39,  9.08s/it]

Extracted feature row shape: (2, 84)
Fetching LSST 313871013084397632 from Antares...
Lightcurve fetched: 306 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:38:21.792959            R  61028.318308  23.647139    0.133060
2025-12-20 07:56:45.657932            g  61029.331084  23.629061    0.135140
2025-12-24 06:40:08.297680            g  61033.277874  23.484959    0.142041
2025-12-24 06:41:33.955920            g  61033.278865  23.414666    0.134515
2026-01-19 07:02:05.529804            g  61059.293120  24.081007    0.215051

Extracted lightcurve features for theorized lightcurve in 44.17s!
Engineering features...

Extracting features:  42%|████████▊            | 94/223 [04:40<38:23, 17.86s/it]

Extracted feature row shape: (302, 84)
Fetching LSST 313853517489504879 from Antares...
Lightcurve fetched: 275 alerts, passbands: ['i' 'R' 'u' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:08.585837            i  61024.245933  22.681858    0.127419
2025-12-15 05:56:18.352569            i  61024.247435  22.779555    0.144442
2025-12-15 05:57:01.744653            i  61024.247937  22.656675    0.127408
2025-12-15 07:41:16.472056            i  61024.320330  22.820109    0.127636
2025-12-17 05:07:40.081494            i  61026.213658  22.734198    0.116888

Extracted lightcurve features for theorized lightcurve in 29.59s!
Engineering features...

Extracting features:  43%|████████▉            | 95/223 [05:17<47:31, 22.28s/it]

Extracted feature row shape: (260, 84)
Fetching LSST 313853533133209653 from Antares...
Lightcurve fetched: 69 alerts, passbands: ['i' 'R' 'g' 'y']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 07:41:59.590165            i  61024.320829  23.494969    0.208779
2025-12-19 07:38:21.792959            R  61028.318308  23.887135    0.143605
2025-12-19 07:39:04.750680            R  61028.318805  23.905411    0.138815
2025-12-19 07:39:47.565349            R  61028.319301  24.224246    0.178582
2025-12-19 07:57:29.877230            R  61028.331596  24.124907    0.165997

Extracted lightcurve features for theorized lightcurve in 4.93s!
Engineering features...

Extracting features:  43%|█████████            | 96/223 [05:30<42:12, 19.94s/it]

Extracted feature row shape: (63, 84)
Fetching LSST 313972182585704492 from Antares...
Lightcurve fetched: 162 alerts, passbands: ['g' 'R' 'u' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-23 07:52:19.446435            g  61032.328003  24.233888    0.194350
2025-12-24 06:41:33.955920            g  61033.278865  23.814358    0.168668
2026-01-11 04:30:39.499836            g  61051.187957  23.775702    0.151696
2026-01-11 04:32:56.699303            g  61051.189545  23.724604    0.152516
2026-01-13 05:58:46.784585            g  61053.249153  23.965008    0.168205

Extracted lightcurve features for theorized lightcurve in 17.45s!
Engineering features...

Extracting features:  43%|█████████▏           | 97/223 [05:55<44:27, 21.17s/it]

Extracted feature row shape: (148, 84)
Fetching LSST 313972183192305778 from Antares...
Lightcurve fetched: 11 alerts, passbands: ['g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-11 04:33:37.909244            g  61051.190022  24.075266    0.212095
2026-02-23 03:22:24.823353            g  61094.140565  25.678147    0.721120
2026-02-23 04:10:29.140959            g  61094.173948  24.471071    0.213921
2026-02-24 03:22:11.277168            g  61095.140408  24.424556    0.194721
2026-02-24 03:23:31.747872            g  61095.141340  24.327104    0.170860

Extracted lightcurve features for theorized lightcurve in 0.10s!
Engineering features...

Extracting features:  44%|█████████▏           | 98/223 [06:02<36:06, 17.33s/it]

Extracted feature row shape: (1, 84)
Fetching LSST 313888627241779278 from Antares...
Lightcurve fetched: 19 alerts, passbands: ['g' 'u' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-23 07:53:02.077728            g  61032.328496  24.192075    0.177490
2026-01-14 03:30:38.280919            u  61054.146276  22.862686    0.209764
2026-01-17 07:18:24.819023            g  61057.304454  24.393065    0.191454
2026-01-18 07:10:45.906332            R  61058.299142  24.271748    0.194519
2026-02-20 04:06:28.604349            g  61091.171164  24.180250    0.187291

Extracted lightcurve features for theorized lightcurve in 1.07s!
Engineering features...

Extracting features:  44%|█████████▎           | 99/223 [06:10<30:32, 14.78s/it]

Extracted feature row shape: (15, 84)
Fetching LSST 313875416848269319 from Antares...
Lightcurve fetched: 7 alerts, passbands: ['g' 'i' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-20 07:56:45.657932            g  61029.331084  23.025050    0.065083
2025-12-20 07:59:29.836264            i  61029.332984  22.077188    0.070630
2025-12-20 08:00:12.135358            i  61029.333474  22.069770    0.057965
2026-01-18 07:09:19.752119            R  61058.298145  24.337093    0.207017
2026-02-24 03:01:43.290312            R  61095.126195  24.303114    0.209747

Extracted lightcurve features for theorized lightcurve in 0.19s!
Engineering features...

Extracting features:  45%|████████▉           | 100/223 [06:17<25:52, 12.62s/it]

Extracted feature row shape: (3, 84)
Fetching LSST 170028510495637526 from Antares...
Lightcurve fetched: 205 alerts, passbands: ['i' 'z' 'R' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 04:20:03.648621            i  61090.180598  22.459245    0.090849
2026-02-19 04:20:44.066323            i  61090.181066  22.528633    0.091286
2026-02-19 04:24:45.380084            i  61090.183859  22.679763    0.095521
2026-02-19 04:26:46.935844            i  61090.185265  22.738070    0.103942
2026-02-19 04:27:26.860477            i  61090.185728  22.654555    0.097302

Extracted lightcurve features for theorized lightcurve in 32.23s!
Engineering features...

Extracting features:  45%|█████████           | 101/223 [07:00<43:20, 21.32s/it]

Extracted feature row shape: (183, 84)
Fetching LSST 313853517553991744 from Antares...
Lightcurve fetched: 86 alerts, passbands: ['i' 'R' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:51.673674            i  61024.246431  23.251532    0.211964
2025-12-19 07:38:21.792959            R  61028.318308  24.250039    0.177310
2025-12-19 07:39:04.750680            R  61028.318805  24.188131    0.167963
2025-12-19 07:39:47.565349            R  61028.319301  24.357008    0.189000
2025-12-19 07:47:21.443547            R  61028.324554  24.340015    0.201240

Extracted lightcurve features for theorized lightcurve in 6.18s!
Engineering features...

Extracting features:  46%|█████████▏          | 102/223 [07:14<39:09, 19.42s/it]

Extracted feature row shape: (75, 84)
Fetching LSST 313871013298831385 from Antares...
Lightcurve fetched: 214 alerts, passbands: ['R' 'g' 'i' 'y' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:39:04.750680            R  61028.318805  23.594253    0.117926
2025-12-19 07:39:47.565349            R  61028.319301  23.950387    0.161261
2025-12-19 07:46:38.413117            R  61028.324056  23.674688    0.130928
2025-12-19 07:47:21.443547            R  61028.324554  23.693698    0.129334
2025-12-19 07:48:04.714781            R  61028.325055  23.760160    0.145044

Extracted lightcurve features for theorized lightcurve in 23.15s!
Engineering features...

Extracting features:  46%|█████████▏          | 103/223 [07:57<52:23, 26.19s/it]

Extracted feature row shape: (206, 84)
Fetching LSST 313853517399326847 from Antares...
Lightcurve fetched: 101 alerts, passbands: ['i' 'R' 'u' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:08.585837            i  61024.245933  23.255570    0.210315
2025-12-19 07:39:47.565349            R  61028.319301  23.991235    0.137711
2025-12-19 07:48:04.714781            R  61028.325055  23.979685    0.144605
2025-12-19 08:07:38.770456            R  61028.338643  24.119588    0.183661
2025-12-20 07:49:41.959837            u  61029.326180  23.279575    0.198759

Extracted lightcurve features for theorized lightcurve in 21.40s!
Engineering features...

Extracting features:  47%|█████████▎          | 104/223 [08:31<56:49, 28.65s/it]

Extracted feature row shape: (96, 84)
Fetching LSST 313967766555066434 from Antares...
Lightcurve fetched: 40 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-10 04:05:48.751257            R  61050.170703  23.553127    0.191789
2026-01-10 04:06:23.207278            R  61050.171102  23.731835    0.193115
2026-01-10 04:07:03.739927            R  61050.171571  23.388486    0.167009
2026-01-11 04:30:39.499836            g  61051.187957  23.857003    0.151338
2026-01-11 04:31:13.636536            g  61051.188352  23.795828    0.154511

Extracted lightcurve features for theorized lightcurve in 7.34s!
Engineering features...

Extracting features:  47%|█████████▍          | 105/223 [08:52<51:38, 26.26s/it]

Extracted feature row shape: (36, 84)
Fetching LSST 313963406094237721 from Antares...
Lightcurve fetched: 121 alerts, passbands: ['i' 'R' 'z' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-09 07:39:33.825898            i  61049.319142  22.839148    0.151739
2026-01-09 07:40:07.997948            i  61049.319537  22.627359    0.129907
2026-01-09 07:40:42.453716            i  61049.319936  22.685908    0.132083
2026-01-09 07:41:16.688823            i  61049.320332  22.627506    0.135473
2026-01-09 07:44:38.816852            i  61049.322671  22.595444    0.116888

Extracted lightcurve features for theorized lightcurve in 16.90s!
Engineering features...

Extracting features:  48%|█████████▌          | 106/223 [09:19<51:40, 26.50s/it]

Extracted feature row shape: (108, 84)
Fetching LSST 313967766620078431 from Antares...
Lightcurve fetched: 227 alerts, passbands: ['R' 'i' 'z' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-10 04:06:23.207278            R  61050.171102  23.405208    0.171822
2026-01-11 04:36:20.560951            i  61051.191905  22.973208    0.143174
2026-01-11 04:37:29.399114            i  61051.192701  22.934913    0.139230
2026-01-11 04:38:38.419494            i  61051.193500  23.304903    0.198516
2026-01-13 06:06:20.918025            i  61053.254409  23.281791    0.209789

Extracted lightcurve features for theorized lightcurve in 20.82s!
Engineering features...

Extracting features:  48%|█████████▌          | 107/223 [09:51<54:08, 28.00s/it]

Extracted feature row shape: (178, 84)
Fetching LSST 313888627102318679 from Antares...
Lightcurve fetched: 197 alerts, passbands: ['g' 'R' 'u' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-23 07:52:19.446435            g  61032.328003  23.740111    0.121914
2025-12-24 06:40:51.061544            g  61033.278369  23.868274    0.183723
2025-12-24 06:41:33.955920            g  61033.278865  23.798344    0.168087
2026-01-10 04:06:23.207278            R  61050.171102  23.669688    0.204932
2026-01-13 05:57:38.073505            g  61053.248357  23.725528    0.154334

Extracted lightcurve features for theorized lightcurve in 39.52s!
Engineering features...

Extracting features:  48%|████████▋         | 108/223 [10:41<1:06:48, 34.86s/it]

Extracted feature row shape: (193, 84)
Fetching LSST 313972182945890309 from Antares...
Lightcurve fetched: 11 alerts, passbands: ['g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-11 04:32:22.381216            g  61051.189148  24.042325    0.202923
2026-02-23 03:21:03.724844            g  61094.139626  27.515786    4.066294
2026-02-23 04:08:41.520730            g  61094.172703  24.429172    0.208990
2026-02-23 04:09:21.599392            g  61094.173167  24.429439    0.212963
2026-02-24 02:33:26.105495            g  61095.106552  24.004050    0.218315

Extracted lightcurve features for theorized lightcurve in 0.26s!
Engineering features...

Extracting features:  49%|█████████▊          | 109/223 [10:52<52:08, 27.44s/it]

Extracted feature row shape: (2, 84)
Fetching LSST 313853517490028622 from Antares...
Lightcurve fetched: 253 alerts, passbands: ['i' 'R' 'u' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:08.585837            i  61024.245933  23.178716    0.195922
2025-12-15 05:56:18.352569            i  61024.247435  23.021640    0.171182
2025-12-15 07:41:16.472056            i  61024.320330  23.107601    0.150391
2025-12-17 05:08:23.677284            i  61026.214163  23.055720    0.173979
2025-12-19 07:38:21.792959            R  61028.318308  23.173523    0.071248

Extracted lightcurve features for theorized lightcurve in 36.93s!
Engineering features...

Extracting features:  49%|████████▉         | 110/223 [11:40<1:03:35, 33.76s/it]

Extracted feature row shape: (239, 84)
Fetching LSST 170028527254503447 from Antares...
Lightcurve fetched: 351 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:01:08.644455            i  61090.250794  22.637251    0.112116
2026-02-19 06:01:46.037937            i  61090.251227  22.308148    0.084640
2026-02-19 06:03:06.445076            i  61090.252158  22.644673    0.115828
2026-02-19 06:03:46.720130            i  61090.252624  22.366703    0.092814
2026-02-19 06:05:07.163877            i  61090.253555  22.412903    0.092525

Extracted lightcurve features for theorized lightcurve in 54.97s!
Engineering features...

Extracting features:  50%|████████▉         | 111/223 [12:44<1:19:52, 42.79s/it]

Extracted feature row shape: (341, 84)
Fetching LSST 170028527248212842 from Antares...
Lightcurve fetched: 99 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:57:46.926176            i  61090.248460  22.785816    0.162860
2026-02-19 06:01:08.644455            i  61090.250794  22.593561    0.126436
2026-02-19 06:01:46.037937            i  61090.251227  22.548850    0.123813
2026-02-19 06:02:26.190294            i  61090.251692  22.562086    0.127532
2026-02-19 06:03:06.445076            i  61090.252158  22.717122    0.148261

Extracted lightcurve features for theorized lightcurve in 8.16s!
Engineering features...

Extracting features:  50%|█████████         | 112/223 [13:01<1:04:39, 34.95s/it]

Extracted feature row shape: (82, 84)
Fetching LSST 170028530413862954 from Antares...
Lightcurve fetched: 15 alerts, passbands: ['g' 'R' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:18:27.485474            g  61090.262818  23.905545    0.162155
2026-02-19 06:30:39.879800            R  61090.271295  22.939965    0.099439
2026-02-23 04:42:37.270877            i  61094.196265  22.785817    0.110062
2026-02-23 04:48:12.575417            i  61094.200146  22.705246    0.093544
2026-02-23 05:12:49.794383            R  61094.217243  23.221226    0.104690

Extracted lightcurve features for theorized lightcurve in 0.90s!
Engineering features...

Extracting features:  51%|██████████▏         | 113/223 [13:10<49:45, 27.14s/it]

Extracted feature row shape: (11, 84)
Fetching LSST 170032916479344655 from Antares...
Lightcurve fetched: 47 alerts, passbands: ['i' 'R' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:00:28.230400            i  61090.250327  23.211563    0.211885
2026-02-19 06:03:46.720130            i  61090.252624  22.954022    0.162695
2026-02-19 06:25:58.404434            R  61090.268037  23.781463    0.197742
2026-02-19 06:33:21.522145            i  61090.273166  22.911294    0.140445
2026-02-19 06:34:07.811179            i  61090.273702  23.006245    0.161812

Extracted lightcurve features for theorized lightcurve in 0.28s!
Engineering features...

Extracting features:  51%|██████████▏         | 114/223 [13:18<38:59, 21.46s/it]

Extracted feature row shape: (3, 84)
Fetching LSST 170028526986068021 from Antares...
Lightcurve fetched: 84 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:59:47.930124            i  61090.249860  22.203618    0.083955
2026-02-19 06:13:45.650130            g  61090.259556  23.750965    0.189232
2026-02-19 06:18:27.485474            g  61090.262818  23.512377    0.119513
2026-02-19 06:23:57.584971            R  61090.266639  22.548341    0.071661
2026-02-19 07:36:45.472784            i  61090.317193  22.098938    0.074413

Extracted lightcurve features for theorized lightcurve in 7.27s!
Engineering features...

Extracting features:  52%|██████████▎         | 115/223 [13:33<35:26, 19.69s/it]

Extracted feature row shape: (80, 84)
Fetching LSST 170032919173136401 from Antares...
Lightcurve fetched: 59 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:04:27.079781            i  61090.253091  21.923327    0.069642
2026-02-19 06:06:27.709125            i  61090.254487  21.927938    0.077113
2026-02-19 06:16:26.924656            g  61090.261423  23.780613    0.178754
2026-02-19 06:28:39.351874            R  61090.269900  22.122456    0.057219
2026-02-19 06:30:39.879800            R  61090.271295  22.152136    0.062295

Extracted lightcurve features for theorized lightcurve in 4.97s!
Engineering features...

Extracting features:  52%|██████████▍         | 116/223 [13:46<31:20, 17.58s/it]

Extracted feature row shape: (55, 84)
Fetching LSST 170028528057190919 from Antares...
Lightcurve fetched: 16 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:05:07.163877            i  61090.253555  22.514877    0.110911
2026-02-20 06:11:00.063154            i  61091.257640  22.742831    0.107203
2026-02-23 04:43:17.699469            i  61094.196733  23.400761    0.243589
2026-02-23 04:52:57.369935            g  61094.203442  24.155172    0.209557
2026-02-23 05:14:51.775322            R  61094.218655  23.844329    0.206909

Extracted lightcurve features for theorized lightcurve in 0.87s!
Engineering features...

Extracting features:  52%|██████████▍         | 117/223 [13:54<26:06, 14.78s/it]

Extracted feature row shape: (12, 84)
Fetching LSST 170028527145975899 from Antares...
Lightcurve fetched: 273 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:59:47.930124            i  61090.249860  21.612495    0.049549
2026-02-19 06:00:28.230400            i  61090.250327  21.570518    0.048315
2026-02-19 06:01:08.644455            i  61090.250794  21.641457    0.046785
2026-02-19 06:03:06.445076            i  61090.252158  21.601668    0.046946
2026-02-19 06:04:27.079781            i  61090.253091  21.626289    0.045084

Extracted lightcurve features for theorized lightcurve in 37.92s!
Engineering features...

Extracting features:  53%|██████████▌         | 118/223 [14:40<42:22, 24.21s/it]

Extracted feature row shape: (260, 84)
Fetching LSST 170028526712913947 from Antares...
Lightcurve fetched: 116 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:57:01.776883            i  61090.247937  23.271650    0.207413
2026-02-19 05:58:27.382654            i  61090.248928  23.047255    0.180007
2026-02-19 06:00:28.230400            i  61090.250327  22.852395    0.144165
2026-02-19 06:04:27.079781            i  61090.253091  23.263394    0.199690
2026-02-19 06:14:25.960040            g  61090.260023  23.626285    0.159722

Extracted lightcurve features for theorized lightcurve in 12.26s!
Engineering features...

Extracting features:  53%|██████████▋         | 119/223 [15:00<39:47, 22.96s/it]

Extracted feature row shape: (111, 84)
Fetching LSST 170028531728777309 from Antares...
Lightcurve fetched: 13 alerts, passbands: ['R' 'i' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:27:18.799991            R  61090.268968  23.736225    0.214942
2026-02-19 08:02:41.874357            R  61090.335207  23.683298    0.212031
2026-02-20 05:37:40.803274            i  61091.234500  23.887744    0.323997
2026-02-20 06:34:19.413115            R  61091.273836  23.798372    0.199741
2026-02-20 06:39:19.661042            R  61091.277311  23.611575    0.196513

Extracted lightcurve features for theorized lightcurve in 0.10s!
Engineering features...

Extracting features:  54%|██████████▊         | 120/223 [15:11<32:53, 19.16s/it]

Extracted feature row shape: (1, 84)
Fetching LSST 170028527997943880 from Antares...
Lightcurve fetched: 15 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:04:27.079781            i  61090.253091  22.786086    0.133804
2026-02-23 04:43:17.699469            i  61094.196733  22.832717    0.124301
2026-02-23 04:48:12.575417            i  61094.200146  22.799484    0.107492
2026-02-23 05:01:05.125587            g  61094.209087  22.502680    0.051039
2026-02-23 05:18:38.967929            R  61094.221284  22.529852    0.062422

Extracted lightcurve features for theorized lightcurve in 0.70s!
Engineering features...

Extracting features:  54%|██████████▊         | 121/223 [15:22<28:32, 16.79s/it]

Extracted feature row shape: (11, 84)
Fetching LSST 170032918138191891 from Antares...
Lightcurve fetched: 17 alerts, passbands: ['g' 'R' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-20 05:45:01.087630            g  61091.239596  22.937176    0.200200
2026-02-20 06:21:53.103330            g  61091.265198  22.485670    0.184331
2026-02-20 06:22:33.402369            g  61091.265664  22.904154    0.200987
2026-02-20 06:34:59.771852            R  61091.274303  22.486660    0.186369
2026-02-23 04:53:38.116287            g  61094.203913  22.849914    0.198441

Extracted lightcurve features for theorized lightcurve in 1.93s!
Engineering features...

Extracting features:  55%|██████████▉         | 122/223 [15:36<27:01, 16.06s/it]

Extracted feature row shape: (13, 84)
Fetching LSST 170028535923081252 from Antares...
Lightcurve fetched: 385 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:57:01.776883            i  61090.247937  24.564301    0.792680
2026-02-19 05:58:27.382654            i  61090.248928  24.389982    0.684503
2026-02-19 05:59:47.930124            i  61090.249860  25.158568    1.419660
2026-02-19 06:00:28.230400            i  61090.250327  25.725938    2.366160
2026-02-19 06:01:08.644455            i  61090.250794  28.243296   23.042846

Extracted lightcurve features for theorized lightcurve in 64.54s!
Engineering features...

Extracting features:  55%|███████████         | 123/223 [16:51<56:12, 33.73s/it]

Extracted feature row shape: (365, 84)
Fetching LSST 170028528011051061 from Antares...
Lightcurve fetched: 28 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:04:27.079781            i  61090.253091  22.827025    0.123242
2026-02-19 06:16:26.924656            g  61090.261423  22.849767    0.065268
2026-02-19 06:28:39.351874            R  61090.269900  22.694731    0.070032
2026-02-19 07:34:44.927229            i  61090.315798  22.762007    0.106308
2026-02-19 08:03:22.211708            R  61090.335674  22.642627    0.097445

Extracted lightcurve features for theorized lightcurve in 1.71s!
Engineering features...

Extracting features:  56%|███████████         | 124/223 [17:01<43:35, 26.42s/it]

Extracted feature row shape: (24, 84)
Fetching LSST 170032922922844339 from Antares...
Lightcurve fetched: 80 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:02:26.190294            i  61090.251692  23.282016    0.200031
2026-02-20 06:13:46.157984            i  61091.259562  23.518376    0.229334
2026-02-24 03:59:44.161355            i  61095.166483  23.022788    0.144255
2026-02-24 04:00:24.455360            i  61095.166950  23.302866    0.186816
2026-02-24 04:01:05.307981            i  61095.167423  22.806858    0.127401

Extracted lightcurve features for theorized lightcurve in 4.35s!
Engineering features...

Extracting features:  56%|███████████▏        | 125/223 [17:13<36:05, 22.09s/it]

Extracted feature row shape: (53, 84)
Fetching LSST 170046110922965087 from Antares...
Lightcurve fetched: 11 alerts, passbands: ['R' 'g' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-23 05:12:49.794383            R  61094.217243  22.128597    0.040757
2026-02-23 05:38:03.188144            g  61094.234759  22.116919    0.027806
2026-02-23 06:00:11.161530            R  61094.250129  22.143913    0.039119
2026-02-24 04:03:46.874187            i  61095.169293  22.037412    0.057831
2026-02-24 04:27:59.831668            R  61095.186109  22.154833    0.044613

Extracted lightcurve features for theorized lightcurve in 0.48s!
Engineering features...

Extracting features:  57%|███████████▎        | 126/223 [17:20<28:42, 17.76s/it]

Extracted feature row shape: (7, 84)
Fetching LSST 170028528397451278 from Antares...
Lightcurve fetched: 95 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:06:27.709125            i  61090.254487  22.774541    0.131587
2026-02-19 06:18:27.485474            g  61090.262818  22.891882    0.065040
2026-02-19 06:30:39.879800            R  61090.271295  22.818812    0.081105
2026-02-19 07:36:45.472784            i  61090.317193  22.663194    0.110917
2026-02-19 07:53:12.462878            g  61090.328616  22.733007    0.067107

Extracted lightcurve features for theorized lightcurve in 6.81s!
Engineering features...

Extracting features:  57%|███████████▍        | 127/223 [17:35<26:59, 16.87s/it]

Extracted feature row shape: (91, 84)
Fetching LSST 170028528999333889 from Antares...
Lightcurve fetched: 45 alerts, passbands: ['g' 'R' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:11:47.444393            g  61090.258188  22.073719    0.038898
2026-02-19 06:30:39.879800            R  61090.271295  21.985622    0.041817
2026-02-19 07:36:45.472784            i  61090.317193  22.017731    0.068440
2026-02-19 07:44:33.031624            i  61090.322605  22.030072    0.067834
2026-02-19 07:53:12.462878            g  61090.328616  22.161609    0.044146

Extracted lightcurve features for theorized lightcurve in 2.83s!
Engineering features...

Extracting features:  57%|███████████▍        | 128/223 [17:45<23:33, 14.88s/it]

Extracted feature row shape: (41, 84)
Fetching LSST 170028527120810004 from Antares...
Lightcurve fetched: 257 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:00:28.230400            i  61090.250327  23.114500    0.195289
2026-02-19 06:01:08.644455            i  61090.250794  23.011574    0.158227
2026-02-19 06:01:46.037937            i  61090.251227  22.987710    0.155930
2026-02-19 06:02:26.190294            i  61090.251692  22.848812    0.136398
2026-02-19 06:06:27.709125            i  61090.254487  22.965173    0.158259

Extracted lightcurve features for theorized lightcurve in 29.42s!
Engineering features...

Extracting features:  58%|███████████▌        | 129/223 [18:23<33:58, 21.69s/it]

Extracted feature row shape: (248, 84)
Fetching LSST 170028528457744406 from Antares...
Lightcurve fetched: 216 alerts, passbands: ['g' 'R' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:09:07.592393            g  61090.256338  23.096572    0.085884
2026-02-19 06:09:46.863206            g  61090.256792  23.233664    0.101695
2026-02-19 06:10:27.241420            g  61090.257260  23.112803    0.093408
2026-02-19 06:11:07.280885            g  61090.257723  23.200515    0.092027
2026-02-19 06:11:47.444393            g  61090.258188  23.176864    0.080648

Extracted lightcurve features for theorized lightcurve in 25.30s!
Engineering features...

Extracting features:  58%|███████████▋        | 130/223 [18:56<38:55, 25.11s/it]

Extracted feature row shape: (202, 84)
Fetching LSST 170028528009478217 from Antares...
Lightcurve fetched: 57 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:04:27.079781            i  61090.253091  23.404216    0.217058
2026-02-19 06:16:26.924656            g  61090.261423  22.873189    0.075975
2026-02-19 06:28:39.351874            R  61090.269900  23.112851    0.112852
2026-02-19 07:34:44.927229            i  61090.315798  22.925032    0.130919
2026-02-19 07:51:11.449168            g  61090.327216  22.757399    0.073606

Extracted lightcurve features for theorized lightcurve in 3.85s!
Engineering features...

Extracting features:  59%|███████████▋        | 131/223 [19:07<32:08, 20.96s/it]

Extracted feature row shape: (53, 84)
Fetching LSST 170032917163016282 from Antares...
Lightcurve fetched: 89 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:04:27.079781            i  61090.253091  22.842218    0.123223
2026-02-19 06:06:27.709125            i  61090.254487  22.824141    0.137688
2026-02-19 06:16:26.924656            g  61090.261423  22.869690    0.065105
2026-02-19 06:28:39.351874            R  61090.269900  22.791999    0.079665
2026-02-19 06:30:39.879800            R  61090.271295  22.678085    0.076223

Extracted lightcurve features for theorized lightcurve in 6.84s!
Engineering features...

Extracting features:  59%|███████████▊        | 132/223 [19:21<28:36, 18.86s/it]

Extracted feature row shape: (85, 84)
Fetching LSST 170028530023268399 from Antares...
Lightcurve fetched: 92 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:58:27.382654            i  61090.248928  22.413243    0.091164
2026-02-19 06:04:27.079781            i  61090.253091  22.700061    0.111269
2026-02-19 06:15:46.557593            g  61090.260956  23.262387    0.094504
2026-02-19 06:16:26.924656            g  61090.261423  23.206237    0.095398
2026-02-19 06:22:37.069391            R  61090.265707  22.840959    0.092205

Extracted lightcurve features for theorized lightcurve in 6.42s!
Engineering features...

Extracting features:  60%|███████████▉        | 133/223 [19:35<26:02, 17.36s/it]

Extracted feature row shape: (88, 84)
Fetching LSST 170028527997943835 from Antares...
Lightcurve fetched: 62 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:04:27.079781            i  61090.253091  22.463032    0.088694
2026-02-19 06:06:27.709125            i  61090.254487  22.245975    0.090149
2026-02-19 06:16:26.924656            g  61090.261423  22.507378    0.049795
2026-02-19 06:28:39.351874            R  61090.269900  22.367332    0.057771
2026-02-19 06:30:39.879800            R  61090.271295  22.321891    0.058528

Extracted lightcurve features for theorized lightcurve in 4.89s!
Engineering features...

Extracting features:  60%|████████████        | 134/223 [19:47<23:23, 15.77s/it]

Extracted feature row shape: (58, 84)
Fetching LSST 170028527876833332 from Antares...
Lightcurve fetched: 138 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:03:46.720130            i  61090.252624  22.568532    0.101970
2026-02-19 06:15:46.557593            g  61090.260956  22.845961    0.060989
2026-02-19 06:16:26.924656            g  61090.261423  22.963381    0.071290
2026-02-19 06:27:59.074532            R  61090.269434  22.690935    0.071801
2026-02-19 06:28:39.351874            R  61090.269900  22.738177    0.069590

Extracted lightcurve features for theorized lightcurve in 10.14s!
Engineering features...

Extracting features:  61%|████████████        | 135/223 [20:05<24:03, 16.40s/it]

Extracted feature row shape: (134, 84)
Fetching LSST 170028527458451541 from Antares...
Lightcurve fetched: 76 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:01:46.037937            i  61090.251227  22.780984    0.158857
2026-02-19 06:16:26.924656            g  61090.261423  22.567916    0.063413
2026-02-19 06:27:59.074532            R  61090.269434  22.260502    0.065936
2026-02-19 06:30:39.879800            R  61090.271295  22.841587    0.103565
2026-02-19 07:36:45.472784            i  61090.317193  22.623958    0.115418

Extracted lightcurve features for theorized lightcurve in 5.64s!
Engineering features...

Extracting features:  61%|████████████▏       | 136/223 [20:20<23:06, 15.93s/it]

Extracted feature row shape: (72, 84)
Fetching LSST 170028526924202013 from Antares...
Lightcurve fetched: 263 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:58:27.382654            i  61090.248928  22.002323    0.060892
2026-02-19 05:59:07.502970            i  61090.249392  22.066616    0.070251
2026-02-19 06:03:06.445076            i  61090.252158  22.011535    0.059755
2026-02-19 06:03:46.720130            i  61090.252624  22.249097    0.075223
2026-02-19 06:04:27.079781            i  61090.253091  22.077820    0.059283

Extracted lightcurve features for theorized lightcurve in 118.43s!
Engineering features...

Extracting features:  61%|███████████       | 137/223 [22:26<1:10:20, 49.08s/it]

Extracted feature row shape: (249, 84)
Fetching LSST 170028526531510615 from Antares...
Lightcurve fetched: 141 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:57:01.776883            i  61090.247937  22.412129    0.092571
2026-02-19 05:58:27.382654            i  61090.248928  22.335209    0.086480
2026-02-19 06:03:46.720130            i  61090.252624  22.449593    0.098397
2026-02-19 06:04:27.079781            i  61090.253091  22.442969    0.089159
2026-02-19 06:09:07.592393            g  61090.256338  22.552236    0.056055

Extracted lightcurve features for theorized lightcurve in 13.80s!
Engineering features...

Extracting features:  62%|████████████▍       | 138/223 [22:48<57:47, 40.79s/it]

Extracted feature row shape: (134, 84)
Fetching LSST 170028526789460018 from Antares...
Lightcurve fetched: 203 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:58:27.382654            i  61090.248928  23.118830    0.172340
2026-02-19 06:00:28.230400            i  61090.250327  23.053465    0.194929
2026-02-19 06:03:46.720130            i  61090.252624  22.666740    0.111925
2026-02-19 06:04:27.079781            i  61090.253091  22.739988    0.113975
2026-02-19 06:15:06.248727            g  61090.260489  22.744340    0.062380

Extracted lightcurve features for theorized lightcurve in 20.31s!
Engineering features...

Extracting features:  62%|████████████▍       | 139/223 [23:16<51:47, 37.00s/it]

Extracted feature row shape: (196, 84)
Fetching LSST 170028527993749569 from Antares...
Lightcurve fetched: 231 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 05:58:27.382654            i  61090.248928  22.679697    0.117288
2026-02-19 06:01:08.644455            i  61090.250794  22.649875    0.110621
2026-02-19 06:04:27.079781            i  61090.253091  22.856678    0.123997
2026-02-19 06:10:27.241420            g  61090.257260  23.151629    0.093439
2026-02-19 06:12:27.760237            g  61090.258655  23.054253    0.084777

Extracted lightcurve features for theorized lightcurve in 27.60s!
Engineering features...

Extracting features:  63%|████████████▌       | 140/223 [23:51<50:28, 36.48s/it]

Extracted feature row shape: (224, 84)
Fetching LSST 170028527011758122 from Antares...
Lightcurve fetched: 185 alerts, passbands: ['g' 'R' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2023-05-09 06:07:14.998083            g  60073.255035        NaN         NaN
2023-05-09 08:16:31.998737            R  60073.344815        NaN         NaN
2023-05-13 05:28:12.996463            R  60077.227928  20.707199    0.291873
2023-05-13 08:56:45.003834            g  60077.372743        NaN         NaN
2023-05-15 07:10:29.997133            R  60079.298958        NaN         NaN

Extracted lightcurve features for theorized lightcurve in 20.90s!
Engineering features...

Extracting features:  63%|████████████▋       | 141/223 [24:21<47:00, 34.40s/it]

Extracted feature row shape: (135, 84)
Fetching LSST 170028532033912925 from Antares...
Lightcurve fetched: 23 alerts, passbands: ['R' 'i' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:28:39.351874            R  61090.269900  21.936238    0.040806
2026-02-19 07:34:44.927229            i  61090.315798  21.937145    0.054594
2026-02-19 07:51:11.449168            g  61090.327216  22.108504    0.040760
2026-02-19 08:03:22.211708            R  61090.335674  21.869862    0.049938
2026-02-23 04:48:12.575417            i  61094.200146  21.822001    0.046450

Extracted lightcurve features for theorized lightcurve in 1.55s!
Engineering features...

Extracting features:  64%|████████████▋       | 142/223 [24:29<36:04, 26.72s/it]

Extracted feature row shape: (19, 84)
Fetching LSST 170050505205612651 from Antares...
Lightcurve fetched: 229 alerts, passbands: ['i' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-24 04:06:29.214096            i  61095.171171  22.945795    0.202347
2026-02-24 04:11:09.035826            g  61095.174410  22.748197    0.092158
2026-02-24 04:12:29.825477            g  61095.175345  22.834192    0.106448
2026-02-24 04:15:11.935660            g  61095.177221  22.775946    0.104830
2026-02-24 04:16:32.765991            g  61095.178157  22.851310    0.109192

Extracted lightcurve features for theorized lightcurve in 30.20s!
Engineering features...

Extracting features:  64%|████████████▊       | 143/223 [25:07<40:02, 30.03s/it]

Extracted feature row shape: (218, 84)
Fetching LSST 170028529692442638 from Antares...
Lightcurve fetched: 330 alerts, passbands: ['g' 'R' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:15:06.248727            g  61090.260489  23.897577    0.173363
2026-02-19 06:17:06.759586            g  61090.261884  23.772495    0.152353
2026-02-19 06:18:27.485474            g  61090.262818  23.764835    0.143343
2026-02-19 06:23:57.584971            R  61090.266639  23.163451    0.132394
2026-02-19 06:25:58.404434            R  61090.268037  23.399936    0.154118

Extracted lightcurve features for theorized lightcurve in 51.39s!
Engineering features...

Extracting features:  65%|████████████▉       | 144/223 [26:07<51:24, 39.04s/it]

Extracted feature row shape: (326, 84)
Fetching LSST 170028528545300647 from Antares...
Lightcurve fetched: 299 alerts, passbands: ['g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:09:07.592393            g  61090.256338  21.737575    0.025790
2026-02-19 06:10:27.241420            g  61090.257260  21.746118    0.025886
2026-02-19 06:11:07.280885            g  61090.257723  21.731853    0.026252
2026-02-19 06:12:27.760237            g  61090.258655  21.726173    0.026105
2026-02-19 06:13:08.480999            g  61090.259126  21.723342    0.025636

Extracted lightcurve features for theorized lightcurve in 45.45s!
Engineering features...

Extracting features:  65%|█████████████       | 145/223 [27:01<56:22, 43.37s/it]

Extracted feature row shape: (288, 84)
Fetching LSST 170028528620273678 from Antares...
Lightcurve fetched: 196 alerts, passbands: ['g' 'R' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 06:09:07.592393            g  61090.256338  23.497924    0.130730
2026-02-19 06:09:46.863206            g  61090.256792  23.734927    0.169047
2026-02-19 06:11:07.280885            g  61090.257723  23.985144    0.190297
2026-02-19 06:11:47.444393            g  61090.258188  23.594621    0.126724
2026-02-19 06:12:27.760237            g  61090.258655  23.565332    0.137970

Extracted lightcurve features for theorized lightcurve in 23.74s!
Engineering features...

Extracting features:  65%|█████████████       | 146/223 [27:32<51:09, 39.86s/it]

Extracted feature row shape: (184, 84)
Fetching LSST 313831458514927674 from Antares...
Lightcurve fetched: 336 alerts, passbands: ['g' 'i' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-10 06:57:12.266929            g  61019.289725  23.701900    0.214409
2025-12-15 03:16:22.446274            i  61024.136371  23.295602    0.132986
2025-12-15 03:39:42.161239            i  61024.152571  23.305022    0.113805
2025-12-17 04:40:51.412032            i  61026.195039  23.396517    0.118713
2025-12-17 05:17:51.600128            i  61026.220736  23.210572    0.096753

Extracted lightcurve features for theorized lightcurve in 39.30s!
Engineering features...

Extracting features:  66%|█████████████▏      | 147/223 [28:21<53:39, 42.37s/it]

Extracted feature row shape: (330, 84)
Fetching LSST 313941448959459395 from Antares...
Lightcurve fetched: 322 alerts, passbands: ['R' 'z' 'g' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-04 03:10:52.862737            R  61044.132556  22.932371    0.120637
2026-01-04 03:28:05.553230            z  61044.144509  22.976434    0.156220
2026-01-05 01:51:24.741225            g  61045.077370  22.991689    0.096749
2026-01-05 01:57:00.224732            i  61045.081253  22.837017    0.094560
2026-01-06 03:43:21.431426            z  61046.155109  22.506341    0.093188

Extracted lightcurve features for theorized lightcurve in 32.30s!
Engineering features...

Extracting features:  66%|█████████████▎      | 148/223 [29:01<52:05, 41.67s/it]

Extracted feature row shape: (318, 84)
Fetching LSST 313871013802672296 from Antares...
Lightcurve fetched: 321 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:43:33.396969            R  61028.321914  22.326187    0.047359
2025-12-19 07:44:13.574976            R  61028.322379  22.354875    0.045863
2025-12-19 07:53:09.071353            R  61028.328577  22.262977    0.043631
2025-12-19 07:53:49.127431            R  61028.329041  22.324435    0.048673
2025-12-19 07:54:29.187474            R  61028.329504  22.382391    0.051082

Extracted lightcurve features for theorized lightcurve in 31.86s!
Engineering features...

Extracting features:  67%|█████████████▎      | 149/223 [29:40<50:30, 40.95s/it]

Extracted feature row shape: (314, 84)
Fetching LSST 313871014435488133 from Antares...
Lightcurve fetched: 86 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:50:29.275315            R  61028.326728  23.692968    0.161243
2025-12-19 07:51:49.014062            R  61028.327651  24.062996    0.218782
2025-12-24 06:48:46.250407            g  61033.283869  23.481452    0.133596
2025-12-24 06:49:26.198131            g  61033.284331  23.452877    0.120824
2025-12-25 03:50:56.443275            g  61034.160376  23.402725    0.073643

Extracted lightcurve features for theorized lightcurve in 6.84s!
Engineering features...

Extracting features:  67%|█████████████▍      | 150/223 [29:54<39:59, 32.87s/it]

Extracted feature row shape: (82, 84)
Fetching LSST 313936964384981047 from Antares...
Lightcurve fetched: 136 alerts, passbands: ['g' 'R' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-03 01:36:04.436130            g  61043.066718  23.092583    0.178376
2026-01-04 03:10:12.454476            R  61044.132089  22.708802    0.109702
2026-01-09 02:34:34.479694            i  61049.107344  21.803165    0.050965
2026-01-09 02:35:14.623407            i  61049.107808  21.892274    0.057927
2026-01-09 02:48:32.958726            g  61049.117048  22.314679    0.048801

Extracted lightcurve features for theorized lightcurve in 11.64s!
Engineering features...

Extracting features:  68%|█████████████▌      | 151/223 [30:13<34:32, 28.78s/it]

Extracted feature row shape: (132, 84)
Fetching LSST 313980945119576112 from Antares...
Lightcurve fetched: 304 alerts, passbands: ['g' 'R' 'z' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-13 05:35:29.884018            g  61053.232985  23.206721    0.099913
2026-01-14 03:37:37.601224            R  61054.151130  22.574931    0.046684
2026-01-14 03:38:12.147878            R  61054.151529  22.558583    0.044980
2026-01-14 03:39:47.742027            R  61054.152636  22.567035    0.046745
2026-01-14 03:40:22.065031            R  61054.153033  22.536639    0.044400

Extracted lightcurve features for theorized lightcurve in 37.20s!
Engineering features...

Extracting features:  68%|█████████████▋      | 152/223 [30:58<39:44, 33.58s/it]

Extracted feature row shape: (300, 84)
Fetching LSST 313928194157183045 from Antares...
Lightcurve fetched: 101 alerts, passbands: ['i' 'R' 'z' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-01 05:18:35.427971            i  61041.221243  22.542455    0.083828
2026-01-01 05:25:01.975558            i  61041.225717  22.336622    0.075941
2026-01-02 02:34:38.091000            i  61042.107385  22.274296    0.066975
2026-01-02 02:35:17.964442            i  61042.107847  22.191399    0.061611
2026-01-03 01:52:19.143698            i  61043.077999  21.937535    0.060941

Extracted lightcurve features for theorized lightcurve in 6.49s!
Engineering features...

Extracting features:  69%|█████████████▋      | 153/223 [31:13<32:37, 27.96s/it]

Extracted feature row shape: (91, 84)
Fetching LSST 313756671825412125 from Antares...
Lightcurve fetched: 351 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-23 05:33:00.218019            R  61002.231253  23.900325    0.161728
2025-11-24 07:47:07.576858            g  61003.324393  23.996069    0.158343
2025-12-15 03:39:01.833492            i  61024.152105  23.903499    0.211293
2025-12-19 07:43:33.396969            R  61028.321914  23.753691    0.172565
2025-12-19 07:44:13.574976            R  61028.322379  23.661590    0.148388

Extracted lightcurve features for theorized lightcurve in 47.86s!
Engineering features...

Extracting features:  69%|█████████████▊      | 154/223 [32:09<41:47, 36.33s/it]

Extracted feature row shape: (347, 84)
Fetching LSST 314051320414732370 from Antares...
Lightcurve fetched: 339 alerts, passbands: ['g' 'i' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-29 01:52:36.012492            g  61069.078195  22.739384    0.098117
2026-01-29 02:01:10.000373            i  61069.084144  22.224532    0.063545
2026-02-17 02:21:48.358651            R  61088.098476  21.981660    0.026828
2026-02-19 01:08:31.268724            i  61090.047584  21.908939    0.038075
2026-02-19 01:09:46.553006            i  61090.048455  21.988014    0.037554

Extracted lightcurve features for theorized lightcurve in 33.40s!
Engineering features...

Extracting features:  70%|█████████████▉      | 155/223 [32:50<42:49, 37.79s/it]

Extracted feature row shape: (335, 84)
Fetching LSST 313761042284412983 from Antares...
Lightcurve fetched: 262 alerts, passbands: ['g' 'z' 'i' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-24 07:45:51.609272            g  61003.323514  22.996903    0.071612
2025-11-25 07:18:09.144488            z  61004.304273  22.711405    0.209582
2025-11-27 05:07:30.891990            i  61006.213552  22.108344    0.039083
2025-11-27 05:23:15.928088            i  61006.224490  22.097759    0.034586
2025-11-27 05:23:58.648624            i  61006.224984  22.021341    0.034529

Extracted lightcurve features for theorized lightcurve in 23.94s!
Engineering features...

Extracting features:  70%|█████████████▉      | 156/223 [33:22<40:14, 36.03s/it]

Extracted feature row shape: (243, 84)
Fetching LSST 313765480704245975 from Antares...
Lightcurve fetched: 172 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-25 07:15:13.235945            R  61004.302237  23.465819    0.110380
2025-12-24 06:50:06.086517            g  61033.284793  24.094029    0.207997
2025-12-24 06:50:46.306671            g  61033.285258  23.642652    0.140733
2025-12-25 03:52:16.672706            g  61034.161304  24.085124    0.124818
2025-12-25 03:52:56.640343            g  61034.161767  23.981506    0.117701

Extracted lightcurve features for theorized lightcurve in 14.10s!
Engineering features...

Extracting features:  70%|██████████████      | 157/223 [33:43<34:50, 31.67s/it]

Extracted feature row shape: (168, 84)
Fetching LSST 313945770525982796 from Antares...
Lightcurve fetched: 105 alerts, passbands: ['i' 'g' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-05 01:57:00.224732            i  61045.081253  23.385181    0.148736
2026-01-09 02:35:14.623407            i  61049.107808  23.009230    0.141986
2026-01-09 02:49:13.658766            g  61049.117519  23.642446    0.128447
2026-01-10 02:45:56.727475            R  61050.115240  22.622609    0.067930
2026-01-11 01:52:38.035487            g  61051.078218  23.579606    0.076404

Extracted lightcurve features for theorized lightcurve in 7.31s!
Engineering features...

Extracting features:  71%|██████████████▏     | 158/223 [33:58<28:45, 26.55s/it]

Extracted feature row shape: (101, 84)
Fetching LSST 313893022930567256 from Antares...
Lightcurve fetched: 233 alerts, passbands: ['g' 'i' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-24 06:49:26.198131            g  61033.284331  23.998749    0.186330
2025-12-25 03:50:56.443275            g  61034.160376  23.908019    0.112448
2025-12-25 03:51:36.440503            g  61034.160838  23.975151    0.117472
2026-01-01 05:18:35.427971            i  61041.221243  21.870059    0.049150
2026-01-01 05:25:01.975558            i  61041.225717  21.960062    0.058935

Extracted lightcurve features for theorized lightcurve in 21.72s!
Engineering features...

Extracting features:  71%|██████████████▎     | 159/223 [34:27<29:06, 27.29s/it]

Extracted feature row shape: (225, 84)
Fetching LSST 313853497671417905 from Antares...
Lightcurve fetched: 313 alerts, passbands: ['i' 'R' 'z' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 03:17:02.614158            i  61024.136836  23.802442    0.214892
2025-12-15 03:39:01.833492            i  61024.152105  23.961602    0.210857
2025-12-17 04:52:32.732968            i  61026.203157  23.714101    0.157872
2025-12-17 05:17:51.600128            i  61026.220736  23.743037    0.157860
2025-12-17 05:18:31.735893            i  61026.221201  23.947010    0.182483

Extracted lightcurve features for theorized lightcurve in 27.01s!
Engineering features...

Extracting features:  72%|██████████████▎     | 160/223 [35:01<30:53, 29.43s/it]

Extracted feature row shape: (268, 84)
Fetching LSST 313831458450440303 from Antares...
Lightcurve fetched: 285 alerts, passbands: ['g' 'z' 'i' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-10 06:57:12.266929            g  61019.289725  22.690024    0.100851
2025-12-11 05:42:33.442095            z  61020.237887  22.859162    0.178265
2025-12-11 05:48:25.414771            z  61020.241961  22.966310    0.194954
2025-12-11 05:49:05.839048            z  61020.242429  23.105478    0.185534
2025-12-15 03:16:22.446274            i  61024.136371  23.036893    0.116108

Extracted lightcurve features for theorized lightcurve in 27.89s!
Engineering features...

Extracting features:  72%|██████████████▍     | 161/223 [35:37<32:13, 31.19s/it]

Extracted feature row shape: (271, 84)
Fetching LSST 313897383783038984 from Antares...
Lightcurve fetched: 122 alerts, passbands: ['g' 'i' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-25 03:51:36.440503            g  61034.160838  24.137914    0.141080
2025-12-25 03:52:16.672706            g  61034.161304  24.136347    0.126561
2025-12-25 03:52:56.640343            g  61034.161767  24.051229    0.119871
2026-01-01 05:19:15.408344            i  61041.221706  22.405751    0.078586
2026-01-01 05:25:41.829369            i  61041.226179  22.395733    0.085334

Extracted lightcurve features for theorized lightcurve in 8.21s!
Engineering features...

Extracting features:  73%|██████████████▌     | 162/223 [35:52<26:53, 26.45s/it]

Extracted feature row shape: (115, 84)
Fetching LSST 170019696437887107 from Antares...
Lightcurve fetched: 327 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 02:21:48.358651            R  61088.098476  22.001598    0.028025
2026-02-19 01:08:31.268724            i  61090.047584  22.147526    0.047626
2026-02-19 01:09:46.553006            i  61090.048455  22.132924    0.045460
2026-02-19 01:18:20.914365            i  61090.054409  22.159247    0.050266
2026-02-19 01:19:35.762826            i  61090.055275  22.126083    0.045373

Extracted lightcurve features for theorized lightcurve in 36.99s!
Engineering features...

Extracting features:  73%|██████████████▌     | 163/223 [36:37<31:58, 31.98s/it]

Extracted feature row shape: (317, 84)
Fetching LSST 170019696466198671 from Antares...
Lightcurve fetched: 368 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 02:21:48.358651            R  61088.098476  22.000342    0.031877
2026-02-19 01:08:31.268724            i  61090.047584  22.347631    0.065861
2026-02-19 01:09:46.553006            i  61090.048455  22.174767    0.053800
2026-02-19 01:17:06.229662            i  61090.053544  22.232340    0.055323
2026-02-19 01:18:20.914365            i  61090.054409  22.203322    0.059080

Extracted lightcurve features for theorized lightcurve in 42.63s!
Engineering features...

Extracting features:  74%|██████████████▋     | 164/223 [37:27<36:46, 37.40s/it]

Extracted feature row shape: (355, 84)
Fetching LSST 313765480559017992 from Antares...
Lightcurve fetched: 118 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-25 07:14:33.555615            R  61004.301777  23.775718    0.112611
2025-11-27 05:23:15.928088            i  61006.224490  24.075848    0.203658
2025-11-29 01:27:14.095235            i  61008.060580  23.509151    0.198275
2025-12-10 06:56:32.338648            g  61019.289263  22.731170    0.095187
2025-12-10 06:59:56.522349            i  61019.291626  22.752237    0.138642

Extracted lightcurve features for theorized lightcurve in 8.21s!
Engineering features...

Extracting features:  74%|██████████████▊     | 165/223 [37:42<29:46, 30.81s/it]

Extracted feature row shape: (114, 84)
Fetching LSST 313871013530042570 from Antares...
Lightcurve fetched: 174 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:42:13.851327            R  61028.320994  23.884414    0.173876
2025-12-19 07:42:53.695422            R  61028.321455  23.967482    0.187328
2025-12-19 07:50:29.275315            R  61028.326728  24.092319    0.193970
2025-12-19 07:51:09.230541            R  61028.327190  23.894787    0.162754
2025-12-19 07:51:49.014062            R  61028.327651  23.657236    0.136982

Extracted lightcurve features for theorized lightcurve in 12.57s!
Engineering features...

Extracting features:  74%|██████████████▉     | 166/223 [38:07<27:36, 29.06s/it]

Extracted feature row shape: (165, 84)
Fetching LSST 313994145051443228 from Antares...
Lightcurve fetched: 304 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-16 05:06:23.145565            R  61056.212768  23.846900    0.194578
2026-01-29 01:51:58.718019            g  61069.077763  22.505860    0.090792
2026-01-29 02:00:32.427815            i  61069.083709  22.343351    0.081772
2026-02-17 02:21:11.105457            R  61088.098045  22.099758    0.038411
2026-02-19 01:09:09.057408            i  61090.048021  22.172623    0.057246

Extracted lightcurve features for theorized lightcurve in 34.34s!
Engineering features...

Extracting features:  75%|██████████████▉     | 167/223 [38:51<31:03, 33.28s/it]

Extracted feature row shape: (300, 84)
Fetching LSST 313756671695913113 from Antares...
Lightcurve fetched: 330 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-23 05:32:19.168401            R  61002.230777  24.001927    0.192967
2025-11-23 05:33:00.218019            R  61002.231253  23.760591    0.143677
2025-11-24 07:47:07.576858            g  61003.324393  23.950874    0.139149
2025-11-24 08:04:49.076854            R  61003.336679  23.819171    0.198067
2025-11-25 07:15:13.235945            R  61004.302237  24.138313    0.186516

Extracted lightcurve features for theorized lightcurve in 52.51s!
Engineering features...

Extracting features:  75%|███████████████     | 168/223 [39:52<38:08, 41.60s/it]

Extracted feature row shape: (326, 84)
Fetching LSST 170019696437362764 from Antares...
Lightcurve fetched: 356 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 02:21:48.358651            R  61088.098476  23.455410    0.112174
2026-02-19 01:08:31.268724            i  61090.047584  23.103592    0.117626
2026-02-19 01:09:46.553006            i  61090.048455  23.356581    0.140142
2026-02-19 01:17:06.229662            i  61090.053544  23.335123    0.140802
2026-02-19 01:19:35.762826            i  61090.055275  23.372537    0.150535

Extracted lightcurve features for theorized lightcurve in 44.10s!
Engineering features...

Extracting features:  76%|███████████████▏    | 169/223 [40:43<40:09, 44.62s/it]

Extracted feature row shape: (346, 84)
Fetching LSST 314051321101549625 from Antares...
Lightcurve fetched: 317 alerts, passbands: ['i' 'R' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-29 02:00:32.427815            i  61069.083709  22.900504    0.118026
2026-02-17 02:21:11.105457            R  61088.098045  22.068014    0.031529
2026-02-19 01:16:28.876779            i  61090.053112  22.267185    0.054659
2026-02-19 01:17:43.489316            i  61090.053976  22.343338    0.062403
2026-02-19 01:18:58.193350            i  61090.054840  22.281974    0.055245

Extracted lightcurve features for theorized lightcurve in 36.31s!
Engineering features...

Extracting features:  76%|███████████████▏    | 170/223 [41:27<39:12, 44.39s/it]

Extracted feature row shape: (307, 84)
Fetching LSST 313756671722127979 from Antares...
Lightcurve fetched: 147 alerts, passbands: ['R' 'g' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-23 05:32:19.168401            R  61002.230777  23.036253    0.087163
2025-11-24 07:45:51.609272            g  61003.323514  23.829984    0.168671
2025-11-25 07:14:33.555615            R  61004.301777  23.110842    0.089644
2025-12-19 07:42:13.851327            R  61028.320994  22.561882    0.067272
2025-12-19 07:42:53.695422            R  61028.321455  22.383564    0.057216

Extracted lightcurve features for theorized lightcurve in 13.59s!
Engineering features...

Extracting features:  77%|███████████████▎    | 171/223 [41:48<32:23, 37.37s/it]

Extracted feature row shape: (143, 84)
Fetching LSST 313853497291309068 from Antares...
Lightcurve fetched: 195 alerts, passbands: ['i' 'R' 'z' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 03:14:53.415283            i  61024.135340  23.431778    0.140716
2025-12-15 03:17:02.614158            i  61024.136836  23.597353    0.189484
2025-12-15 03:37:42.365291            i  61024.151185  23.300552    0.127717
2025-12-15 03:38:21.661481            i  61024.151640  23.464766    0.142045
2025-12-15 03:39:01.833492            i  61024.152105  23.537629    0.151484

Extracted lightcurve features for theorized lightcurve in 13.29s!
Engineering features...

Extracting features:  77%|███████████████▍    | 172/223 [42:09<27:33, 32.42s/it]

Extracted feature row shape: (172, 84)
Fetching LSST 313761042410242140 from Antares...
Lightcurve fetched: 313 alerts, passbands: ['g' 'R' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-24 07:47:07.576858            g  61003.324393  24.076943    0.155793
2026-01-09 02:49:13.658766            g  61049.117519  23.760922    0.161691
2026-01-11 01:52:38.035487            g  61051.078218  23.554310    0.092936
2026-01-13 05:36:07.437865            g  61053.233419  23.639141    0.180680
2026-01-17 04:16:01.425723            g  61057.177794  23.377587    0.089226

Extracted lightcurve features for theorized lightcurve in 38.13s!
Engineering features...

Extracting features:  78%|███████████████▌    | 173/223 [42:56<30:40, 36.81s/it]

Extracted feature row shape: (308, 84)
Fetching LSST 313853497321193628 from Antares...
Lightcurve fetched: 153 alerts, passbands: ['i' 'R' 'z' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 03:14:53.415283            i  61024.135340  22.649686    0.071447
2025-12-15 03:15:42.265401            i  61024.135906  22.611675    0.071821
2025-12-15 03:37:42.365291            i  61024.151185  22.528935    0.062198
2025-12-15 03:38:21.661481            i  61024.151640  22.588147    0.060358
2025-12-17 04:39:23.797025            i  61026.194025  22.572066    0.068248

Extracted lightcurve features for theorized lightcurve in 10.35s!
Engineering features...

Extracting features:  78%|███████████████▌    | 174/223 [43:14<25:26, 31.16s/it]

Extracted feature row shape: (134, 84)
Fetching LSST 313928194187591742 from Antares...
Lightcurve fetched: 96 alerts, passbands: ['i' 'z' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-01 05:18:35.427971            i  61041.221243  23.342714    0.170350
2026-01-02 02:34:38.091000            i  61042.107385  23.097599    0.147964
2026-01-03 01:52:19.143698            i  61043.077999  23.171703    0.189196
2026-01-04 03:27:24.992776            z  61044.144039  22.751087    0.158271
2026-01-06 03:42:41.304952            z  61046.154645  22.836404    0.130283

Extracted lightcurve features for theorized lightcurve in 6.31s!
Engineering features...

Extracting features:  78%|███████████████▋    | 175/223 [43:28<20:48, 26.01s/it]

Extracted feature row shape: (90, 84)
Fetching LSST 313853501446815761 from Antares...
Lightcurve fetched: 262 alerts, passbands: ['i' 'R' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 03:39:42.161239            i  61024.152571  23.397633    0.125451
2025-12-17 04:40:51.412032            i  61026.195039  22.490259    0.055314
2025-12-17 05:17:51.600128            i  61026.220736  22.414194    0.048932
2025-12-17 05:19:12.351287            i  61026.221671  22.466397    0.050398
2025-12-17 05:19:53.418911            i  61026.222146  22.490590    0.050852

Extracted lightcurve features for theorized lightcurve in 22.47s!
Engineering features...

Extracting features:  79%|███████████████▊    | 176/223 [43:58<21:18, 27.19s/it]

Extracted feature row shape: (254, 84)
Fetching LSST 313893023086280813 from Antares...
Lightcurve fetched: 156 alerts, passbands: ['g' 'i' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-24 06:50:06.086517            g  61033.284793  23.235482    0.099364
2025-12-24 06:50:46.306671            g  61033.285258  23.533990    0.135267
2025-12-25 03:52:16.672706            g  61034.161304  23.167594    0.062066
2026-01-02 02:35:58.080050            i  61042.108311  22.742748    0.104670
2026-01-02 02:36:38.268749            i  61042.108776  22.635270    0.097219

Extracted lightcurve features for theorized lightcurve in 11.49s!
Engineering features...

Extracting features:  79%|███████████████▊    | 177/223 [44:17<18:53, 24.65s/it]

Extracted feature row shape: (144, 84)
Fetching LSST 313945770546430083 from Antares...
Lightcurve fetched: 187 alerts, passbands: ['i' 'z' 'g' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-05 01:57:00.224732            i  61045.081253  23.551303    0.167740
2026-01-06 03:43:21.431426            z  61046.155109  23.291875    0.186114
2026-01-09 02:49:13.658766            g  61049.117519  22.919326    0.068595
2026-01-10 02:45:56.727475            R  61050.115240  22.404509    0.060190
2026-01-11 01:52:38.035487            g  61051.078218  22.640901    0.035653

Extracted lightcurve features for theorized lightcurve in 16.67s!
Engineering features...

Extracting features:  80%|███████████████▉    | 178/223 [44:40<18:17, 24.38s/it]

Extracted feature row shape: (183, 84)
Fetching LSST 313950161909317636 from Antares...
Lightcurve fetched: 93 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-06 03:50:31.631606            R  61046.160088  23.153105    0.123981
2026-01-09 02:48:32.958726            g  61049.117048  23.647837    0.151865
2026-01-10 02:45:18.721923            R  61050.114800  22.749603    0.095282
2026-01-11 01:51:59.189229            g  61051.077768  23.371130    0.072692
2026-01-11 02:06:09.108139            i  61051.087605  22.852893    0.082387

Extracted lightcurve features for theorized lightcurve in 6.52s!
Engineering features...

Extracting features:  80%|████████████████    | 179/223 [44:54<15:29, 21.12s/it]

Extracted feature row shape: (89, 84)
Fetching LSST 313871013794283597 from Antares...
Lightcurve fetched: 90 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:43:33.396969            R  61028.321914  23.547819    0.134297
2025-12-19 07:44:13.574976            R  61028.322379  23.486671    0.115990
2025-12-19 07:54:29.187474            R  61028.329504  23.686905    0.151345
2025-12-19 07:55:09.416708            R  61028.329970  23.388676    0.125629
2025-12-24 06:50:06.086517            g  61033.284793  23.010302    0.076770

Extracted lightcurve features for theorized lightcurve in 6.31s!
Engineering features...

Extracting features:  81%|████████████████▏   | 180/223 [45:08<13:31, 18.88s/it]

Extracted feature row shape: (86, 84)
Fetching LSST 313853501480894545 from Antares...
Lightcurve fetched: 118 alerts, passbands: ['i' 'R' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 03:39:42.161239            i  61024.152571  23.616184    0.162787
2025-12-17 04:40:51.412032            i  61026.195039  23.422954    0.128059
2025-12-17 04:52:32.732968            i  61026.203157  23.283876    0.116491
2025-12-17 05:18:31.735893            i  61026.221201  23.313259    0.117071
2025-12-17 05:19:12.351287            i  61026.221671  23.322616    0.113869

Extracted lightcurve features for theorized lightcurve in 8.17s!
Engineering features...

Extracting features:  81%|████████████████▏   | 181/223 [45:23<12:27, 17.81s/it]

Extracted feature row shape: (105, 84)
Fetching LSST 313967752817672227 from Antares...
Lightcurve fetched: 182 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-10 02:45:56.727475            R  61050.115240  23.732588    0.179861
2026-01-11 01:52:38.035487            g  61051.078218  24.497424    0.165108
2026-01-11 02:06:47.375047            i  61051.088048  23.518784    0.179785
2026-01-13 05:36:07.437865            g  61053.233419  23.971971    0.190668
2026-01-13 05:41:45.432455            i  61053.237331  23.036570    0.201199

Extracted lightcurve features for theorized lightcurve in 15.30s!
Engineering features...

Extracting features:  82%|████████████████▎   | 182/223 [45:45<13:09, 19.25s/it]

Extracted feature row shape: (178, 84)
Fetching LSST 313756671858442321 from Antares...
Lightcurve fetched: 97 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-23 05:33:00.218019            R  61002.231253  23.997647    0.155668
2025-11-23 06:26:26.750041            R  61002.268365  24.191711    0.204741
2025-12-15 03:39:42.161239            i  61024.152571  23.173605    0.109323
2025-12-17 04:40:51.412032            i  61026.195039  23.103061    0.103177
2025-12-17 05:17:51.600128            i  61026.220736  23.055478    0.094974

Extracted lightcurve features for theorized lightcurve in 6.20s!
Engineering features...

Extracting features:  82%|████████████████▍   | 183/223 [45:59<11:36, 17.41s/it]

Extracted feature row shape: (88, 84)
Fetching LSST 313928194151940140 from Antares...
Lightcurve fetched: 180 alerts, passbands: ['i' 'g' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-01 05:18:35.427971            i  61041.221243  22.786015    0.109355
2026-01-01 05:25:01.975558            i  61041.225717  22.836703    0.122364
2026-01-02 02:34:38.091000            i  61042.107385  22.643402    0.095326
2026-01-02 02:35:17.964442            i  61042.107847  22.416736    0.073226
2026-01-03 01:35:24.650560            g  61043.066258  22.889195    0.193441

Extracted lightcurve features for theorized lightcurve in 12.93s!
Engineering features...

Extracting features:  83%|████████████████▌   | 184/223 [46:19<11:53, 18.29s/it]

Extracted feature row shape: (174, 84)
Fetching LSST 170050474601349124 from Antares...
Lightcurve fetched: 143 alerts, passbands: ['i' 'g' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-24 01:09:26.242579            i  61095.048220  23.009331    0.168013
2026-02-24 01:16:39.800448            g  61095.053238  22.590471    0.073186
2026-02-24 01:17:54.414792            g  61095.054102  22.422950    0.065975
2026-02-24 01:19:09.569778            g  61095.054972  22.461641    0.067825
2026-02-24 01:19:46.819361            g  61095.055403  22.464026    0.071983

Extracted lightcurve features for theorized lightcurve in 11.22s!
Engineering features...

Extracting features:  83%|████████████████▌   | 185/223 [46:38<11:41, 18.46s/it]

Extracted feature row shape: (128, 84)
Fetching LSST 313871013549441166 from Antares...
Lightcurve fetched: 123 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:42:13.851327            R  61028.320994  23.745340    0.183993
2025-12-19 07:42:53.695422            R  61028.321455  23.628698    0.165866
2025-12-19 07:43:33.396969            R  61028.321914  23.563796    0.148556
2025-12-19 07:50:29.275315            R  61028.326728  23.922863    0.215818
2025-12-19 07:51:09.230541            R  61028.327190  23.723521    0.172546

Extracted lightcurve features for theorized lightcurve in 9.76s!
Engineering features...

Extracting features:  83%|████████████████▋   | 186/223 [46:56<11:17, 18.32s/it]

Extracted feature row shape: (116, 84)
Fetching LSST 313761042386124904 from Antares...
Lightcurve fetched: 276 alerts, passbands: ['g' 'i' 'z' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-24 07:47:07.576858            g  61003.324393  23.553352    0.115276
2026-01-11 01:52:38.035487            g  61051.078218  23.882961    0.160704
2026-01-13 05:36:07.437865            g  61053.233419  23.156183    0.129316
2026-01-17 04:16:01.425723            g  61057.177794  23.038470    0.071250
2026-01-19 03:47:45.867983            g  61059.158170  22.858371    0.075731

Extracted lightcurve features for theorized lightcurve in 26.29s!
Engineering features...

Extracting features:  84%|████████████████▊   | 187/223 [47:30<13:46, 22.96s/it]

Extracted feature row shape: (240, 84)
Fetching LSST 313963359527501831 from Antares...

Extracting features:  84%|████████████████▊   | 188/223 [52:04<57:22, 98.36s/it]

FAILED: 313963359527501831 — HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Read timed out. (read timeout=60)
Fetching LSST 313756673035468835 from Antares...
Lightcurve fetched: 320 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-23 05:49:49.636845            R  61002.242936  23.545339    0.200678
2026-02-19 01:08:31.268724            i  61090.047584  21.162249    0.028911
2026-02-19 01:09:46.553006            i  61090.048455  21.151832    0.027372
2026-02-19 01:17:06.229662            i  61090.053544  21.099476    0.025665
2026-02-19 01:18:20.914365            i  61090.054409  21.183418    0.030680

Extracted lightcurve features for theorized lightcurve in 35.51s!
Engineering features...

Extracting features:  85%|████████████████▉   | 189/223 [52:47<46:23, 81.86s/it]

Extracted feature row shape: (311, 84)
Fetching LSST 313897383678181486 from Antares...
Lightcurve fetched: 296 alerts, passbands: ['g' 'R' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-25 03:50:56.443275            g  61034.160376  23.387188    0.101808
2025-12-25 03:51:36.440503            g  61034.160838  23.459920    0.109657
2026-01-09 02:48:32.958726            g  61049.117048  23.150074    0.114398
2026-01-11 01:51:59.189229            g  61051.077768  22.969803    0.077377
2026-01-16 05:04:12.527725            R  61056.211256  23.243115    0.132698

Extracted lightcurve features for theorized lightcurve in 33.60s!
Engineering features...

Extracting features:  85%|█████████████████   | 190/223 [53:29<38:20, 69.70s/it]

Extracted feature row shape: (292, 84)
Fetching LSST 313756673012400719 from Antares...
Lightcurve fetched: 62 alerts, passbands: ['R' 'g' 'z' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-23 05:49:49.636845            R  61002.242936  23.188992    0.123647
2025-11-24 07:47:07.576858            g  61003.324393  23.371109    0.113884
2025-11-24 08:04:49.076854            R  61003.336679  23.239964    0.123438
2025-11-25 07:15:13.235945            R  61004.302237  23.077609    0.090815
2025-12-10 06:57:12.266929            g  61019.289725  23.191842    0.170800

Extracted lightcurve features for theorized lightcurve in 4.65s!
Engineering features...

Extracting features:  86%|█████████████████▏  | 191/223 [53:41<27:59, 52.49s/it]

Extracted feature row shape: (58, 84)
Fetching LSST 313699506405244961 from Antares...
Lightcurve fetched: 265 alerts, passbands: ['i' 'R' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-10 05:13:27.754750            i  60989.217682  23.724562    0.221411
2025-11-27 05:07:30.891990            i  61006.213552  23.351176    0.130705
2025-12-15 03:38:21.661481            i  61024.151640  23.484791    0.153765
2025-12-17 04:39:23.797025            i  61026.194025  23.249550    0.148958
2025-12-19 07:51:49.014062            R  61028.327651  23.015714    0.096398

Extracted lightcurve features for theorized lightcurve in 26.52s!
Engineering features...

Extracting features:  86%|█████████████████▏  | 192/223 [54:15<24:16, 46.99s/it]

Extracted feature row shape: (258, 84)
Fetching LSST 170028488668479507 from Antares...
Lightcurve fetched: 175 alerts, passbands: ['g' 'R' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 01:30:24.817271            g  61090.062787  24.016841    0.160060
2026-02-19 01:31:02.452691            g  61090.063223  24.079278    0.159240
2026-02-19 01:33:31.836547            g  61090.064952  24.101360    0.198930
2026-02-19 01:34:46.279993            g  61090.065813  24.187402    0.174730
2026-02-19 01:35:43.008794            g  61090.066470  24.106722    0.217213

Extracted lightcurve features for theorized lightcurve in 15.27s!
Engineering features...

Extracting features:  87%|█████████████████▎  | 193/223 [54:38<19:54, 39.83s/it]

Extracted feature row shape: (162, 84)
Fetching LSST 170028497264181363 from Antares...
Lightcurve fetched: 91 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 02:15:26.247355            R  61090.094054  23.265622    0.152220
2026-02-19 02:21:58.970295            R  61090.098599  23.635993    0.209691
2026-02-19 02:25:42.963110            R  61090.101192  23.172045    0.142047
2026-02-19 02:29:33.975726            R  61090.103865  23.628745    0.202814
2026-02-20 00:38:19.421189            i  61091.026614  23.060535    0.166386

Extracted lightcurve features for theorized lightcurve in 6.91s!
Engineering features...

Extracting features:  87%|█████████████████▍  | 194/223 [54:52<15:30, 32.10s/it]

Extracted feature row shape: (84, 84)
Fetching LSST 313985346353234012 from Antares...
Lightcurve fetched: 203 alerts, passbands: ['R' 'z' 'g' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-14 03:37:37.601224            R  61054.151130  23.398520    0.092589
2026-01-14 03:38:12.147878            R  61054.151529  23.347186    0.084781
2026-01-14 03:39:47.742027            R  61054.152636  23.387017    0.089150
2026-01-14 03:40:22.065031            R  61054.153033  23.364699    0.083834
2026-01-14 03:41:58.367967            R  61054.154148  23.381016    0.080126

Extracted lightcurve features for theorized lightcurve in 18.45s!
Engineering features...

Extracting features:  87%|█████████████████▍  | 195/223 [55:18<14:07, 30.26s/it]

Extracted feature row shape: (191, 84)
Fetching LSST 313756671682281480 from Antares...
Lightcurve fetched: 112 alerts, passbands: ['R' 'z' 'g' 'i']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-23 05:32:19.168401            R  61002.230777  22.490501    0.046360
2025-11-23 05:41:44.223239            z  61002.237317  23.153730    0.187555
2025-11-24 07:45:51.609272            g  61003.323514  22.486086    0.040991
2025-11-25 07:14:33.555615            R  61004.301777  22.379728    0.043243
2025-11-27 05:07:30.891990            i  61006.213552  23.100925    0.094929

Extracted lightcurve features for theorized lightcurve in 8.80s!
Engineering features...

Extracting features:  88%|█████████████████▌  | 196/223 [55:34<11:41, 25.97s/it]

Extracted feature row shape: (108, 84)
Fetching LSST 313871013678940198 from Antares...
Lightcurve fetched: 185 alerts, passbands: ['R' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:42:53.695422            R  61028.321455  23.207518    0.107786
2025-12-19 07:50:29.275315            R  61028.326728  23.157728    0.098003
2025-12-19 07:51:09.230541            R  61028.327190  23.251237    0.108884
2025-12-19 07:51:49.014062            R  61028.327651  23.299794    0.115205
2025-12-19 07:52:29.081591            R  61028.328114  23.307797    0.118165

Extracted lightcurve features for theorized lightcurve in 15.40s!
Engineering features...

Extracting features:  88%|█████████████████▋  | 197/223 [55:57<10:49, 25.00s/it]

Extracted feature row shape: (180, 84)
Fetching LSST 170028486051233796 from Antares...
Lightcurve fetched: 112 alerts, passbands: ['i' 'g' 'z' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 01:16:28.876779            i  61090.053112  20.734697    0.023219
2026-02-19 01:21:28.195616            i  61090.056576  20.711436    0.022372
2026-02-19 01:29:47.635928            g  61090.062357  22.416156    0.069849
2026-02-19 01:37:35.140233            g  61090.067768  22.562342    0.074956
2026-02-19 01:38:50.080395            g  61090.068635  22.407465    0.074598

Extracted lightcurve features for theorized lightcurve in 6.72s!
Engineering features...

Extracting features:  89%|█████████████████▊  | 198/223 [56:11<09:00, 21.63s/it]

Extracted feature row shape: (100, 84)
Fetching LSST 170046083740205236 from Antares...
Lightcurve fetched: 138 alerts, passbands: ['z' 'R' 'i' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-23 02:18:54.428898            z  61094.096463  21.611868    0.069447
2026-02-23 02:26:23.769896            z  61094.101664  21.561660    0.070266
2026-02-23 02:27:38.543902            z  61094.102529  21.752210    0.083617
2026-02-23 02:35:04.543040            R  61094.107691  21.473844    0.023874
2026-02-23 02:40:10.323983            R  61094.111231  21.461472    0.024952

Extracted lightcurve features for theorized lightcurve in 8.15s!
Engineering features...

Extracting features:  89%|█████████████████▊  | 199/223 [56:27<07:57, 19.89s/it]

Extracted feature row shape: (123, 84)
Fetching LSST 313893022983520325 from Antares...
Lightcurve fetched: 149 alerts, passbands: ['g' 'R' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-24 06:49:26.198131            g  61033.284331  23.517677    0.126578
2025-12-24 06:50:46.306671            g  61033.285258  23.562540    0.138158
2025-12-25 03:50:56.443275            g  61034.160376  23.868855    0.130990
2025-12-25 03:51:36.440503            g  61034.160838  23.455624    0.078116
2025-12-25 03:52:16.672706            g  61034.161304  23.508706    0.092323

Extracted lightcurve features for theorized lightcurve in 13.24s!
Engineering features...

Extracting features:  90%|█████████████████▉  | 200/223 [56:47<07:42, 20.10s/it]

Extracted feature row shape: (143, 84)
Fetching LSST 313998539799134474 from Antares...
Lightcurve fetched: 208 alerts, passbands: ['g' 'i' 'z' 'R']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-17 04:16:01.425723            g  61057.177794  24.026767    0.196088
2026-01-19 03:47:45.867983            g  61059.158170  23.416163    0.122224
2026-01-29 01:52:36.012492            g  61069.078195  20.194636    0.011330
2026-02-19 01:17:06.229662            i  61090.053544  20.685474    0.015829
2026-02-19 01:18:20.914365            i  61090.054409  20.693968    0.017718

Extracted lightcurve features for theorized lightcurve in 13.93s!
Engineering features...

Extracting features:  90%|██████████████████  | 201/223 [57:11<07:45, 21.15s/it]

Extracted feature row shape: (185, 84)
Fetching LSST 170019696475111620 from Antares...
Lightcurve fetched: 209 alerts, passbands: ['R' 'i' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 02:21:48.358651            R  61088.098476  23.378394    0.106864
2026-02-19 01:08:31.268724            i  61090.047584  23.088128    0.116486
2026-02-19 01:09:46.553006            i  61090.048455  23.071927    0.114836
2026-02-19 01:17:06.229662            i  61090.053544  22.968868    0.103250
2026-02-19 01:19:35.762826            i  61090.055275  23.136566    0.128552

Extracted lightcurve features for theorized lightcurve in 23.85s!
Engineering features...

Extracting features:  91%|██████████████████  | 202/223 [57:46<08:53, 25.42s/it]

Extracted feature row shape: (198, 84)
Fetching LSST 313690717350789543 from Antares...
Lightcurve fetched: 226 alerts, passbands: ['g' 'R' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-08 06:43:51.692585            g  60987.280459  23.275161    0.181307
2025-11-08 06:44:29.453808            g  60987.280896  23.315866    0.203543
2025-11-10 05:25:31.987434            g  60989.226065  23.862394    0.178342
2025-11-12 06:13:00.903024            g  60991.259038  23.594606    0.146557
2025-11-23 05:33:00.218019            R  61002.231253  23.813502    0.171835

Extracted lightcurve features for theorized lightcurve in 60.57s!
Engineering features...

Extracting features:  91%|██████████████████▏ | 203/223 [58:59<13:13, 39.69s/it]

Extracted feature row shape: (222, 84)
Fetching LSST 313690717562601492 from Antares...
Lightcurve fetched: 223 alerts, passbands: ['g' 'R' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-11-08 06:44:29.453808            g  60987.280896  23.181718    0.176204
2025-11-12 06:13:00.903024            g  60991.259038  23.216352    0.107431
2026-01-17 04:10:54.192879            g  61057.174238  23.472391    0.125290
2026-01-17 04:11:28.719354            g  61057.174638  23.416841    0.122690
2026-01-17 04:13:09.558674            g  61057.175805  23.337248    0.138701

Extracted lightcurve features for theorized lightcurve in 29.61s!
Engineering features...

Extracting features:  91%|██████████████████▎ | 204/223 [59:37<12:25, 39.21s/it]

Extracted feature row shape: (215, 84)
Fetching LSST 170028486213238822 from Antares...
Lightcurve fetched: 225 alerts, passbands: ['i' 'g' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-19 01:17:06.229662            i  61090.053544  23.388192    0.153206
2026-02-19 01:31:39.977169            g  61090.063657  23.803916    0.119985
2026-02-19 01:32:54.610331            g  61090.064521  23.668621    0.118859
2026-02-19 01:34:09.126608            g  61090.065383  23.863112    0.147786
2026-02-19 01:35:43.008794            g  61090.066470  23.839545    0.157841

Extracted lightcurve features for theorized lightcurve in 25.64s!
Engineering features...

Extracting features:  92%|████████████████▌ | 205/223 [1:00:11<11:15, 37.55s/it]

Extracted feature row shape: (211, 84)
Fetching LSST 313928194426667064 from Antares...
Lightcurve fetched: 176 alerts, passbands: ['i' 'g' 'R' 'z' 'y']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-01 05:21:45.886290            i  61041.223448  23.289617    0.224723
2026-01-01 05:28:12.647509            i  61041.227924  23.292521    0.213601
2026-01-01 05:28:55.415289            i  61041.228419  23.037675    0.151076
2026-01-09 07:33:39.514449            g  61049.315041  22.870895    0.146164
2026-01-09 07:34:13.958550            g  61049.315439  23.109627    0.171256

Extracted lightcurve features for theorized lightcurve in 12.86s!
Engineering features...

Extracting features:  92%|████████████████▋ | 206/223 [1:00:33<09:20, 32.97s/it]

Extracted feature row shape: (162, 84)
Fetching LSST 313888627043598349 from Antares...
Lightcurve fetched: 107 alerts, passbands: ['g' 'i' 'y' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-23 07:52:19.446435            g  61032.328003  24.077522    0.166430
2025-12-23 07:53:44.963625            g  61032.328993  23.798550    0.211117
2026-01-01 05:22:29.044211            i  61041.223947  22.420611    0.105402
2026-01-02 05:05:34.519543            i  61042.212205  22.259006    0.094381
2026-01-09 07:36:40.105703            g  61049.317131  22.444305    0.111861

Extracted lightcurve features for theorized lightcurve in 8.04s!
Engineering features...

Extracting features:  93%|████████████████▋ | 207/223 [1:00:49<07:27, 27.98s/it]

Extracted feature row shape: (88, 84)
Fetching LSST 170019716307877924 from Antares...
Lightcurve fetched: 6 alerts, passbands: ['R' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 05:05:15.017236            R  61088.211979  19.944672    0.006262
2026-02-17 05:05:55.134224            R  61088.212444  19.940035    0.006149
2026-02-19 05:29:15.854626            g  61090.228656  23.662196    0.165463
2026-02-20 04:31:33.501413            R  61091.188582  24.174478    0.223776
2026-02-23 04:05:13.388225            g  61094.170294  24.139906    0.180921

Extracted lightcurve features for theorized lightcurve in 0.18s!
Engineering features...

Extracting features:  93%|████████████████▊ | 208/223 [1:00:57<05:27, 21.85s/it]

Extracted feature row shape: (2, 84)
Fetching LSST 313871013403689120 from Antares...
Lightcurve fetched: 21 alerts, passbands: ['R' 'y' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:39:47.565349            R  61028.319301  24.009212    0.148890
2025-12-19 07:57:29.877230            R  61028.331596  24.389178    0.207451
2026-01-12 07:59:32.810402            y  61052.333019  22.437445    0.211168
2026-02-19 04:35:42.014991            g  61090.191459  24.284061    0.210348
2026-02-20 04:09:09.488143            g  61091.173026  24.387809    0.206077

Extracted lightcurve features for theorized lightcurve in 3.59s!
Engineering features...

Extracting features:  94%|████████████████▊ | 209/223 [1:01:11<04:32, 19.44s/it]

Extracted feature row shape: (17, 84)
Fetching LSST 313871013171953667 from Antares...
Lightcurve fetched: 194 alerts, passbands: ['R' 'u' 'g' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-19 07:38:21.792959            R  61028.318308  23.520752    0.112429
2025-12-19 07:39:47.565349            R  61028.319301  23.531869    0.106012
2025-12-19 07:46:38.413117            R  61028.324056  23.456903    0.102444
2025-12-19 07:47:21.443547            R  61028.324554  23.543710    0.111750
2025-12-19 07:48:04.714781            R  61028.325055  23.307028    0.093470

Extracted lightcurve features for theorized lightcurve in 24.36s!
Engineering features...

Extracting features:  94%|████████████████▉ | 210/223 [1:01:43<05:03, 23.33s/it]

Extracted feature row shape: (181, 84)
Fetching LSST 313893021742531388 from Antares...
Lightcurve fetched: 36 alerts, passbands: ['g' 'i' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-24 06:41:33.955920            g  61033.278865  24.345744    0.268979
2026-01-01 05:28:55.415289            i  61041.228419  22.783246    0.129072
2026-01-02 05:06:17.501874            i  61042.212703  22.493203    0.103794
2026-01-09 07:39:33.825898            i  61049.319142  22.778010    0.162618
2026-01-09 07:40:07.997948            i  61049.319537  22.675072    0.150382

Extracted lightcurve features for theorized lightcurve in 1.63s!
Engineering features...

Extracting features:  95%|█████████████████ | 211/223 [1:01:55<03:58, 19.91s/it]

Extracted feature row shape: (28, 84)
Fetching LSST 313853517574963301 from Antares...
Lightcurve fetched: 96 alerts, passbands: ['i' 'R' 'g' 'z' 'y']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:51.673674            i  61024.246431  23.088468    0.181967
2025-12-15 05:55:34.947172            i  61024.246932  23.174133    0.193934
2025-12-15 05:57:01.744653            i  61024.247937  22.955656    0.158720
2025-12-15 07:41:16.472056            i  61024.320330  23.063086    0.149924
2025-12-15 07:41:59.590165            i  61024.320829  23.133633    0.147029

Extracted lightcurve features for theorized lightcurve in 8.35s!
Engineering features...

Extracting features:  95%|█████████████████ | 212/223 [1:02:13<03:31, 19.20s/it]

Extracted feature row shape: (76, 84)
Fetching LSST 313853517419774035 from Antares...
Lightcurve fetched: 183 alerts, passbands: ['i' 'R' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:08.585837            i  61024.245933  21.338348    0.040313
2025-12-15 05:54:51.673674            i  61024.246431  21.359736    0.044039
2025-12-15 05:55:34.947172            i  61024.246932  21.347146    0.040361
2025-12-15 05:56:18.352569            i  61024.247435  21.503174    0.047805
2025-12-15 07:41:16.472056            i  61024.320330  21.323707    0.035094

Extracted lightcurve features for theorized lightcurve in 29.25s!
Engineering features...

Extracting features:  96%|█████████████████▏| 213/223 [1:02:51<04:08, 24.88s/it]

Extracted feature row shape: (166, 84)
Fetching LSST 313853517448085571 from Antares...
Lightcurve fetched: 153 alerts, passbands: ['i' 'R' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:08.585837            i  61024.245933  21.709214    0.048825
2025-12-15 05:54:51.673674            i  61024.246431  21.607639    0.045708
2025-12-15 05:55:34.947172            i  61024.246932  21.733276    0.053464
2025-12-15 05:56:18.352569            i  61024.247435  21.623395    0.048192
2025-12-15 07:41:16.472056            i  61024.320330  21.729039    0.043179

Extracted lightcurve features for theorized lightcurve in 16.83s!
Engineering features...

Extracting features:  96%|█████████████████▎| 214/223 [1:03:15<03:42, 24.75s/it]

Extracted feature row shape: (132, 84)
Fetching LSST 313853533265854510 from Antares...
Lightcurve fetched: 174 alerts, passbands: ['i' 'R' 'g' 'z' 'y']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 07:42:42.760641            i  61024.321328  23.505024    0.212445
2025-12-15 07:44:08.906733            i  61024.322325  23.558124    0.221074
2025-12-15 07:44:52.352766            i  61024.322828  23.616363    0.219176
2025-12-17 05:09:07.111363            i  61026.214666  23.307451    0.183502
2025-12-19 07:38:21.792959            R  61028.318308  23.164196    0.068454

Extracted lightcurve features for theorized lightcurve in 13.32s!
Engineering features...

Extracting features:  96%|█████████████████▎| 215/223 [1:03:37<03:11, 23.96s/it]

Extracted feature row shape: (162, 84)
Fetching LSST 313853517404569719 from Antares...
Lightcurve fetched: 187 alerts, passbands: ['i' 'R' 'g' 'z' 'y']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:08.585837            i  61024.245933  22.180771    0.078719
2025-12-15 05:54:51.673674            i  61024.246431  22.185722    0.076485
2025-12-15 05:56:18.352569            i  61024.247435  22.144159    0.078047
2025-12-15 05:57:01.744653            i  61024.247937  22.186983    0.080872
2025-12-15 07:41:16.472056            i  61024.320330  22.041684    0.060107

Extracted lightcurve features for theorized lightcurve in 12.73s!
Engineering features...

Extracting features:  97%|█████████████████▍| 216/223 [1:03:59<02:42, 23.16s/it]

Extracted feature row shape: (167, 84)
Fetching LSST 313853517424492644 from Antares...
Lightcurve fetched: 98 alerts, passbands: ['i' 'R' 'g' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:08.585837            i  61024.245933  22.204706    0.074512
2025-12-15 05:54:51.673674            i  61024.246431  22.262766    0.085114
2025-12-15 05:55:34.947172            i  61024.246932  22.162424    0.075900
2025-12-15 05:57:01.744653            i  61024.247937  21.977878    0.062650
2025-12-15 07:41:16.472056            i  61024.320330  22.183984    0.064032

Extracted lightcurve features for theorized lightcurve in 6.45s!
Engineering features...

Extracting features:  97%|█████████████████▌| 217/223 [1:04:13<02:03, 20.59s/it]

Extracted feature row shape: (77, 84)
Fetching LSST 313932595758366765 from Antares...
Lightcurve fetched: 225 alerts, passbands: ['i' 'g' 'R' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-02 05:05:34.519543            i  61042.212205  23.127682    0.187348
2026-01-09 07:34:13.958550            g  61049.315439  22.742233    0.143993
2026-01-09 07:34:48.208962            g  61049.315836  22.637340    0.125500
2026-01-09 07:35:22.674095            g  61049.316235  22.706759    0.132424
2026-01-09 07:35:57.232945            g  61049.316635  23.197346    0.209480

Extracted lightcurve features for theorized lightcurve in 22.06s!
Engineering features...

Extracting features:  98%|█████████████████▌| 218/223 [1:04:43<01:56, 23.38s/it]

Extracted feature row shape: (214, 84)
Fetching LSST 313967766160277548 from Antares...
Lightcurve fetched: 959 alerts, passbands: ['g' 'R' 'u' 'i' 'z']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-23 07:52:19.446435            g  61032.328003  23.837905    0.132490
2025-12-23 07:53:02.077728            g  61032.328496  24.041599    0.161234
2026-01-10 04:04:05.818315            R  61050.169512  23.366827    0.198512
2026-01-11 04:30:39.499836            g  61051.187957  23.234654    0.101874
2026-01-11 04:31:13.636536            g  61051.188352  23.574859    0.148376

Extracted lightcurve features for theorized lightcurve in 195.80s!
Engineering features...

Extracting features:  98%|█████████████████▋| 219/223 [1:08:11<05:14, 78.61s/it]

Extracted feature row shape: (955, 84)
Fetching LSST 313853517494747320 from Antares...
Lightcurve fetched: 126 alerts, passbands: ['i' 'R' 'u' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2025-12-15 05:54:08.585837            i  61024.245933  22.361869    0.094763
2025-12-15 05:56:18.352569            i  61024.247435  22.488296    0.113021
2025-12-15 05:57:01.744653            i  61024.247937  22.495452    0.120361
2025-12-15 07:41:16.472056            i  61024.320330  22.447682    0.097376
2025-12-15 07:43:26.127448            i  61024.321830  22.487876    0.090638

Extracted lightcurve features for theorized lightcurve in 8.68s!
Engineering features...

Extracting features:  99%|█████████████████▊| 220/223 [1:08:26<02:59, 59.75s/it]

Extracted feature row shape: (113, 84)
Fetching LSST 314003013998478333 from Antares...
Lightcurve fetched: 193 alerts, passbands: ['R' 'z' 'i' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-01-18 07:10:45.906332            R  61058.299142  24.035746    0.166036
2026-01-18 07:11:20.033730            R  61058.299537  24.130047    0.196203
2026-01-20 06:59:45.419441            R  61060.291498  23.815973    0.152135
2026-01-20 07:00:19.665525            R  61060.291894  23.576546    0.127381
2026-01-20 07:02:05.137946            R  61060.293115  23.732430    0.147458

Extracted lightcurve features for theorized lightcurve in 14.85s!
Engineering features...

Extracting features:  99%|█████████████████▊| 221/223 [1:08:49<01:37, 48.52s/it]

Extracted feature row shape: (181, 84)
Fetching LSST 170019716456251517 from Antares...
Lightcurve fetched: 249 alerts, passbands: ['R' 'i' 'g']

                           ant_passband       ant_mjd    ant_mag  ant_magerr
time
2026-02-17 05:05:55.134224            R  61088.212444  23.995061    0.159871
2026-02-19 05:00:15.828136            R  61090.208517  23.487645    0.152108
2026-02-19 05:01:35.918524            R  61090.209444  23.457135    0.126767
2026-02-19 05:05:37.614292            R  61090.212241  23.823461    0.188261
2026-02-19 05:11:49.786270            i  61090.216548  23.493239    0.196225

Extracted lightcurve features for theorized lightcurve in 21.61s!
Engineering features...

Extracting features: 100%|██████████████████| 223/223 [1:09:18<00:00, 18.65s/it]

Extracted feature row shape: (242, 84)
Fetching LSST ZTF25acchxhv from Antares...
FAILED: ZTF25acchxhv — Object ZTF25acchxhv not found in Antares

Done. Extracted: 17899 / 223
Failed: 2
Failed IDs saved to lsst_failed.csv

In [ ]:
### df_all = pd.read_csv("lsst_extracted_features.csv")
print(f"Rows in CSV: {len(df_all)}")
print(f"Unique objects: {df_all['lsst_dia_object_id'].nunique()}")

In [52]:
df_all = pd.read_csv("lsst_extracted_features.csv")
df_all = df_all.drop_duplicates(subset="lsst_dia_object_id")
df_all.to_csv("lsst_extracted_features.csv", index=False)
print(f"Cleaned CSV: {len(df_all)} rows, {df_all['lsst_dia_object_id'].nunique()} unique objects")

Cleaned CSV: 221 rows, 221 unique objects