# DiMMAD anomaly scoring on ZTF/RELAISS features

1. Loads a RELAISS feature table (with durations + sky coords)
2. Applies basic quality cuts (duration, Galactic latitude)
3. Cross-matches to ALeRCE explorer export to get class labels
4. Trains DiMMAD (distclassipy DistanceAnomaly) on *known* classes
5. Scores an unlabeled/unknown set and ranks anomalies

In [1]:
# --- Imports & settings ---
import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

from astropy.coordinates import SkyCoord
import astropy.units as u

from distclassipy.anomaly import DistanceAnomaly

import matplotlib.pyplot as plt

from relaiss import constants
import relaiss as rl

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

pd.set_option("display.max_columns", 200)

In [2]:
# --- Paths ---
DATA_DIR = Path("data")          
OUT_DIR  = Path("outputs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

RELAISS_CSV = DATA_DIR / "reference_20k_with_durations.csv"
ALERCE_EXPLORER_CSV = DATA_DIR / "btsztf.csv"
#ALERCE_EXPLORER_CSV = Path("experiments") / "explorer.csv"  

RELAISS_CSV, ALERCE_EXPLORER_CSV

(PosixPath('data/reference_20k_with_durations.csv'),
 PosixPath('data/btsztf.csv'))

## Load data

In [5]:
df = pd.read_csv(RELAISS_CSV, low_memory=False)
df.head()

,t0,g_peak_mag,g_peak_time,g_rise_time,g_decline_time,g_duration_above_half_flux,g_amplitude,g_skewness,g_beyond_2sigma,r_peak_mag,r_peak_time,r_rise_time,r_decline_time,r_duration_above_half_flux,r_amplitude,r_skewness,r_beyond_2sigma,mean_g-r,g-r_at_g_peak,mean_color_rate,g_n_peaks,g_dt_main_to_secondary_peak,g_dmag_secondary_peak,g_secondary_peak_prominence,g_secondary_peak_width,r_n_peaks,r_dt_main_to_secondary_peak,r_dmag_secondary_peak,r_secondary_peak_prominence,r_secondary_peak_width,g_max_rolling_variance,g_mean_rolling_variance,r_max_rolling_variance,r_mean_rolling_variance,g_rise_local_curvature,g_decline_local_curvature,r_rise_local_curvature,r_decline_local_curvature,features_valid,t0_err,g_peak_mag_err,g_peak_time_err,g_rise_time_err,g_decline_time_err,g_duration_above_half_flux_err,g_amplitude_err,g_skewness_err,g_beyond_2sigma_err,r_peak_mag_err,r_peak_time_err,r_rise_time_err,r_decline_time_err,r_duration_above_half_flux_err,r_amplitude_err,r_skewness_err,r_beyond_2sigma_err,mean_g-r_err,g-r_at_g_peak_err,mean_color_rate_err,g_n_peaks_err,g_dt_main_to_secondary_peak_err,g_dmag_secondary_peak_err,g_secondary_peak_prominence_err,g_secondary_peak_width_err,r_n_peaks_err,r_dt_main_to_secondary_peak_err,r_dmag_secondary_peak_err,r_secondary_peak_prominence_err,r_secondary_peak_width_err,g_max_rolling_variance_err,g_mean_rolling_variance_err,r_max_rolling_variance_err,r_mean_rolling_variance_err,g_rise_local_curvature_err,g_decline_local_curvature_err,r_rise_local_curvature_err,r_decline_local_curvature_err,features_valid_err,ZTFID,ra,dec,Unnamed: 0,idx,best_cat,best_cat_release,query_time,smallcone_posterior,missedcat_posterior,extra_cat_cols,host_objID,host_name,host_total_posterior,host_ra,host_dec,host_redshift_mean,host_redshift_std,host_absmag_mean,host_absmag_std,host_absmag_info,host_offset_mean,...,rExtNSigma,iKronRad,yExtNSigma,ymomentYY,ny,zstackDetectID,gEpoch,iFPSFFlux,nStackDetections,KronMag,ypsfLikelihood,iinfoFlag,zFPSFFlux,zpsfCore,momentXY,ypsfMinorFWHM,zPSFMag,yraErr,iFApFlux,zPSFMagErr,iPSFFluxErr,rinfoFlag,ipsfMinorFWHM,inFrames,gpsfMinorFWHM,gmomentXX,iKronFluxErr,ng,rpsfCore,raStack,zFKronFlux,uniquePspsSTid,objAltName1,iPSFMag,zApRadius,decStackErr,gmomentR1,yApFluxErr,zinfoFlag,rmomentR1,gzp,iKronFlux,randomID,surveyID,cx,imomentRH,ydec,gyPosErr,rra,rKronRad,zpsfMinorFWHM,yApFillFac,yKronMag,uniquePspsOBid,rpsfTheta,zApMagErr,iippDetectID,iinfoFlag2,ystackDetectID,batchID,rFmeanflxR5,zFmeanflxR7,iEpoch,zxPosErr,rpsfLikelihood,yPSFFlux,yEpoch,rKronMag,gdecErr,zmomentXX,yinfoFlag,zpsfChiSq,zexpTime,zKronMagErr,rKronFluxErr,gKronFluxErr,gKronFlux,rFApFlux,gPSFFlux,gKronMag,iraErr,gstackImageID,yFmeanflxR6,graErr,ipsfQf,iFmeanflxR5,zExtNSigma,ypsfCore,zFmeanflxR6,iFmeanflxR6,mjd_extracted,tns_redshift,latest_magnitude,oldest_alert,newest_alert,peak_phase,antares_oldest_alert,antares_newest_alert,antares_duration,duration_days
0,59850.515694,18.058201,19.991794,6.032847,12.011400,18.044248,0.521299,0.225308,0.0,17.598600,0.000000,NaN,33.467286,31.981111,1.021000,-0.492451,0.083333,0.109230,0.027208,0.016575,1,NaN,NaN,NaN,NaN,2,12.119703,0.211326,0.249921,20.899493,0.000295,0.000144,0.071492,0.001672,-0.007540,-0.002478,NaN,-0.005436,False,0.0,0.058249,0.903369,0.903369,0.903369,0.000000,0.074867,0.576231,6.117006e-02,0.170234,0.000000,NaN,16.194011,4.325329,0.154256,0.477562,0.045843,0.051900,0.119613,0.008798,0.615587,4.181948,0.153224,0.045004,13.055632,0.638666,3.519174,0.126541,0.123748,7.833686,0.000581,0.000123,0.054051,0.000855,0.021606,0.012067,NaN,0.006085,0.0,ZTF17aabtvsy,158.883762,37.649729,5.0,19226.0,panstarrs,dr2,6.246375,1.341795e-15,1.341795e-15,"{'iinfoFlag3': 196608.0, 'zpsfQfPerfect': 0.99...",1.531816e+17,NaN,0.987186,158.883575,37.649555,0.077098,0.019274,-22.734511,0.749100,r,0.829189,...,13.785300,17.996799,23.644100,0.228099,13.0,2.523244e+18,55923.256190,0.000530,5.0,14.982000,0.000000,262160391.0,0.000617,0.425564,-0.002408,0.943950,16.888700,0.001657,0.001063,0.001878,6.914810e-07,262160391.0,0.927463,16.0,1.17831,0.319913,4.597210e-06,12.0,0.522189,158.883637,0.004043,3.738386e+15,NaN,17.254601,2.25000,0.001,4.69666,1.093620e-06,262160391.0,6.856200,24.950701,0.003692,0.744533,0.0,-0.738595,0.970184,37.649583,0.006502,158.883628,17.140499,1.008880,0.859437,14.688800,3.600872e+15,55.072300,0.000677,1959.0,524416.0,2.523243e+18,3600872.0,0.000764,0.002693,56536.031130,0.003129,0.000000,0.000776,56204.427467,15.409000,0.001625,0.203681,262160391.0,10.139900,722.0,0.001885,4.149480e-06,0.000003,0.000986,0.000905,1.875150e-04,16.4149,0.000597,4567628.0,0.002399,0.001737,0.997530,0.001177,19.938200,0.664856,0.001948,0.001616,60796.710596,NaN,NaN,NaN,NaN,NaN,59850.515694,59901.530729,51.015035,51.015035
1,60596.327662,16.803886,9.917465,8.474729,14.790803,16.114167,3.273268,0.270541,0.0,17.555490,34.969363,NaN,13.471450,2.982419,1.341433,-0.426584,0.000000,0.908953,-0.751604,-0.005580,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.056652,0.005948,0.000541,0.000441,0.022751,0.006562,NaN,NaN,False,0.0,0.037687,1.645437,1.707257,1.600286,3.683273,0.170410,0.046208,0.000000e+00,0.040870,0.000000,NaN,1.917810,0.000000,0.083318,0.056074,0.000000,0.121456,0.050861,0.007787,0.552506,6.309628,0.220410,0.117434,9.974748,0.223607,NaN,NaN,NaN,NaN,0.012854,0.001026,0.001621,0.000134,0.008264,0.008680,NaN,NaN,0.0,ZTF17aabvong,31.282032,11.248651,6.0,8996.0,panstarrs,dr2,6.524667,1.132243e-15,1.132243e-15,"{'iPSFFlux': 0.0002382450038567, 'projectionID...",1.214903e+17,NaN,1.000000,31.282127,11.248569,0.025181,0.007587,-20.618437,0.729355,r,0.454126,...,38.124699,17.693001,38.024601,0.216703,8.0,2.523095e+18,55943.572730,0.000237,5.0,14.587100,0.000000,262160391.0,0.000326,0.750460,0.002253,0.844023,17.735600,0.004179,0.000697,0.004494,6.202390e-07,262160391.0,0.983609,14.0,1.15710,0.360280,5.837870e-06,14.0,0.437406,31.282053,0.006039,3.673351e+15,NaN,17.957399,2.25000,0.001,6.43585,8.365690e-07,262160391.0,6.900980,24.995100,0.005311,0.046059,0.0,0.838204,1.092810,11.248618,0.007672,31.282053,17.252501,0.871072,0.864545,14.171600,3.501513e+15,-9.446360,0.000970,6290.0,1572992.0,2.523108e+18,3501513.0,0.000645,0.003231,56294.406587,0.006940,0.000000,0.000324,55941.203492,14.951000,0.001918,0.233626,262160391.0,169.826996,540.0,0.001870,5.242890e-06,0.000003,0.001872,0.000632,1.135010e-04,15.7191,0.001144,4030072.0,0.002548,0.002127,0.997932,0.000839,35.214901,0.595606,0.001940,0.001579,60796.710596,NaN,NaN,NaN,NaN,NaN,60596.327662,60663.246713,66.919051,66.919051
2,59861.468773,18.025000,0.000000,NaN,1.246246,5.971481,1.945101,0.815205,0.1,18.274099,0.021192,NaN,1.415106,9.945428,1.760750,0.595434,0.090909,-0.098382,-0.249100,0.013544,1,NaN,NaN,NaN,NaN,2,5.954756,0.602849,0.198726,31.826992,0.014541,0.004381,0.019289,0.004223,NaN,0.076705,NaN,0.087738,False,0.0,0.042273,0.000000,NaN,0.240076,1.968606,0.103605,0.153046,1.423831e-17,0.051127,1.643622,0.000000,1.198672,1.987739,0.178663,0.222787,0.020328,0.044112,0.063622,0.014004,0.489360,1.540522,0.171408,0.075891,7.011332,0.695852,1.965831,0.294856,0.083630,10.050958,0.005109,0.001060,0.010062,0.000792,NaN,0.070404,0.089636,0.111978,0.0,ZTF17aaaycpc,105.863596,32.068390,2.0,10296.0,panstarrs,dr2,8.549133,7.403929e-15,7.403929e-15,"{'raStackErr': 0.0010000000474974, 'cz': 0.530...",1.464811e+17,NaN,0.998975,105.864122,32.068686,0.516699,0.259615,-20.990470,1.067820,r,1.929947,...,-0.594730,1.762880,0.691058,0.117420,0.0,2.523214e+18,56301.695611,0.000011,4.0,21.356400,0.489529,35651585.0,0.000019,0.726127,-0.014049,0.818664,20.723400,0.037106,0.000009,0.055614,7.877810e-07,35651585.0,1.039530,4.0,1.47531,NaN,9.757030e-07,0.0,0.229726,105.864119,0.000017,3.792412e+15,NaN,21.314301,2.50000,0.001,NaN,1.076550e-07,35651585.0,0.858702,24.983700,0.000006,0.006697,0.0,-0.231646,0.790146,32.068698,1.198120,105.864122,2.146750,0.993778,0.868475,20.723101,3.554956e+15,-62.186501,0.005556,6409.0,0.0,2.523191e+18,3554956.0,0.000002,-0.000017,56363.257702,0.095893,-0.552024,0.000019,56073.729985,22.842699,0.299529,0.167133,35651585.0,1.069600,660.0,0.083105,3.242540e-07,NaN,NaN,0.000002,7.793350e-07,NaN,0.032768,4341886.0,0.000043,0.325730,0.998050,0.000004,0.103803,0.943772,0.000014,-0.000006,60796.710596,NaN,NaN,NaN,NaN,NaN,59861.468773,59874.486111,13.017338,13.017338
3,60168.430151,19.891600,16.017986,16.017986,NaN,16.017986,0.332001,0.738549,0.0,19.139200,14.040162,12.144228,13.450842,24.071412,1.046000,-0.510378,0.000000,0.557520,0.638637,0.037503,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.000232,0.000045,0.008214,0.001308,0.001968,NaN,0.008372,0.000673,False,0.0,0.133814,6.690610,3.329197,6.939874,0.983905,0.224879,0.564882,0.000000e+00,0.087849,1.218998,1.783097,5.738995,8.249798,0.146477,0.250046,0.037308,0.162770,0.517105,0.029405,0.444262,NaN,NaN,NaN,NaN,0.606977,2.711063,0.164649,0.095495,10.651462,0.001247,0.000232,0.015369,0.001136,0.008206,0.005486,0.027864,0.005755,0.0,ZTF17aaahhwn,69.419513,15.476838,1.0,4629.0,panstarrs,dr2,8.731575,5.265903e-15,5.265903e-15,"{'rpsfQfPerfect': 0.997987985610962, 'zinfoFla...",1.265707e+17,NaN,0.999887,69.419055,15.475506,0.061477,0.038571,-19.657119,0.877200,r,5.052795,...,27.889400,8.609510,32.283100,0.204750,8.0,2.523177e+18,56029.758091,0.000052,5.0,17.544001,0.000000,262160391.0,0.000046,0.536181,-0.002680,0.844265,19.620600,0.011020,0.000150,0.017615,4.890330e-07,262160391.0,1.064300,16.0,1.20624,0.358607,2.709190e-06,8.0,0.524166,69.419043,0.000424,3.737647e+15,NaN,19.704500,1.99999,0.001,2.63877,3.794600e-07,262160391.0,3.525280,25.000700,0.000349,0.327321,0.0,0.338785,1.176730,15.475460,0.051028,69.419023,8.813210,0.844592,0.845511,17.066799,3.527800e+15,-69.611900,0.002509,2966.0,1572992.0,2.523173e+18,3527800.0,0.000085,0.000419,56290.682505,0.026276,0.000000,0.000076,55907.662621,18.117399,0.012757,0.181665,262160391.0,6.803540,480.0,0.011566,2.178080e-06,0.000001,0.000082,0.000076,1.341610e-05,19.1180,0.004853,4334244.0,0.000394,0.013486,0.997816,0.000144,33.136902,0.652382,0.000310,0.000227,60796.710596,NaN,NaN,NaN,NaN,NaN,60168.430151,60208.496088,40.065937,40.065937
4,59163.441424,NaN,NaN,NaN,NaN,NaN,0.089211,-0.370045,0.0,NaN,NaN,NaN,NaN,NaN,0.134977,-0.670378,0.000000,0.499700,0.374033,-0.013112,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.000021,0.000008,0.000038,0.000015,-0.004096,NaN,NaN,NaN,False,0.0,0.124332,2.966214,2.169821,2.061728,0.472477,0.145045,0.501863,0.000000e+00,0.108621,2.729212,2.572773,0.982429,0.000000,0.090754,0.475010,0.000000,0.133191,0.186942,0.043897,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000178,0.000078,0.000102,0.000032,0.038685,0.041126,0.025475,0.002856,0.0,ZTF17aaazjab,117.810147,34.412364,3.0,15712.0,panstarrs,dr2,6.325459,1.979225e-15,1.979225e-15,"{'rnFrames': 15.0, 'ypsfMajorFWHM': 0.91689997...",1.492912e+17,NaN,0.930639,117.810329,34.412576,0.076348,0.019087,-21.537358,0.807840,r,0.940699,...,14.266700,4.933910,15.869800,0.198206,14.0,2.523198e+18,56286.473447,0.000674,10.0,16.156799,0.000000,262160391.0,0.000632,0.289077,-0.013810,0.884926,17.052099,0.001629,0.001112,0.002535,6.645630e-07,262160391.0,1.090340,29.0,1.06956,0.278656,1.323810e-06,15.0,0.392236,117.810362,0.001259,3.633557e+15,NaN,16.871000,2.50001,0.001,1.89873,8.144340e-07,262160391.0,2.272060,25.008600,0.001348,0.401881,0.0,-0.384896,0.973595,34.412566,0.003250,117.810337,5.680150,1.042310,0.872169,15.933900,3.563442e+15,-86.350700,0.000795,2817.0,524416.0,2.523214e+18,3563442.0,0.000758,0.001335,56593.472794,0.004418,0.000000,0.000663,56032.055520,16.447500,0.000813,0.231648,262160391.0,43.972599,630.0,0.002720,1.450220e-06,0.000001,0.000783,0.000754,4.369490e-04,16.6660,0.000465,4395353.0,0.001485,0.000878,0.997580,0.001095,18.360800,1.024430,0.001202,0.001288,60796.710596,NaN,NaN,NaN,NaN,NaN,59163.441424,59170.444711,7.003287,7.003287

## Basic cuts
- remove long-duration objects (duration_days > 200)
- avoid Galactic plane (|b| < 15°)

In [7]:
DURATION_MAX_DAYS = 200
LAT_CUT_DEG = 15.0

coords = SkyCoord(ra=df["ra"].values * u.deg, dec=df["dec"].values * u.deg, frame="icrs")
b = coords.galactic.b.deg

mask = (df["duration_days"] <= DURATION_MAX_DAYS) & (np.abs(b) >= LAT_CUT_DEG)
df_cut = df.loc[mask].copy()

print(f"Kept {len(df_cut):,} / {len(df):,} rows")
df_cut[["ra","dec","duration_days"]].describe()

df_cut.head()

Kept 17,254 / 25,515 rows

,t0,g_peak_mag,g_peak_time,g_rise_time,g_decline_time,g_duration_above_half_flux,g_amplitude,g_skewness,g_beyond_2sigma,r_peak_mag,r_peak_time,r_rise_time,r_decline_time,r_duration_above_half_flux,r_amplitude,r_skewness,r_beyond_2sigma,mean_g-r,g-r_at_g_peak,mean_color_rate,g_n_peaks,g_dt_main_to_secondary_peak,g_dmag_secondary_peak,g_secondary_peak_prominence,g_secondary_peak_width,r_n_peaks,r_dt_main_to_secondary_peak,r_dmag_secondary_peak,r_secondary_peak_prominence,r_secondary_peak_width,g_max_rolling_variance,g_mean_rolling_variance,r_max_rolling_variance,r_mean_rolling_variance,g_rise_local_curvature,g_decline_local_curvature,r_rise_local_curvature,r_decline_local_curvature,features_valid,t0_err,g_peak_mag_err,g_peak_time_err,g_rise_time_err,g_decline_time_err,g_duration_above_half_flux_err,g_amplitude_err,g_skewness_err,g_beyond_2sigma_err,r_peak_mag_err,r_peak_time_err,r_rise_time_err,r_decline_time_err,r_duration_above_half_flux_err,r_amplitude_err,r_skewness_err,r_beyond_2sigma_err,mean_g-r_err,g-r_at_g_peak_err,mean_color_rate_err,g_n_peaks_err,g_dt_main_to_secondary_peak_err,g_dmag_secondary_peak_err,g_secondary_peak_prominence_err,g_secondary_peak_width_err,r_n_peaks_err,r_dt_main_to_secondary_peak_err,r_dmag_secondary_peak_err,r_secondary_peak_prominence_err,r_secondary_peak_width_err,g_max_rolling_variance_err,g_mean_rolling_variance_err,r_max_rolling_variance_err,r_mean_rolling_variance_err,g_rise_local_curvature_err,g_decline_local_curvature_err,r_rise_local_curvature_err,r_decline_local_curvature_err,features_valid_err,ZTFID,ra,dec,Unnamed: 0,idx,best_cat,best_cat_release,query_time,smallcone_posterior,missedcat_posterior,extra_cat_cols,host_objID,host_name,host_total_posterior,host_ra,host_dec,host_redshift_mean,host_redshift_std,host_absmag_mean,host_absmag_std,host_absmag_info,host_offset_mean,...,rExtNSigma,iKronRad,yExtNSigma,ymomentYY,ny,zstackDetectID,gEpoch,iFPSFFlux,nStackDetections,KronMag,ypsfLikelihood,iinfoFlag,zFPSFFlux,zpsfCore,momentXY,ypsfMinorFWHM,zPSFMag,yraErr,iFApFlux,zPSFMagErr,iPSFFluxErr,rinfoFlag,ipsfMinorFWHM,inFrames,gpsfMinorFWHM,gmomentXX,iKronFluxErr,ng,rpsfCore,raStack,zFKronFlux,uniquePspsSTid,objAltName1,iPSFMag,zApRadius,decStackErr,gmomentR1,yApFluxErr,zinfoFlag,rmomentR1,gzp,iKronFlux,randomID,surveyID,cx,imomentRH,ydec,gyPosErr,rra,rKronRad,zpsfMinorFWHM,yApFillFac,yKronMag,uniquePspsOBid,rpsfTheta,zApMagErr,iippDetectID,iinfoFlag2,ystackDetectID,batchID,rFmeanflxR5,zFmeanflxR7,iEpoch,zxPosErr,rpsfLikelihood,yPSFFlux,yEpoch,rKronMag,gdecErr,zmomentXX,yinfoFlag,zpsfChiSq,zexpTime,zKronMagErr,rKronFluxErr,gKronFluxErr,gKronFlux,rFApFlux,gPSFFlux,gKronMag,iraErr,gstackImageID,yFmeanflxR6,graErr,ipsfQf,iFmeanflxR5,zExtNSigma,ypsfCore,zFmeanflxR6,iFmeanflxR6,mjd_extracted,tns_redshift,latest_magnitude,oldest_alert,newest_alert,peak_phase,antares_oldest_alert,antares_newest_alert,antares_duration,duration_days
0,59850.515694,18.058201,19.991794,6.032847,12.011400,18.044248,0.521299,0.225308,0.0,17.598600,0.000000,NaN,33.467286,31.981111,1.021000,-0.492451,0.083333,0.109230,0.027208,0.016575,1,NaN,NaN,NaN,NaN,2,12.119703,0.211326,0.249921,20.899493,0.000295,0.000144,0.071492,0.001672,-0.007540,-0.002478,NaN,-0.005436,False,0.0,0.058249,0.903369,0.903369,0.903369,0.000000,0.074867,0.576231,6.117006e-02,0.170234,0.000000,NaN,16.194011,4.325329,0.154256,0.477562,0.045843,0.051900,0.119613,0.008798,0.615587,4.181948,0.153224,0.045004,13.055632,0.638666,3.519174,0.126541,0.123748,7.833686,0.000581,0.000123,0.054051,0.000855,0.021606,0.012067,NaN,0.006085,0.0,ZTF17aabtvsy,158.883762,37.649729,5.0,19226.0,panstarrs,dr2,6.246375,1.341795e-15,1.341795e-15,"{'iinfoFlag3': 196608.0, 'zpsfQfPerfect': 0.99...",1.531816e+17,NaN,0.987186,158.883575,37.649555,0.077098,0.019274,-22.734511,0.749100,r,0.829189,...,13.785300,17.996799,23.644100,0.228099,13.0,2.523244e+18,55923.256190,0.000530,5.0,14.982000,0.000000,262160391.0,0.000617,0.425564,-0.002408,0.943950,16.888700,0.001657,0.001063,0.001878,6.914810e-07,262160391.0,0.927463,16.0,1.17831,0.319913,4.597210e-06,12.0,0.522189,158.883637,0.004043,3.738386e+15,NaN,17.254601,2.25000,0.001,4.69666,1.093620e-06,262160391.0,6.856200,24.950701,0.003692,0.744533,0.0,-0.738595,0.970184,37.649583,0.006502,158.883628,17.140499,1.008880,0.859437,14.688800,3.600872e+15,55.072300,0.000677,1959.0,524416.0,2.523243e+18,3600872.0,0.000764,0.002693,56536.031130,0.003129,0.000000,0.000776,56204.427467,15.409000,0.001625,0.203681,262160391.0,10.139900,722.0,0.001885,4.149480e-06,0.000003,0.000986,0.000905,1.875150e-04,16.4149,0.000597,4567628.0,0.002399,0.001737,0.997530,0.001177,19.938200,0.664856,0.001948,0.001616,60796.710596,NaN,NaN,NaN,NaN,NaN,59850.515694,59901.530729,51.015035,51.015035
1,60596.327662,16.803886,9.917465,8.474729,14.790803,16.114167,3.273268,0.270541,0.0,17.555490,34.969363,NaN,13.471450,2.982419,1.341433,-0.426584,0.000000,0.908953,-0.751604,-0.005580,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.056652,0.005948,0.000541,0.000441,0.022751,0.006562,NaN,NaN,False,0.0,0.037687,1.645437,1.707257,1.600286,3.683273,0.170410,0.046208,0.000000e+00,0.040870,0.000000,NaN,1.917810,0.000000,0.083318,0.056074,0.000000,0.121456,0.050861,0.007787,0.552506,6.309628,0.220410,0.117434,9.974748,0.223607,NaN,NaN,NaN,NaN,0.012854,0.001026,0.001621,0.000134,0.008264,0.008680,NaN,NaN,0.0,ZTF17aabvong,31.282032,11.248651,6.0,8996.0,panstarrs,dr2,6.524667,1.132243e-15,1.132243e-15,"{'iPSFFlux': 0.0002382450038567, 'projectionID...",1.214903e+17,NaN,1.000000,31.282127,11.248569,0.025181,0.007587,-20.618437,0.729355,r,0.454126,...,38.124699,17.693001,38.024601,0.216703,8.0,2.523095e+18,55943.572730,0.000237,5.0,14.587100,0.000000,262160391.0,0.000326,0.750460,0.002253,0.844023,17.735600,0.004179,0.000697,0.004494,6.202390e-07,262160391.0,0.983609,14.0,1.15710,0.360280,5.837870e-06,14.0,0.437406,31.282053,0.006039,3.673351e+15,NaN,17.957399,2.25000,0.001,6.43585,8.365690e-07,262160391.0,6.900980,24.995100,0.005311,0.046059,0.0,0.838204,1.092810,11.248618,0.007672,31.282053,17.252501,0.871072,0.864545,14.171600,3.501513e+15,-9.446360,0.000970,6290.0,1572992.0,2.523108e+18,3501513.0,0.000645,0.003231,56294.406587,0.006940,0.000000,0.000324,55941.203492,14.951000,0.001918,0.233626,262160391.0,169.826996,540.0,0.001870,5.242890e-06,0.000003,0.001872,0.000632,1.135010e-04,15.7191,0.001144,4030072.0,0.002548,0.002127,0.997932,0.000839,35.214901,0.595606,0.001940,0.001579,60796.710596,NaN,NaN,NaN,NaN,NaN,60596.327662,60663.246713,66.919051,66.919051
2,59861.468773,18.025000,0.000000,NaN,1.246246,5.971481,1.945101,0.815205,0.1,18.274099,0.021192,NaN,1.415106,9.945428,1.760750,0.595434,0.090909,-0.098382,-0.249100,0.013544,1,NaN,NaN,NaN,NaN,2,5.954756,0.602849,0.198726,31.826992,0.014541,0.004381,0.019289,0.004223,NaN,0.076705,NaN,0.087738,False,0.0,0.042273,0.000000,NaN,0.240076,1.968606,0.103605,0.153046,1.423831e-17,0.051127,1.643622,0.000000,1.198672,1.987739,0.178663,0.222787,0.020328,0.044112,0.063622,0.014004,0.489360,1.540522,0.171408,0.075891,7.011332,0.695852,1.965831,0.294856,0.083630,10.050958,0.005109,0.001060,0.010062,0.000792,NaN,0.070404,0.089636,0.111978,0.0,ZTF17aaaycpc,105.863596,32.068390,2.0,10296.0,panstarrs,dr2,8.549133,7.403929e-15,7.403929e-15,"{'raStackErr': 0.0010000000474974, 'cz': 0.530...",1.464811e+17,NaN,0.998975,105.864122,32.068686,0.516699,0.259615,-20.990470,1.067820,r,1.929947,...,-0.594730,1.762880,0.691058,0.117420,0.0,2.523214e+18,56301.695611,0.000011,4.0,21.356400,0.489529,35651585.0,0.000019,0.726127,-0.014049,0.818664,20.723400,0.037106,0.000009,0.055614,7.877810e-07,35651585.0,1.039530,4.0,1.47531,NaN,9.757030e-07,0.0,0.229726,105.864119,0.000017,3.792412e+15,NaN,21.314301,2.50000,0.001,NaN,1.076550e-07,35651585.0,0.858702,24.983700,0.000006,0.006697,0.0,-0.231646,0.790146,32.068698,1.198120,105.864122,2.146750,0.993778,0.868475,20.723101,3.554956e+15,-62.186501,0.005556,6409.0,0.0,2.523191e+18,3554956.0,0.000002,-0.000017,56363.257702,0.095893,-0.552024,0.000019,56073.729985,22.842699,0.299529,0.167133,35651585.0,1.069600,660.0,0.083105,3.242540e-07,NaN,NaN,0.000002,7.793350e-07,NaN,0.032768,4341886.0,0.000043,0.325730,0.998050,0.000004,0.103803,0.943772,0.000014,-0.000006,60796.710596,NaN,NaN,NaN,NaN,NaN,59861.468773,59874.486111,13.017338,13.017338
3,60168.430151,19.891600,16.017986,16.017986,NaN,16.017986,0.332001,0.738549,0.0,19.139200,14.040162,12.144228,13.450842,24.071412,1.046000,-0.510378,0.000000,0.557520,0.638637,0.037503,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.000232,0.000045,0.008214,0.001308,0.001968,NaN,0.008372,0.000673,False,0.0,0.133814,6.690610,3.329197,6.939874,0.983905,0.224879,0.564882,0.000000e+00,0.087849,1.218998,1.783097,5.738995,8.249798,0.146477,0.250046,0.037308,0.162770,0.517105,0.029405,0.444262,NaN,NaN,NaN,NaN,0.606977,2.711063,0.164649,0.095495,10.651462,0.001247,0.000232,0.015369,0.001136,0.008206,0.005486,0.027864,0.005755,0.0,ZTF17aaahhwn,69.419513,15.476838,1.0,4629.0,panstarrs,dr2,8.731575,5.265903e-15,5.265903e-15,"{'rpsfQfPerfect': 0.997987985610962, 'zinfoFla...",1.265707e+17,NaN,0.999887,69.419055,15.475506,0.061477,0.038571,-19.657119,0.877200,r,5.052795,...,27.889400,8.609510,32.283100,0.204750,8.0,2.523177e+18,56029.758091,0.000052,5.0,17.544001,0.000000,262160391.0,0.000046,0.536181,-0.002680,0.844265,19.620600,0.011020,0.000150,0.017615,4.890330e-07,262160391.0,1.064300,16.0,1.20624,0.358607,2.709190e-06,8.0,0.524166,69.419043,0.000424,3.737647e+15,NaN,19.704500,1.99999,0.001,2.63877,3.794600e-07,262160391.0,3.525280,25.000700,0.000349,0.327321,0.0,0.338785,1.176730,15.475460,0.051028,69.419023,8.813210,0.844592,0.845511,17.066799,3.527800e+15,-69.611900,0.002509,2966.0,1572992.0,2.523173e+18,3527800.0,0.000085,0.000419,56290.682505,0.026276,0.000000,0.000076,55907.662621,18.117399,0.012757,0.181665,262160391.0,6.803540,480.0,0.011566,2.178080e-06,0.000001,0.000082,0.000076,1.341610e-05,19.1180,0.004853,4334244.0,0.000394,0.013486,0.997816,0.000144,33.136902,0.652382,0.000310,0.000227,60796.710596,NaN,NaN,NaN,NaN,NaN,60168.430151,60208.496088,40.065937,40.065937
4,59163.441424,NaN,NaN,NaN,NaN,NaN,0.089211,-0.370045,0.0,NaN,NaN,NaN,NaN,NaN,0.134977,-0.670378,0.000000,0.499700,0.374033,-0.013112,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.000021,0.000008,0.000038,0.000015,-0.004096,NaN,NaN,NaN,False,0.0,0.124332,2.966214,2.169821,2.061728,0.472477,0.145045,0.501863,0.000000e+00,0.108621,2.729212,2.572773,0.982429,0.000000,0.090754,0.475010,0.000000,0.133191,0.186942,0.043897,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000178,0.000078,0.000102,0.000032,0.038685,0.041126,0.025475,0.002856,0.0,ZTF17aaazjab,117.810147,34.412364,3.0,15712.0,panstarrs,dr2,6.325459,1.979225e-15,1.979225e-15,"{'rnFrames': 15.0, 'ypsfMajorFWHM': 0.91689997...",1.492912e+17,NaN,0.930639,117.810329,34.412576,0.076348,0.019087,-21.537358,0.807840,r,0.940699,...,14.266700,4.933910,15.869800,0.198206,14.0,2.523198e+18,56286.473447,0.000674,10.0,16.156799,0.000000,262160391.0,0.000632,0.289077,-0.013810,0.884926,17.052099,0.001629,0.001112,0.002535,6.645630e-07,262160391.0,1.090340,29.0,1.06956,0.278656,1.323810e-06,15.0,0.392236,117.810362,0.001259,3.633557e+15,NaN,16.871000,2.50001,0.001,1.89873,8.144340e-07,262160391.0,2.272060,25.008600,0.001348,0.401881,0.0,-0.384896,0.973595,34.412566,0.003250,117.810337,5.680150,1.042310,0.872169,15.933900,3.563442e+15,-86.350700,0.000795,2817.0,524416.0,2.523214e+18,3563442.0,0.000758,0.001335,56593.472794,0.004418,0.000000,0.000663,56032.055520,16.447500,0.000813,0.231648,262160391.0,43.972599,630.0,0.002720,1.450220e-06,0.000001,0.000783,0.000754,4.369490e-04,16.6660,0.000465,4395353.0,0.001485,0.000878,0.997580,0.001095,18.360800,1.024430,0.001202,0.001288,60796.710596,NaN,NaN,NaN,NaN,NaN,59163.441424,59170.444711,7.003287,7.003287

## Cross-match to labeled catalog
Original notebook tried to match by `ZTFID` and now switched to coordinate matching.

Instead:
- converts ALeRCE RA/Dec strings into degrees
- matches each `df_cut` row to nearest ALeRCE object
- keeps matches within 1 arcsec

In [9]:
zdf = pd.read_csv(ALERCE_EXPLORER_CSV, low_memory=False)

df_cut["ZTFID"].describe()

df_copycut = df_cut.copy()

In [11]:
df_matched = df_copycut.merge(
    zdf,
    on="ZTFID",
    how="inner"   
)

len(set(df_copycut["ZTFID"]) & set(zdf["ZTFID"]))

3831

In [13]:
tmp = df_copycut.merge(
    zdf,
    on="ZTFID",
    how="left",
    indicator=True
)

df_matched   = tmp[tmp["_merge"] == "both"].drop(columns=["_merge"])

df_matched.head()

,t0,g_peak_mag,g_peak_time,g_rise_time,g_decline_time,g_duration_above_half_flux,g_amplitude,g_skewness,g_beyond_2sigma,r_peak_mag,r_peak_time,r_rise_time,r_decline_time,r_duration_above_half_flux,r_amplitude,r_skewness,r_beyond_2sigma,mean_g-r,g-r_at_g_peak,mean_color_rate,g_n_peaks,g_dt_main_to_secondary_peak,g_dmag_secondary_peak,g_secondary_peak_prominence,g_secondary_peak_width,r_n_peaks,r_dt_main_to_secondary_peak,r_dmag_secondary_peak,r_secondary_peak_prominence,r_secondary_peak_width,g_max_rolling_variance,g_mean_rolling_variance,r_max_rolling_variance,r_mean_rolling_variance,g_rise_local_curvature,g_decline_local_curvature,r_rise_local_curvature,r_decline_local_curvature,features_valid,t0_err,g_peak_mag_err,g_peak_time_err,g_rise_time_err,g_decline_time_err,g_duration_above_half_flux_err,g_amplitude_err,g_skewness_err,g_beyond_2sigma_err,r_peak_mag_err,r_peak_time_err,r_rise_time_err,r_decline_time_err,r_duration_above_half_flux_err,r_amplitude_err,r_skewness_err,r_beyond_2sigma_err,mean_g-r_err,g-r_at_g_peak_err,mean_color_rate_err,g_n_peaks_err,g_dt_main_to_secondary_peak_err,g_dmag_secondary_peak_err,g_secondary_peak_prominence_err,g_secondary_peak_width_err,r_n_peaks_err,r_dt_main_to_secondary_peak_err,r_dmag_secondary_peak_err,r_secondary_peak_prominence_err,r_secondary_peak_width_err,g_max_rolling_variance_err,g_mean_rolling_variance_err,r_max_rolling_variance_err,r_mean_rolling_variance_err,g_rise_local_curvature_err,g_decline_local_curvature_err,r_rise_local_curvature_err,r_decline_local_curvature_err,features_valid_err,ZTFID,ra,dec,Unnamed: 0,idx,best_cat,best_cat_release,query_time,smallcone_posterior,missedcat_posterior,extra_cat_cols,host_objID,host_name,host_total_posterior,host_ra,host_dec,host_redshift_mean,host_redshift_std,host_absmag_mean,host_absmag_std,host_absmag_info,host_offset_mean,...,momentXY,ypsfMinorFWHM,zPSFMag,yraErr,iFApFlux,zPSFMagErr,iPSFFluxErr,rinfoFlag,ipsfMinorFWHM,inFrames,gpsfMinorFWHM,gmomentXX,iKronFluxErr,ng,rpsfCore,raStack,zFKronFlux,uniquePspsSTid,objAltName1,iPSFMag,zApRadius,decStackErr,gmomentR1,yApFluxErr,zinfoFlag,rmomentR1,gzp,iKronFlux,randomID,surveyID,cx,imomentRH,ydec,gyPosErr,rra,rKronRad,zpsfMinorFWHM,yApFillFac,yKronMag,uniquePspsOBid,rpsfTheta,zApMagErr,iippDetectID,iinfoFlag2,ystackDetectID,batchID,rFmeanflxR5,zFmeanflxR7,iEpoch,zxPosErr,rpsfLikelihood,yPSFFlux,yEpoch,rKronMag,gdecErr,zmomentXX,yinfoFlag,zpsfChiSq,zexpTime,zKronMagErr,rKronFluxErr,gKronFluxErr,gKronFlux,rFApFlux,gPSFFlux,gKronMag,iraErr,gstackImageID,yFmeanflxR6,graErr,ipsfQf,iFmeanflxR5,zExtNSigma,ypsfCore,zFmeanflxR6,iFmeanflxR6,mjd_extracted,tns_redshift,latest_magnitude,oldest_alert,newest_alert,peak_phase,antares_oldest_alert,antares_newest_alert,antares_duration,duration_days,IAUID,RA,Dec,peakt,peakfilt,peakmag,peakabs,duration,rise,fade,type,redshift,b_y,A_V
0,59850.515694,18.058201,19.991794,6.032847,12.011400,18.044248,0.521299,0.225308,0.000000,17.598600,0.000000,NaN,33.467286,31.981111,1.021000,-0.492451,0.083333,0.109230,0.027208,0.016575,1,NaN,NaN,NaN,NaN,2,12.119703,0.211326,0.249921,20.899493,0.000295,0.000144,0.071492,0.001672,-0.007540,-0.002478,NaN,-0.005436,False,0.0,0.058249,0.903369,0.903369,0.903369,0.000000,0.074867,0.576231,0.061170,0.170234,0.000000,NaN,16.194011,4.325329,0.154256,0.477562,0.045843,0.051900,0.119613,0.008798,0.615587,4.181948,0.153224,0.045004,13.055632,0.638666,3.519174,0.126541,0.123748,7.833686,0.000581,0.000123,0.054051,0.000855,0.021606,0.012067,NaN,0.006085,0.000000,ZTF17aabtvsy,158.883762,37.649729,5.0,19226.0,panstarrs,dr2,6.246375,1.341795e-15,1.341795e-15,"{'iinfoFlag3': 196608.0, 'zpsfQfPerfect': 0.99...",1.531816e+17,NaN,0.987186,158.883575,37.649555,0.077098,0.019274,-22.734511,0.749100,r,0.829189,...,-0.002408,0.943950,16.888700,0.001657,0.001063,0.001878,6.914810e-07,262160391.0,0.927463,16.0,1.17831,0.319913,4.597210e-06,12.0,0.522189,158.883637,0.004043,3.738386e+15,NaN,17.254601,2.25,0.001,4.69666,1.093620e-06,262160391.0,6.85620,24.950701,0.003692,0.744533,0.0,-0.738595,0.970184,37.649583,0.006502,158.883628,17.140499,1.008880,0.859437,14.688800,3.600872e+15,55.072300,0.000677,1959.0,524416.0,2.523243e+18,3600872.0,0.000764,0.002693,56536.031130,0.003129,0.000000e+00,0.000776,56204.427467,15.409000,0.001625,0.203681,262160391.0,10.139900,722.0,0.001885,4.149480e-06,2.535200e-06,0.000986,0.000905,0.000188,16.414900,0.000597,4567628.0,0.002399,0.001737,0.997530,0.001177,19.938200,0.664856,0.001948,0.001616,60796.710596,NaN,NaN,NaN,NaN,NaN,59850.515694,59901.530729,51.015035,51.015035,SN2022yei,10:35:32.09,+37:38:59.0,1870.99,r,18.0303,-19.41,>34.229,>6.01,28.219,SN Ia,0.06922,59.641962,0.053
1,60596.327662,16.803886,9.917465,8.474729,14.790803,16.114167,3.273268,0.270541,0.000000,17.555490,34.969363,NaN,13.471450,2.982419,1.341433,-0.426584,0.000000,0.908953,-0.751604,-0.005580,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.056652,0.005948,0.000541,0.000441,0.022751,0.006562,NaN,NaN,False,0.0,0.037687,1.645437,1.707257,1.600286,3.683273,0.170410,0.046208,0.000000,0.040870,0.000000,NaN,1.917810,0.000000,0.083318,0.056074,0.000000,0.121456,0.050861,0.007787,0.552506,6.309628,0.220410,0.117434,9.974748,0.223607,NaN,NaN,NaN,NaN,0.012854,0.001026,0.001621,0.000134,0.008264,0.008680,NaN,NaN,0.000000,ZTF17aabvong,31.282032,11.248651,6.0,8996.0,panstarrs,dr2,6.524667,1.132243e-15,1.132243e-15,"{'iPSFFlux': 0.0002382450038567, 'projectionID...",1.214903e+17,NaN,1.000000,31.282127,11.248569,0.025181,0.007587,-20.618437,0.729355,r,0.454126,...,0.002253,0.844023,17.735600,0.004179,0.000697,0.004494,6.202390e-07,262160391.0,0.983609,14.0,1.15710,0.360280,5.837870e-06,14.0,0.437406,31.282053,0.006039,3.673351e+15,NaN,17.957399,2.25,0.001,6.43585,8.365690e-07,262160391.0,6.90098,24.995100,0.005311,0.046059,0.0,0.838204,1.092810,11.248618,0.007672,31.282053,17.252501,0.871072,0.864545,14.171600,3.501513e+15,-9.446360,0.000970,6290.0,1572992.0,2.523108e+18,3501513.0,0.000645,0.003231,56294.406587,0.006940,0.000000e+00,0.000324,55941.203492,14.951000,0.001918,0.233626,262160391.0,169.826996,540.0,0.001870,5.242890e-06,3.362150e-06,0.001872,0.000632,0.000114,15.719100,0.001144,4030072.0,0.002548,0.002127,0.997932,0.000839,35.214901,0.595606,0.001940,0.001579,60796.710596,NaN,NaN,NaN,NaN,NaN,60596.327662,60663.246713,66.919051,66.919051,SN2024xxq,02:05:07.68,+11:14:55.1,2606.75,g,16.8039,-19.57,23.222,8.464,14.758,SN Ia,0.034,-47.664064,0.446
20,59173.447870,18.974548,7.067546,7.067546,16.720824,22.995752,1.287252,0.749261,0.000000,19.101851,9.042870,1.956157,21.933148,23.889306,0.602354,0.385230,0.000000,0.278525,-0.359152,0.048309,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.003025,0.000674,0.001636,0.000241,0.010747,0.000535,NaN,-0.003986,False,0.0,0.111942,2.150783,2.150783,2.493344,7.311149,0.262028,0.189282,0.045793,0.079415,4.475092,4.294002,4.362970,2.168362,0.121970,0.470695,0.045599,0.080815,0.308499,0.022120,0.447214,9.648425,0.329574,0.049232,3.253857,0.875094,3.469118,0.125229,0.097304,12.616382,0.004806,0.000606,0.005619,0.000460,0.047836,0.013632,0.032050,0.019498,0.512989,ZTF18aacnlxz,134.954664,38.109070,63.0,5.0,panstarrs,dr2,9.391677,1.897190e-15,1.897190e-15,"{'ixPosErr': 0.0068755098618566, 'gyPos': 1807...",1.537313e+17,NaN,0.997602,134.954725,38.108963,0.077816,0.019454,-18.989943,0.937390,r,0.433211,...,-0.004518,0.747760,19.246901,0.010846,0.000128,0.011823,3.215180e-07,262160391.0,1.109980,37.0,1.12981,0.215833,6.211500e-07,11.0,0.276354,134.954717,0.000101,3.699840e+15,NaN,18.980801,2.25,0.001,1.30342,2.580670e-07,262160391.0,1.38775,24.998699,0.000126,0.304170,0.0,-0.555939,0.916655,38.108959,0.010012,134.954725,3.469360,0.953642,0.840537,18.622101,3.576514e+15,-33.867500,0.001908,1309.0,524416.0,2.523224e+18,3576514.0,0.000084,0.000100,56641.112870,0.019803,5.629140e-14,0.000069,55902.139086,19.058500,0.002503,0.146783,262160391.0,1.775590,1020.0,0.017235,8.187660e-07,7.353790e-07,0.000115,0.000088,0.000097,18.747801,0.001719,4491923.0,0.000154,0.002901,0.998264,0.000126,10.668100,0.941259,0.000106,0.000132,60796.710596,NaN,NaN,NaN,NaN,NaN,59173.447870,59204.423889,30.976019,30.976019,SN2020aavr,08:59:49.12,+38:06:32.6,1181.02,g,18.9745,-18.61,27.803,8.896,18.907,SN II,0.07247,40.805389,0.068
23,60043.177928,18.908300,0.104329,NaN,5.796895,5.881979,0.985100,0.005564,0.000000,18.595699,0.000000,NaN,12.025185,12.025185,0.747200,-0.266398,0.000000,0.463985,0.176795,0.067047,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.001475,0.000254,0.006212,0.000423,NaN,-0.017796,NaN,0.004720,False,0.0,0.197704,0.013469,0.000000,1.898932,2.243103,0.261337,0.331959,0.027951,0.097631,0.635572,1.123934,2.122267,2.672136,0.175839,0.270138,0.024845,0.097463,0.235680,0.073733,0.858395,1.679233,0.200956,0.096369,15.396584,0.825578,1.794192,0.063599,0.092001,22.418160,0.037077,0.000763,0.012293,0.000641,NaN,0.097793,0.080044,0.042549,0.000000,ZTF18aaczmob,105.519506,49.059275,67.0,11983.0,panstarrs,dr2,9.113055,2.113283e-15,2.113283e-15,"{'epochMean': 56901.90640046, 'iippDetectID': ...",1.668711e+17,NaN,0.996547,105.519165,49.059571,0.077820,0.019455,-21.602051,0.806790,r,1.341543,...,0.001743,0.972577,17.310600,0.001958,0.000745,0.003143,4.892170e-07,262160391.0,1.003370,31.0,1.28081,0.336879,1.742540e-06,13.0,0.375259,105.519161,0.001548,3.732512e+15,NaN,17.466700,2.25,0.001,3.36597,8.414200e-07,262160391.0,2.95876,25.019600,0.001276,0.407551,0.0,-0.175326,1.016880,49.059592,0.008544,105.519115,7.396900,0.894952,0.886532,15.851800,3.545760e+15,-28.087700,0.000910,1013.0,524416.0,2.523203e+18,3545760.0,0.000461,0.001533,56707.877770,0.004968,0.000000e+00,0.000636,56070.327335,16.606501,0.002136,0.177212,262160391.0,40.895599,540.0,0.003471,2.746670e-06,1.594720e-06,0.000409,0.000544,0.000134,17.371901,0.000571,4579261.0,0.001434,0.002237,0.997245,0.000791,22.660299,1.101420,0.001251,0.001020,60796.710596,NaN,NaN,NaN,NaN,NaN,60031.160231,60053.213090,22.052859,22.052859,-,07:02:04.68,+49:03:33.4,2043.68,r,18.5957,-,>20.036,>12.02,8.016,-,-,21.808882,0.210
24,59267.246863,18.704327,7.927118,6.460970,6.152083,9.961250,1.008818,1.461279,0.166667,18.589582,10.936713,6.924757,3.040232,9.964989,0.373775,-0.484507,0.000000,0.042387,-0.065440,0.009466,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.001236,0.000458,0.000078,0.000065,0.044192,0.013724,-0.018445,NaN,False,0.0,0.082206,2.406094,2.334064,2.406094,0.000000,0.192350,0.312030,0.078360,0.085528,0.697477,0.697477,0.000000,0.000000,0.153696,0.570150,0.000000,0.085270,0.202465,0.022381,0.444262,1.267698,0.097251,0.067323,14.321966,0.510418,NaN,NaN,NaN,NaN,0.000910,0.000286,0.000304,0.000087,0.027477,0.019351,0.023023,NaN,0.000000,ZTF18aadaexi,125.241560,36.312320,68.0,18938.0,panstarrs,dr2,7.009168,1.751783e-15,1.751783e-15,"{'iFApFlux': 0.0010230799671262, 'rsky': 1.495...",1.515713e+17,NaN,0.994366,125.241135,36.312345,0.083110,0.020777,-22.230179,0.782920,r,1.239423,...,0.006807,0.985270,16.828600,0.001838,0.001023,0.001917,5.571510e-07,262160391.0,1.164740,30.0,1.01551,0.230307,2.571340e-06,12.0,0.238187,125.241162,0.002445,3.683933e+15,NaN,17.115000,2.75,0.001,3.81854,9.700050e-07,262160391.0,4.77802,25.021000,0.001980,0.028116,0.0,-0.464962,1.080050,36.312357,0.005980,125.241127,11.945000,1.128080,0.883902,15.298900,3.573121e+15,66.336899,0.000644,5808.0,524416.0,2.523223e+18,3573121.0,0.000647,0.002134,56592.255214,0.003764,0.000000e+00,0.000778,56055.508459,16.085400,0.001495,0.278755,262160391.0,91.623398,750.0,0.002396,4.234870e-06,2.133650e-06,0.000586,0.000674,0.000152,16.980600,0.000546,4489803.0,0.001867,0.001626,0.997968,0.001006,16.551001,0.565476,0.001687,0.001328,60796.710596,NaN,NaN,NaN,NaN,NaN,59267.246863,59293.155081,25.908218,25.908218,AT2021dpr,08:20:57.97,+36:18:44.3,1278.68,r,18.5896,-,19.247,9.507,9.74,-,-,32.895312,0.159

In [15]:
df_unmatched = tmp[tmp["_merge"] == "left_only"].drop(columns=["_merge"])

df_unmatched.head()

,t0,g_peak_mag,g_peak_time,g_rise_time,g_decline_time,g_duration_above_half_flux,g_amplitude,g_skewness,g_beyond_2sigma,r_peak_mag,r_peak_time,r_rise_time,r_decline_time,r_duration_above_half_flux,r_amplitude,r_skewness,r_beyond_2sigma,mean_g-r,g-r_at_g_peak,mean_color_rate,g_n_peaks,g_dt_main_to_secondary_peak,g_dmag_secondary_peak,g_secondary_peak_prominence,g_secondary_peak_width,r_n_peaks,r_dt_main_to_secondary_peak,r_dmag_secondary_peak,r_secondary_peak_prominence,r_secondary_peak_width,g_max_rolling_variance,g_mean_rolling_variance,r_max_rolling_variance,r_mean_rolling_variance,g_rise_local_curvature,g_decline_local_curvature,r_rise_local_curvature,r_decline_local_curvature,features_valid,t0_err,g_peak_mag_err,g_peak_time_err,g_rise_time_err,g_decline_time_err,g_duration_above_half_flux_err,g_amplitude_err,g_skewness_err,g_beyond_2sigma_err,r_peak_mag_err,r_peak_time_err,r_rise_time_err,r_decline_time_err,r_duration_above_half_flux_err,r_amplitude_err,r_skewness_err,r_beyond_2sigma_err,mean_g-r_err,g-r_at_g_peak_err,mean_color_rate_err,g_n_peaks_err,g_dt_main_to_secondary_peak_err,g_dmag_secondary_peak_err,g_secondary_peak_prominence_err,g_secondary_peak_width_err,r_n_peaks_err,r_dt_main_to_secondary_peak_err,r_dmag_secondary_peak_err,r_secondary_peak_prominence_err,r_secondary_peak_width_err,g_max_rolling_variance_err,g_mean_rolling_variance_err,r_max_rolling_variance_err,r_mean_rolling_variance_err,g_rise_local_curvature_err,g_decline_local_curvature_err,r_rise_local_curvature_err,r_decline_local_curvature_err,features_valid_err,ZTFID,ra,dec,Unnamed: 0,idx,best_cat,best_cat_release,query_time,smallcone_posterior,missedcat_posterior,extra_cat_cols,host_objID,host_name,host_total_posterior,host_ra,host_dec,host_redshift_mean,host_redshift_std,host_absmag_mean,host_absmag_std,host_absmag_info,host_offset_mean,...,momentXY,ypsfMinorFWHM,zPSFMag,yraErr,iFApFlux,zPSFMagErr,iPSFFluxErr,rinfoFlag,ipsfMinorFWHM,inFrames,gpsfMinorFWHM,gmomentXX,iKronFluxErr,ng,rpsfCore,raStack,zFKronFlux,uniquePspsSTid,objAltName1,iPSFMag,zApRadius,decStackErr,gmomentR1,yApFluxErr,zinfoFlag,rmomentR1,gzp,iKronFlux,randomID,surveyID,cx,imomentRH,ydec,gyPosErr,rra,rKronRad,zpsfMinorFWHM,yApFillFac,yKronMag,uniquePspsOBid,rpsfTheta,zApMagErr,iippDetectID,iinfoFlag2,ystackDetectID,batchID,rFmeanflxR5,zFmeanflxR7,iEpoch,zxPosErr,rpsfLikelihood,yPSFFlux,yEpoch,rKronMag,gdecErr,zmomentXX,yinfoFlag,zpsfChiSq,zexpTime,zKronMagErr,rKronFluxErr,gKronFluxErr,gKronFlux,rFApFlux,gPSFFlux,gKronMag,iraErr,gstackImageID,yFmeanflxR6,graErr,ipsfQf,iFmeanflxR5,zExtNSigma,ypsfCore,zFmeanflxR6,iFmeanflxR6,mjd_extracted,tns_redshift,latest_magnitude,oldest_alert,newest_alert,peak_phase,antares_oldest_alert,antares_newest_alert,antares_duration,duration_days,IAUID,RA,Dec,peakt,peakfilt,peakmag,peakabs,duration,rise,fade,type,redshift,b_y,A_V
2,59861.468773,18.025000,0.000000,NaN,1.246246,5.971481,1.945101,0.815205,0.1,18.274099,0.021192,NaN,1.415106,9.945428,1.760750,0.595434,0.090909,-0.098382,-0.249100,0.013544,1,NaN,NaN,NaN,NaN,2,5.954756,0.602849,0.198726,31.826992,0.014541,0.004381,0.019289,0.004223,NaN,0.076705,NaN,0.087738,False,0.0,0.042273,0.000000,NaN,0.240076,1.968606,0.103605,0.153046,1.423831e-17,0.051127,1.643622,0.000000,1.198672,1.987739,0.178663,0.222787,0.020328,0.044112,0.063622,0.014004,0.489360,1.540522,0.171408,0.075891,7.011332,0.695852,1.965831,0.294856,0.083630,10.050958,0.005109,0.001060,0.010062,0.000792,NaN,0.070404,0.089636,0.111978,0.000000,ZTF17aaaycpc,105.863596,32.068390,2.0,10296.0,panstarrs,dr2,8.549133,7.403929e-15,7.403929e-15,"{'raStackErr': 0.0010000000474974, 'cz': 0.530...",1.464811e+17,NaN,0.998975,105.864122,32.068686,0.516699,0.259615,-20.990470,1.067820,r,1.929947,...,-0.014049,0.818664,20.723400,0.037106,0.000009,0.055614,7.877810e-07,35651585.0,1.039530,4.0,1.47531,NaN,9.757030e-07,0.0,0.229726,105.864119,0.000017,3.792412e+15,NaN,21.314301,2.50000,0.001,NaN,1.076550e-07,35651585.0,0.858702,24.983700,0.000006,0.006697,0.0,-0.231646,0.790146,32.068698,1.198120,105.864122,2.14675,0.993778,0.868475,20.723101,3.554956e+15,-62.186501,0.005556,6409.0,0.0,2.523191e+18,3554956.0,0.000002,-0.000017,56363.257702,0.095893,-0.552024,0.000019,56073.729985,22.842699,0.299529,0.167133,35651585.0,1.069600,660.0,0.083105,3.242540e-07,NaN,NaN,0.000002,7.793350e-07,NaN,0.032768,4341886.0,0.000043,0.325730,0.998050,0.000004,0.103803,0.943772,0.000014,-0.000006,60796.710596,NaN,NaN,NaN,NaN,NaN,59861.468773,59874.486111,13.017338,13.017338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,60168.430151,19.891600,16.017986,16.017986,NaN,16.017986,0.332001,0.738549,0.0,19.139200,14.040162,12.144228,13.450842,24.071412,1.046000,-0.510378,0.000000,0.557520,0.638637,0.037503,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.000232,0.000045,0.008214,0.001308,0.001968,NaN,0.008372,0.000673,False,0.0,0.133814,6.690610,3.329197,6.939874,0.983905,0.224879,0.564882,0.000000e+00,0.087849,1.218998,1.783097,5.738995,8.249798,0.146477,0.250046,0.037308,0.162770,0.517105,0.029405,0.444262,NaN,NaN,NaN,NaN,0.606977,2.711063,0.164649,0.095495,10.651462,0.001247,0.000232,0.015369,0.001136,0.008206,0.005486,0.027864,0.005755,0.000000,ZTF17aaahhwn,69.419513,15.476838,1.0,4629.0,panstarrs,dr2,8.731575,5.265903e-15,5.265903e-15,"{'rpsfQfPerfect': 0.997987985610962, 'zinfoFla...",1.265707e+17,NaN,0.999887,69.419055,15.475506,0.061477,0.038571,-19.657119,0.877200,r,5.052795,...,-0.002680,0.844265,19.620600,0.011020,0.000150,0.017615,4.890330e-07,262160391.0,1.064300,16.0,1.20624,0.358607,2.709190e-06,8.0,0.524166,69.419043,0.000424,3.737647e+15,NaN,19.704500,1.99999,0.001,2.63877,3.794600e-07,262160391.0,3.525280,25.000700,0.000349,0.327321,0.0,0.338785,1.176730,15.475460,0.051028,69.419023,8.81321,0.844592,0.845511,17.066799,3.527800e+15,-69.611900,0.002509,2966.0,1572992.0,2.523173e+18,3527800.0,0.000085,0.000419,56290.682505,0.026276,0.000000,0.000076,55907.662621,18.117399,0.012757,0.181665,262160391.0,6.803540,480.0,0.011566,2.178080e-06,0.000001,0.000082,0.000076,1.341610e-05,19.118000,0.004853,4334244.0,0.000394,0.013486,0.997816,0.000144,33.136902,0.652382,0.000310,0.000227,60796.710596,NaN,NaN,NaN,NaN,NaN,60168.430151,60208.496088,40.065937,40.065937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,59163.441424,NaN,NaN,NaN,NaN,NaN,0.089211,-0.370045,0.0,NaN,NaN,NaN,NaN,NaN,0.134977,-0.670378,0.000000,0.499700,0.374033,-0.013112,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.000021,0.000008,0.000038,0.000015,-0.004096,NaN,NaN,NaN,False,0.0,0.124332,2.966214,2.169821,2.061728,0.472477,0.145045,0.501863,0.000000e+00,0.108621,2.729212,2.572773,0.982429,0.000000,0.090754,0.475010,0.000000,0.133191,0.186942,0.043897,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000178,0.000078,0.000102,0.000032,0.038685,0.041126,0.025475,0.002856,0.000000,ZTF17aaazjab,117.810147,34.412364,3.0,15712.0,panstarrs,dr2,6.325459,1.979225e-15,1.979225e-15,"{'rnFrames': 15.0, 'ypsfMajorFWHM': 0.91689997...",1.492912e+17,NaN,0.930639,117.810329,34.412576,0.076348,0.019087,-21.537358,0.807840,r,0.940699,...,-0.013810,0.884926,17.052099,0.001629,0.001112,0.002535,6.645630e-07,262160391.0,1.090340,29.0,1.06956,0.278656,1.323810e-06,15.0,0.392236,117.810362,0.001259,3.633557e+15,NaN,16.871000,2.50001,0.001,1.89873,8.144340e-07,262160391.0,2.272060,25.008600,0.001348,0.401881,0.0,-0.384896,0.973595,34.412566,0.003250,117.810337,5.68015,1.042310,0.872169,15.933900,3.563442e+15,-86.350700,0.000795,2817.0,524416.0,2.523214e+18,3563442.0,0.000758,0.001335,56593.472794,0.004418,0.000000,0.000663,56032.055520,16.447500,0.000813,0.231648,262160391.0,43.972599,630.0,0.002720,1.450220e-06,0.000001,0.000783,0.000754,4.369490e-04,16.666000,0.000465,4395353.0,0.001485,0.000878,0.997580,0.001095,18.360800,1.024430,0.001202,0.001288,60796.710596,NaN,NaN,NaN,NaN,NaN,59163.441424,59170.444711,7.003287,7.003287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,60635.340544,19.191984,1.946759,1.946759,11.899672,13.043426,0.919960,0.229242,0.0,19.248514,5.002998,4.932164,10.102558,15.034722,0.349546,0.528644,0.000000,0.206339,-0.125611,0.018020,2,7.046778,0.284679,0.148666,30.466405,0,NaN,NaN,NaN,NaN,0.003029,0.000562,0.000576,0.000123,-0.084371,0.023301,-0.007316,0.011983,True,0.0,0.131003,2.172262,2.023882,1.567870,2.242813,0.157982,0.250040,3.417397e-02,0.083200,3.952559,3.857736,3.939719,0.610632,0.151167,0.773426,0.063466,0.090530,0.244201,0.027715,0.812728,2.120356,0.140290,0.118371,23.388351,0.923381,1.550585,0.085013,0.112500,27.728795,0.013609,0.000765,0.009691,0.000423,0.324583,0.049230,0.028030,0.063916,0.510418,ZTF17aadcedu,104.070385,37.029006,15.0,16665.0,panstarrs,dr2,7.338146,2.247694e-15,2.247694e-15,"{'zApMag': 17.15019989013672, 'momentYY': 0.22...",1.524310e+17,NaN,0.982211,104.070475,37.029474,0.151999,0.038000,-22.723023,0.828720,r,1.704147,...,-0.021807,0.832674,18.051800,0.003133,0.000410,0.004977,4.497080e-07,102776839.0,0.973961,24.0,1.36127,0.548462,2.052730e-06,13.0,0.367960,104.070468,0.001083,3.777059e+15,NaN,18.307800,2.00000,0.001,3.24535,7.294550e-07,102776839.0,3.463700,25.007299,0.000852,0.664673,0.0,-0.194085,1.070400,37.029517,0.021216,104.070489,8.65925,0.882796,0.872405,16.047501,3.560718e+15,13.907300,0.001126,11112.0,128.0,2.523193e+18,3560718.0,0.000264,0.001068,56683.936732,0.007860,0.000000,0.000320,56144.359124,17.126400,0.005304,0.178281,102776839.0,29.670000,630.0,0.004873,2.299640e-06,0.000002,0.000207,0.000335,5.118510e-05,18.109100,0.001187,4340103.0,0.001057,0.005484,0.996763,0.000473,40.511299,1.120380,0.000869,0.000648,60796.710596,NaN,NaN,NaN,NaN,NaN,60635.340544,60652.332373,16.991829,16.991829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,60253.313345,17.772699,8.019803,7.152844,23.900289,3.961007,1.924301,0.057989,0.0,17.778400,10.048935,8.855082,24.849410,6.086123,0.948299,0.222121,0.000000,0.386144,-0.101989,0.032312,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.008082,0.001833,0.007754,0.001019,0.039968,NaN,0.024831,NaN,False,0.0,0.042966,0.723765,0.934349,3.276472,1.486930,0.096331,0.084314,0.000000e+00,0.037942,0.976601,0.949144,1.587273,13.278388,0.080242,0.104527,0.000000,0.050053,0.067983,0.005198,0.307794,0.000000,0.027784,0.119625,2.822687,0.366348,0.071190,0.036253,0.017134,6.576485,0.003898,0.000295,0.002922,0.000227,0.014790,NaN,0.017540,NaN,0.000000,ZTF17aacpbmv,49.465938,-0.104966,12.0,9831.0,panstarrs,dr2,5.166699,1.515270e-15,1.515270e-15,"{'gxPos': 2156.4599609375, 'yPSFMag': 17.88459...",1.078705e+17,NaN,0.999649,49.465826,-0.104993,0.031643,0.013094,-18.818527,0.844675,r,0.424008,...,0.007385,0.726455,18.125601,0.002523,0.000466,0.005446,5.415220e-07,262160391.0,0.933417,18.0,1.07518,0.302363,1.678240e-06,8.0,0.508974,49.465770,0.000700,3.700477e+15,NaN,18.044100,2.00000,0.001,2.26232,5.274740e-07,262160391.0,2.404890,25.009899,0.000635,0.160407,0.0,0.649900,1.026690,-0.104996,0.008682,49.465764,6.01222,0.867595,0.840537,16.641899,3.506425e+15,-77.396004,0.001432,2804.0,524416.0,2.523134e+18,3506425.0,0.000391,0.000686,56598.879284,0.008145,0.000000,0.000255,55914.690547,17.097099,0.002171,0.163975,262160391.0,14.377100,480.0,0.005883,1.418030e-06,0.000001,0.000332,0.000419,1.497300e-04,17.598801,0.001081,4165576.0,0.000752,0.002310,0.997638,0.000445,23.109600,1.202280,0.000605,0.000565,60796.710596,NaN,NaN,NaN,NaN,NaN,60253.313345,60314.131678,60.818333,60.818333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
alerce_coords = SkyCoord(
    ra=zdf["RA"].astype(str),
    dec=zdf["Dec"].astype(str),
    unit=(u.hourangle, u.deg)
)
zdf = zdf.copy()
zdf["ra_deg"] = alerce_coords.ra.deg
zdf["dec_deg"] = alerce_coords.dec.deg

In [19]:
ref_coords = SkyCoord(ra=df_cut["ra"].values * u.deg, dec=df_cut["dec"].values * u.deg)

idx, sep2d, _ = ref_coords.match_to_catalog_sky(alerce_coords)
mask_match = sep2d < (1.0 * u.arcsec)

In [21]:
df_copycut["alerce_idx"] = idx
df_copycut["matched"] = mask_match

df_copycut.head()

,t0,g_peak_mag,g_peak_time,g_rise_time,g_decline_time,g_duration_above_half_flux,g_amplitude,g_skewness,g_beyond_2sigma,r_peak_mag,r_peak_time,r_rise_time,r_decline_time,r_duration_above_half_flux,r_amplitude,r_skewness,r_beyond_2sigma,mean_g-r,g-r_at_g_peak,mean_color_rate,g_n_peaks,g_dt_main_to_secondary_peak,g_dmag_secondary_peak,g_secondary_peak_prominence,g_secondary_peak_width,r_n_peaks,r_dt_main_to_secondary_peak,r_dmag_secondary_peak,r_secondary_peak_prominence,r_secondary_peak_width,g_max_rolling_variance,g_mean_rolling_variance,r_max_rolling_variance,r_mean_rolling_variance,g_rise_local_curvature,g_decline_local_curvature,r_rise_local_curvature,r_decline_local_curvature,features_valid,t0_err,g_peak_mag_err,g_peak_time_err,g_rise_time_err,g_decline_time_err,g_duration_above_half_flux_err,g_amplitude_err,g_skewness_err,g_beyond_2sigma_err,r_peak_mag_err,r_peak_time_err,r_rise_time_err,r_decline_time_err,r_duration_above_half_flux_err,r_amplitude_err,r_skewness_err,r_beyond_2sigma_err,mean_g-r_err,g-r_at_g_peak_err,mean_color_rate_err,g_n_peaks_err,g_dt_main_to_secondary_peak_err,g_dmag_secondary_peak_err,g_secondary_peak_prominence_err,g_secondary_peak_width_err,r_n_peaks_err,r_dt_main_to_secondary_peak_err,r_dmag_secondary_peak_err,r_secondary_peak_prominence_err,r_secondary_peak_width_err,g_max_rolling_variance_err,g_mean_rolling_variance_err,r_max_rolling_variance_err,r_mean_rolling_variance_err,g_rise_local_curvature_err,g_decline_local_curvature_err,r_rise_local_curvature_err,r_decline_local_curvature_err,features_valid_err,ZTFID,ra,dec,Unnamed: 0,idx,best_cat,best_cat_release,query_time,smallcone_posterior,missedcat_posterior,extra_cat_cols,host_objID,host_name,host_total_posterior,host_ra,host_dec,host_redshift_mean,host_redshift_std,host_absmag_mean,host_absmag_std,host_absmag_info,host_offset_mean,...,yExtNSigma,ymomentYY,ny,zstackDetectID,gEpoch,iFPSFFlux,nStackDetections,KronMag,ypsfLikelihood,iinfoFlag,zFPSFFlux,zpsfCore,momentXY,ypsfMinorFWHM,zPSFMag,yraErr,iFApFlux,zPSFMagErr,iPSFFluxErr,rinfoFlag,ipsfMinorFWHM,inFrames,gpsfMinorFWHM,gmomentXX,iKronFluxErr,ng,rpsfCore,raStack,zFKronFlux,uniquePspsSTid,objAltName1,iPSFMag,zApRadius,decStackErr,gmomentR1,yApFluxErr,zinfoFlag,rmomentR1,gzp,iKronFlux,randomID,surveyID,cx,imomentRH,ydec,gyPosErr,rra,rKronRad,zpsfMinorFWHM,yApFillFac,yKronMag,uniquePspsOBid,rpsfTheta,zApMagErr,iippDetectID,iinfoFlag2,ystackDetectID,batchID,rFmeanflxR5,zFmeanflxR7,iEpoch,zxPosErr,rpsfLikelihood,yPSFFlux,yEpoch,rKronMag,gdecErr,zmomentXX,yinfoFlag,zpsfChiSq,zexpTime,zKronMagErr,rKronFluxErr,gKronFluxErr,gKronFlux,rFApFlux,gPSFFlux,gKronMag,iraErr,gstackImageID,yFmeanflxR6,graErr,ipsfQf,iFmeanflxR5,zExtNSigma,ypsfCore,zFmeanflxR6,iFmeanflxR6,mjd_extracted,tns_redshift,latest_magnitude,oldest_alert,newest_alert,peak_phase,antares_oldest_alert,antares_newest_alert,antares_duration,duration_days,alerce_idx,matched
0,59850.515694,18.058201,19.991794,6.032847,12.011400,18.044248,0.521299,0.225308,0.0,17.598600,0.000000,NaN,33.467286,31.981111,1.021000,-0.492451,0.083333,0.109230,0.027208,0.016575,1,NaN,NaN,NaN,NaN,2,12.119703,0.211326,0.249921,20.899493,0.000295,0.000144,0.071492,0.001672,-0.007540,-0.002478,NaN,-0.005436,False,0.0,0.058249,0.903369,0.903369,0.903369,0.000000,0.074867,0.576231,6.117006e-02,0.170234,0.000000,NaN,16.194011,4.325329,0.154256,0.477562,0.045843,0.051900,0.119613,0.008798,0.615587,4.181948,0.153224,0.045004,13.055632,0.638666,3.519174,0.126541,0.123748,7.833686,0.000581,0.000123,0.054051,0.000855,0.021606,0.012067,NaN,0.006085,0.0,ZTF17aabtvsy,158.883762,37.649729,5.0,19226.0,panstarrs,dr2,6.246375,1.341795e-15,1.341795e-15,"{'iinfoFlag3': 196608.0, 'zpsfQfPerfect': 0.99...",1.531816e+17,NaN,0.987186,158.883575,37.649555,0.077098,0.019274,-22.734511,0.749100,r,0.829189,...,23.644100,0.228099,13.0,2.523244e+18,55923.256190,0.000530,5.0,14.982000,0.000000,262160391.0,0.000617,0.425564,-0.002408,0.943950,16.888700,0.001657,0.001063,0.001878,6.914810e-07,262160391.0,0.927463,16.0,1.17831,0.319913,4.597210e-06,12.0,0.522189,158.883637,0.004043,3.738386e+15,NaN,17.254601,2.25000,0.001,4.69666,1.093620e-06,262160391.0,6.856200,24.950701,0.003692,0.744533,0.0,-0.738595,0.970184,37.649583,0.006502,158.883628,17.140499,1.008880,0.859437,14.688800,3.600872e+15,55.072300,0.000677,1959.0,524416.0,2.523243e+18,3600872.0,0.000764,0.002693,56536.031130,0.003129,0.000000,0.000776,56204.427467,15.409000,0.001625,0.203681,262160391.0,10.139900,722.0,0.001885,4.149480e-06,0.000003,0.000986,0.000905,1.875150e-04,16.4149,0.000597,4567628.0,0.002399,0.001737,0.997530,0.001177,19.938200,0.664856,0.001948,0.001616,60796.710596,NaN,NaN,NaN,NaN,NaN,59850.515694,59901.530729,51.015035,51.015035,3,True
1,60596.327662,16.803886,9.917465,8.474729,14.790803,16.114167,3.273268,0.270541,0.0,17.555490,34.969363,NaN,13.471450,2.982419,1.341433,-0.426584,0.000000,0.908953,-0.751604,-0.005580,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.056652,0.005948,0.000541,0.000441,0.022751,0.006562,NaN,NaN,False,0.0,0.037687,1.645437,1.707257,1.600286,3.683273,0.170410,0.046208,0.000000e+00,0.040870,0.000000,NaN,1.917810,0.000000,0.083318,0.056074,0.000000,0.121456,0.050861,0.007787,0.552506,6.309628,0.220410,0.117434,9.974748,0.223607,NaN,NaN,NaN,NaN,0.012854,0.001026,0.001621,0.000134,0.008264,0.008680,NaN,NaN,0.0,ZTF17aabvong,31.282032,11.248651,6.0,8996.0,panstarrs,dr2,6.524667,1.132243e-15,1.132243e-15,"{'iPSFFlux': 0.0002382450038567, 'projectionID...",1.214903e+17,NaN,1.000000,31.282127,11.248569,0.025181,0.007587,-20.618437,0.729355,r,0.454126,...,38.024601,0.216703,8.0,2.523095e+18,55943.572730,0.000237,5.0,14.587100,0.000000,262160391.0,0.000326,0.750460,0.002253,0.844023,17.735600,0.004179,0.000697,0.004494,6.202390e-07,262160391.0,0.983609,14.0,1.15710,0.360280,5.837870e-06,14.0,0.437406,31.282053,0.006039,3.673351e+15,NaN,17.957399,2.25000,0.001,6.43585,8.365690e-07,262160391.0,6.900980,24.995100,0.005311,0.046059,0.0,0.838204,1.092810,11.248618,0.007672,31.282053,17.252501,0.871072,0.864545,14.171600,3.501513e+15,-9.446360,0.000970,6290.0,1572992.0,2.523108e+18,3501513.0,0.000645,0.003231,56294.406587,0.006940,0.000000,0.000324,55941.203492,14.951000,0.001918,0.233626,262160391.0,169.826996,540.0,0.001870,5.242890e-06,0.000003,0.001872,0.000632,1.135010e-04,15.7191,0.001144,4030072.0,0.002548,0.002127,0.997932,0.000839,35.214901,0.595606,0.001940,0.001579,60796.710596,NaN,NaN,NaN,NaN,NaN,60596.327662,60663.246713,66.919051,66.919051,4,True
2,59861.468773,18.025000,0.000000,NaN,1.246246,5.971481,1.945101,0.815205,0.1,18.274099,0.021192,NaN,1.415106,9.945428,1.760750,0.595434,0.090909,-0.098382,-0.249100,0.013544,1,NaN,NaN,NaN,NaN,2,5.954756,0.602849,0.198726,31.826992,0.014541,0.004381,0.019289,0.004223,NaN,0.076705,NaN,0.087738,False,0.0,0.042273,0.000000,NaN,0.240076,1.968606,0.103605,0.153046,1.423831e-17,0.051127,1.643622,0.000000,1.198672,1.987739,0.178663,0.222787,0.020328,0.044112,0.063622,0.014004,0.489360,1.540522,0.171408,0.075891,7.011332,0.695852,1.965831,0.294856,0.083630,10.050958,0.005109,0.001060,0.010062,0.000792,NaN,0.070404,0.089636,0.111978,0.0,ZTF17aaaycpc,105.863596,32.068390,2.0,10296.0,panstarrs,dr2,8.549133,7.403929e-15,7.403929e-15,"{'raStackErr': 0.0010000000474974, 'cz': 0.530...",1.464811e+17,NaN,0.998975,105.864122,32.068686,0.516699,0.259615,-20.990470,1.067820,r,1.929947,...,0.691058,0.117420,0.0,2.523214e+18,56301.695611,0.000011,4.0,21.356400,0.489529,35651585.0,0.000019,0.726127,-0.014049,0.818664,20.723400,0.037106,0.000009,0.055614,7.877810e-07,35651585.0,1.039530,4.0,1.47531,NaN,9.757030e-07,0.0,0.229726,105.864119,0.000017,3.792412e+15,NaN,21.314301,2.50000,0.001,NaN,1.076550e-07,35651585.0,0.858702,24.983700,0.000006,0.006697,0.0,-0.231646,0.790146,32.068698,1.198120,105.864122,2.146750,0.993778,0.868475,20.723101,3.554956e+15,-62.186501,0.005556,6409.0,0.0,2.523191e+18,3554956.0,0.000002,-0.000017,56363.257702,0.095893,-0.552024,0.000019,56073.729985,22.842699,0.299529,0.167133,35651585.0,1.069600,660.0,0.083105,3.242540e-07,NaN,NaN,0.000002,7.793350e-07,NaN,0.032768,4341886.0,0.000043,0.325730,0.998050,0.000004,0.103803,0.943772,0.000014,-0.000006,60796.710596,NaN,NaN,NaN,NaN,NaN,59861.468773,59874.486111,13.017338,13.017338,2025,False
3,60168.430151,19.891600,16.017986,16.017986,NaN,16.017986,0.332001,0.738549,0.0,19.139200,14.040162,12.144228,13.450842,24.071412,1.046000,-0.510378,0.000000,0.557520,0.638637,0.037503,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.000232,0.000045,0.008214,0.001308,0.001968,NaN,0.008372,0.000673,False,0.0,0.133814,6.690610,3.329197,6.939874,0.983905,0.224879,0.564882,0.000000e+00,0.087849,1.218998,1.783097,5.738995,8.249798,0.146477,0.250046,0.037308,0.162770,0.517105,0.029405,0.444262,NaN,NaN,NaN,NaN,0.606977,2.711063,0.164649,0.095495,10.651462,0.001247,0.000232,0.015369,0.001136,0.008206,0.005486,0.027864,0.005755,0.0,ZTF17aaahhwn,69.419513,15.476838,1.0,4629.0,panstarrs,dr2,8.731575,5.265903e-15,5.265903e-15,"{'rpsfQfPerfect': 0.997987985610962, 'zinfoFla...",1.265707e+17,NaN,0.999887,69.419055,15.475506,0.061477,0.038571,-19.657119,0.877200,r,5.052795,...,32.283100,0.204750,8.0,2.523177e+18,56029.758091,0.000052,5.0,17.544001,0.000000,262160391.0,0.000046,0.536181,-0.002680,0.844265,19.620600,0.011020,0.000150,0.017615,4.890330e-07,262160391.0,1.064300,16.0,1.20624,0.358607,2.709190e-06,8.0,0.524166,69.419043,0.000424,3.737647e+15,NaN,19.704500,1.99999,0.001,2.63877,3.794600e-07,262160391.0,3.525280,25.000700,0.000349,0.327321,0.0,0.338785,1.176730,15.475460,0.051028,69.419023,8.813210,0.844592,0.845511,17.066799,3.527800e+15,-69.611900,0.002509,2966.0,1572992.0,2.523173e+18,3527800.0,0.000085,0.000419,56290.682505,0.026276,0.000000,0.000076,55907.662621,18.117399,0.012757,0.181665,262160391.0,6.803540,480.0,0.011566,2.178080e-06,0.000001,0.000082,0.000076,1.341610e-05,19.1180,0.004853,4334244.0,0.000394,0.013486,0.997816,0.000144,33.136902,0.652382,0.000310,0.000227,60796.710596,NaN,NaN,NaN,NaN,NaN,60168.430151,60208.496088,40.065937,40.065937,8502,False
4,59163.441424,NaN,NaN,NaN,NaN,NaN,0.089211,-0.370045,0.0,NaN,NaN,NaN,NaN,NaN,0.134977,-0.670378,0.000000,0.499700,0.374033,-0.013112,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.000021,0.000008,0.000038,0.000015,-0.004096,NaN,NaN,NaN,False,0.0,0.124332,2.966214,2.169821,2.061728,0.472477,0.145045,0.501863,0.000000e+00,0.108621,2.729212,2.572773,0.982429,0.000000,0.090754,0.475010,0.000000,0.133191,0.186942,0.043897,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000178,0.000078,0.000102,0.000032,0.038685,0.041126,0.025475,0.002856,0.0,ZTF17aaazjab,117.810147,34.412364,3.0,15712.0,panstarrs,dr2,6.325459,1.979225e-15,1.979225e-15,"{'rnFrames': 15.0, 'ypsfMajorFWHM': 0.91689997...",1.492912e+17,NaN,0.930639,117.810329,34.412576,0.076348,0.019087,-21.537358,0.807840,r,0.940699,...,15.869800,0.198206,14.0,2.523198e+18,56286.473447,0.000674,10.0,16.156799,0.000000,262160391.0,0.000632,0.289077,-0.013810,0.884926,17.052099,0.001629,0.001112,0.002535,6.645630e-07,262160391.0,1.090340,29.0,1.06956,0.278656,1.323810e-06,15.0,0.392236,117.810362,0.001259,3.633557e+15,NaN,16.871000,2.50001,0.001,1.89873,8.144340e-07,262160391.0,2.272060,25.008600,0.001348,0.401881,0.0,-0.384896,0.973595,34.412566,0.003250,117.810337,5.680150,1.042310,0.872169,15.933900,3.563442e+15,-86.350700,0.000795,2817.0,524416.0,2.523214e+18,3563442.0,0.000758,0.001335,56593.472794,0.004418,0.000000,0.000663,56032.055520,16.447500,0.000813,0.231648,262160391.0,43.972599,630.0,0.002720,1.450220e-06,0.000001,0.000783,0.000754,4.369490e-04,16.6660,0.000465,4395353.0,0.001485,0.000878,0.997580,0.001095,18.360800,1.024430,0.001202,0.001288,60796.710596,NaN,NaN,NaN,NaN,NaN,59163.441424,59170.444711,7.003287,7.003287,1846,False

In [23]:
df_matched = df_copycut.loc[mask_match].merge(
    zdf[["ra_deg","dec_deg","ZTFID","type","IAUID"]],
    left_on="alerce_idx",
    right_index=True,
    how="left"
)

df_unmatched = df_copycut.loc[~mask_match].copy()

df_matched.head()
df_unmatched.head()

,t0,g_peak_mag,g_peak_time,g_rise_time,g_decline_time,g_duration_above_half_flux,g_amplitude,g_skewness,g_beyond_2sigma,r_peak_mag,r_peak_time,r_rise_time,r_decline_time,r_duration_above_half_flux,r_amplitude,r_skewness,r_beyond_2sigma,mean_g-r,g-r_at_g_peak,mean_color_rate,g_n_peaks,g_dt_main_to_secondary_peak,g_dmag_secondary_peak,g_secondary_peak_prominence,g_secondary_peak_width,r_n_peaks,r_dt_main_to_secondary_peak,r_dmag_secondary_peak,r_secondary_peak_prominence,r_secondary_peak_width,g_max_rolling_variance,g_mean_rolling_variance,r_max_rolling_variance,r_mean_rolling_variance,g_rise_local_curvature,g_decline_local_curvature,r_rise_local_curvature,r_decline_local_curvature,features_valid,t0_err,g_peak_mag_err,g_peak_time_err,g_rise_time_err,g_decline_time_err,g_duration_above_half_flux_err,g_amplitude_err,g_skewness_err,g_beyond_2sigma_err,r_peak_mag_err,r_peak_time_err,r_rise_time_err,r_decline_time_err,r_duration_above_half_flux_err,r_amplitude_err,r_skewness_err,r_beyond_2sigma_err,mean_g-r_err,g-r_at_g_peak_err,mean_color_rate_err,g_n_peaks_err,g_dt_main_to_secondary_peak_err,g_dmag_secondary_peak_err,g_secondary_peak_prominence_err,g_secondary_peak_width_err,r_n_peaks_err,r_dt_main_to_secondary_peak_err,r_dmag_secondary_peak_err,r_secondary_peak_prominence_err,r_secondary_peak_width_err,g_max_rolling_variance_err,g_mean_rolling_variance_err,r_max_rolling_variance_err,r_mean_rolling_variance_err,g_rise_local_curvature_err,g_decline_local_curvature_err,r_rise_local_curvature_err,r_decline_local_curvature_err,features_valid_err,ZTFID,ra,dec,Unnamed: 0,idx,best_cat,best_cat_release,query_time,smallcone_posterior,missedcat_posterior,extra_cat_cols,host_objID,host_name,host_total_posterior,host_ra,host_dec,host_redshift_mean,host_redshift_std,host_absmag_mean,host_absmag_std,host_absmag_info,host_offset_mean,...,yExtNSigma,ymomentYY,ny,zstackDetectID,gEpoch,iFPSFFlux,nStackDetections,KronMag,ypsfLikelihood,iinfoFlag,zFPSFFlux,zpsfCore,momentXY,ypsfMinorFWHM,zPSFMag,yraErr,iFApFlux,zPSFMagErr,iPSFFluxErr,rinfoFlag,ipsfMinorFWHM,inFrames,gpsfMinorFWHM,gmomentXX,iKronFluxErr,ng,rpsfCore,raStack,zFKronFlux,uniquePspsSTid,objAltName1,iPSFMag,zApRadius,decStackErr,gmomentR1,yApFluxErr,zinfoFlag,rmomentR1,gzp,iKronFlux,randomID,surveyID,cx,imomentRH,ydec,gyPosErr,rra,rKronRad,zpsfMinorFWHM,yApFillFac,yKronMag,uniquePspsOBid,rpsfTheta,zApMagErr,iippDetectID,iinfoFlag2,ystackDetectID,batchID,rFmeanflxR5,zFmeanflxR7,iEpoch,zxPosErr,rpsfLikelihood,yPSFFlux,yEpoch,rKronMag,gdecErr,zmomentXX,yinfoFlag,zpsfChiSq,zexpTime,zKronMagErr,rKronFluxErr,gKronFluxErr,gKronFlux,rFApFlux,gPSFFlux,gKronMag,iraErr,gstackImageID,yFmeanflxR6,graErr,ipsfQf,iFmeanflxR5,zExtNSigma,ypsfCore,zFmeanflxR6,iFmeanflxR6,mjd_extracted,tns_redshift,latest_magnitude,oldest_alert,newest_alert,peak_phase,antares_oldest_alert,antares_newest_alert,antares_duration,duration_days,alerce_idx,matched
2,59861.468773,18.025000,0.000000,NaN,1.246246,5.971481,1.945101,0.815205,0.1,18.274099,0.021192,NaN,1.415106,9.945428,1.760750,0.595434,0.090909,-0.098382,-0.249100,0.013544,1,NaN,NaN,NaN,NaN,2,5.954756,0.602849,0.198726,31.826992,0.014541,0.004381,0.019289,0.004223,NaN,0.076705,NaN,0.087738,False,0.0,0.042273,0.000000,NaN,0.240076,1.968606,0.103605,0.153046,1.423831e-17,0.051127,1.643622,0.000000,1.198672,1.987739,0.178663,0.222787,0.020328,0.044112,0.063622,0.014004,0.489360,1.540522,0.171408,0.075891,7.011332,0.695852,1.965831,0.294856,0.083630,10.050958,0.005109,0.001060,0.010062,0.000792,NaN,0.070404,0.089636,0.111978,0.000000,ZTF17aaaycpc,105.863596,32.068390,2.0,10296.0,panstarrs,dr2,8.549133,7.403929e-15,7.403929e-15,"{'raStackErr': 0.0010000000474974, 'cz': 0.530...",1.464811e+17,NaN,0.998975,105.864122,32.068686,0.516699,0.259615,-20.990470,1.067820,r,1.929947,...,0.691058,0.117420,0.0,2.523214e+18,56301.695611,0.000011,4.0,21.356400,0.489529,35651585.0,0.000019,0.726127,-0.014049,0.818664,20.723400,0.037106,0.000009,0.055614,7.877810e-07,35651585.0,1.039530,4.0,1.47531,NaN,9.757030e-07,0.0,0.229726,105.864119,0.000017,3.792412e+15,NaN,21.314301,2.50000,0.001,NaN,1.076550e-07,35651585.0,0.858702,24.983700,0.000006,0.006697,0.0,-0.231646,0.790146,32.068698,1.198120,105.864122,2.14675,0.993778,0.868475,20.723101,3.554956e+15,-62.186501,0.005556,6409.0,0.0,2.523191e+18,3554956.0,0.000002,-0.000017,56363.257702,0.095893,-0.552024,0.000019,56073.729985,22.842699,0.299529,0.167133,35651585.0,1.069600,660.0,0.083105,3.242540e-07,NaN,NaN,0.000002,7.793350e-07,NaN,0.032768,4341886.0,0.000043,0.325730,0.998050,0.000004,0.103803,0.943772,0.000014,-0.000006,60796.710596,NaN,NaN,NaN,NaN,NaN,59861.468773,59874.486111,13.017338,13.017338,2025,False
3,60168.430151,19.891600,16.017986,16.017986,NaN,16.017986,0.332001,0.738549,0.0,19.139200,14.040162,12.144228,13.450842,24.071412,1.046000,-0.510378,0.000000,0.557520,0.638637,0.037503,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.000232,0.000045,0.008214,0.001308,0.001968,NaN,0.008372,0.000673,False,0.0,0.133814,6.690610,3.329197,6.939874,0.983905,0.224879,0.564882,0.000000e+00,0.087849,1.218998,1.783097,5.738995,8.249798,0.146477,0.250046,0.037308,0.162770,0.517105,0.029405,0.444262,NaN,NaN,NaN,NaN,0.606977,2.711063,0.164649,0.095495,10.651462,0.001247,0.000232,0.015369,0.001136,0.008206,0.005486,0.027864,0.005755,0.000000,ZTF17aaahhwn,69.419513,15.476838,1.0,4629.0,panstarrs,dr2,8.731575,5.265903e-15,5.265903e-15,"{'rpsfQfPerfect': 0.997987985610962, 'zinfoFla...",1.265707e+17,NaN,0.999887,69.419055,15.475506,0.061477,0.038571,-19.657119,0.877200,r,5.052795,...,32.283100,0.204750,8.0,2.523177e+18,56029.758091,0.000052,5.0,17.544001,0.000000,262160391.0,0.000046,0.536181,-0.002680,0.844265,19.620600,0.011020,0.000150,0.017615,4.890330e-07,262160391.0,1.064300,16.0,1.20624,0.358607,2.709190e-06,8.0,0.524166,69.419043,0.000424,3.737647e+15,NaN,19.704500,1.99999,0.001,2.63877,3.794600e-07,262160391.0,3.525280,25.000700,0.000349,0.327321,0.0,0.338785,1.176730,15.475460,0.051028,69.419023,8.81321,0.844592,0.845511,17.066799,3.527800e+15,-69.611900,0.002509,2966.0,1572992.0,2.523173e+18,3527800.0,0.000085,0.000419,56290.682505,0.026276,0.000000,0.000076,55907.662621,18.117399,0.012757,0.181665,262160391.0,6.803540,480.0,0.011566,2.178080e-06,0.000001,0.000082,0.000076,1.341610e-05,19.118000,0.004853,4334244.0,0.000394,0.013486,0.997816,0.000144,33.136902,0.652382,0.000310,0.000227,60796.710596,NaN,NaN,NaN,NaN,NaN,60168.430151,60208.496088,40.065937,40.065937,8502,False
4,59163.441424,NaN,NaN,NaN,NaN,NaN,0.089211,-0.370045,0.0,NaN,NaN,NaN,NaN,NaN,0.134977,-0.670378,0.000000,0.499700,0.374033,-0.013112,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.000021,0.000008,0.000038,0.000015,-0.004096,NaN,NaN,NaN,False,0.0,0.124332,2.966214,2.169821,2.061728,0.472477,0.145045,0.501863,0.000000e+00,0.108621,2.729212,2.572773,0.982429,0.000000,0.090754,0.475010,0.000000,0.133191,0.186942,0.043897,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000178,0.000078,0.000102,0.000032,0.038685,0.041126,0.025475,0.002856,0.000000,ZTF17aaazjab,117.810147,34.412364,3.0,15712.0,panstarrs,dr2,6.325459,1.979225e-15,1.979225e-15,"{'rnFrames': 15.0, 'ypsfMajorFWHM': 0.91689997...",1.492912e+17,NaN,0.930639,117.810329,34.412576,0.076348,0.019087,-21.537358,0.807840,r,0.940699,...,15.869800,0.198206,14.0,2.523198e+18,56286.473447,0.000674,10.0,16.156799,0.000000,262160391.0,0.000632,0.289077,-0.013810,0.884926,17.052099,0.001629,0.001112,0.002535,6.645630e-07,262160391.0,1.090340,29.0,1.06956,0.278656,1.323810e-06,15.0,0.392236,117.810362,0.001259,3.633557e+15,NaN,16.871000,2.50001,0.001,1.89873,8.144340e-07,262160391.0,2.272060,25.008600,0.001348,0.401881,0.0,-0.384896,0.973595,34.412566,0.003250,117.810337,5.68015,1.042310,0.872169,15.933900,3.563442e+15,-86.350700,0.000795,2817.0,524416.0,2.523214e+18,3563442.0,0.000758,0.001335,56593.472794,0.004418,0.000000,0.000663,56032.055520,16.447500,0.000813,0.231648,262160391.0,43.972599,630.0,0.002720,1.450220e-06,0.000001,0.000783,0.000754,4.369490e-04,16.666000,0.000465,4395353.0,0.001485,0.000878,0.997580,0.001095,18.360800,1.024430,0.001202,0.001288,60796.710596,NaN,NaN,NaN,NaN,NaN,59163.441424,59170.444711,7.003287,7.003287,1846,False
6,60635.340544,19.191984,1.946759,1.946759,11.899672,13.043426,0.919960,0.229242,0.0,19.248514,5.002998,4.932164,10.102558,15.034722,0.349546,0.528644,0.000000,0.206339,-0.125611,0.018020,2,7.046778,0.284679,0.148666,30.466405,0,NaN,NaN,NaN,NaN,0.003029,0.000562,0.000576,0.000123,-0.084371,0.023301,-0.007316,0.011983,True,0.0,0.131003,2.172262,2.023882,1.567870,2.242813,0.157982,0.250040,3.417397e-02,0.083200,3.952559,3.857736,3.939719,0.610632,0.151167,0.773426,0.063466,0.090530,0.244201,0.027715,0.812728,2.120356,0.140290,0.118371,23.388351,0.923381,1.550585,0.085013,0.112500,27.728795,0.013609,0.000765,0.009691,0.000423,0.324583,0.049230,0.028030,0.063916,0.510418,ZTF17aadcedu,104.070385,37.029006,15.0,16665.0,panstarrs,dr2,7.338146,2.247694e-15,2.247694e-15,"{'zApMag': 17.15019989013672, 'momentYY': 0.22...",1.524310e+17,NaN,0.982211,104.070475,37.029474,0.151999,0.038000,-22.723023,0.828720,r,1.704147,...,23.640900,0.184807,11.0,2.523211e+18,56370.449421,0.000178,5.0,16.574400,0.000000,102776839.0,0.000286,0.120457,-0.021807,0.832674,18.051800,0.003133,0.000410,0.004977,4.497080e-07,102776839.0,0.973961,24.0,1.36127,0.548462,2.052730e-06,13.0,0.367960,104.070468,0.001083,3.777059e+15,NaN,18.307800,2.00000,0.001,3.24535,7.294550e-07,102776839.0,3.463700,25.007299,0.000852,0.664673,0.0,-0.194085,1.070400,37.029517,0.021216,104.070489,8.65925,0.882796,0.872405,16.047501,3.560718e+15,13.907300,0.001126,11112.0,128.0,2.523193e+18,3560718.0,0.000264,0.001068,56683.936732,0.007860,0.000000,0.000320,56144.359124,17.126400,0.005304,0.178281,102776839.0,29.670000,630.0,0.004873,2.299640e-06,0.000002,0.000207,0.000335,5.118510e-05,18.109100,0.001187,4340103.0,0.001057,0.005484,0.996763,0.000473,40.511299,1.120380,0.000869,0.000648,60796.710596,NaN,NaN,NaN,NaN,NaN,60635.340544,60652.332373,16.991829,16.991829,7709,False
7,60253.313345,17.772699,8.019803,7.152844,23.900289,3.961007,1.924301,0.057989,0.0,17.778400,10.048935,8.855082,24.849410,6.086123,0.948299,0.222121,0.000000,0.386144,-0.101989,0.032312,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.008082,0.001833,0.007754,0.001019,0.039968,NaN,0.024831,NaN,False,0.0,0.042966,0.723765,0.934349,3.276472,1.486930,0.096331,0.084314,0.000000e+00,0.037942,0.976601,0.949144,1.587273,13.278388,0.080242,0.104527,0.000000,0.050053,0.067983,0.005198,0.307794,0.000000,0.027784,0.119625,2.822687,0.366348,0.071190,0.036253,0.017134,6.576485,0.003898,0.000295,0.002922,0.000227,0.014790,NaN,0.017540,NaN,0.000000,ZTF17aacpbmv,49.465938,-0.104966,12.0,9831.0,panstarrs,dr2,5.166699,1.515270e-15,1.515270e-15,"{'gxPos': 2156.4599609375, 'yPSFMag': 17.88459...",1.078705e+17,NaN,0.999649,49.465826,-0.104993,0.031643,0.013094,-18.818527,0.844675,r,0.424008,...,20.454100,0.142489,14.0,2.523133e+18,56080.738050,0.000265,5.0,16.893499,0.000000,262160391.0,0.000216,0.234125,0.007385,0.726455,18.125601,0.002523,0.000466,0.005446,5.415220e-07,262160391.0,0.933417,18.0,1.07518,0.302363,1.678240e-06,8.0,0.508974,49.465770,0.000700,3.700477e+15,NaN,18.044100,2.00000,0.001,2.26232,5.274740e-07,262160391.0,2.404890,25.009899,0.000635,0.160407,0.0,0.649900,1.026690,-0.104996,0.008682,49.465764,6.01222,0.867595,0.840537,16.641899,3.506425e+15,-77.396004,0.001432,2804.0,524416.0,2.523134e+18,3506425.0,0.000391,0.000686,56598.879284,0.008145,0.000000,0.000255,55914.690547,17.097099,0.002171,0.163975,262160391.0,14.377100,480.0,0.005883,1.418030e-06,0.000001,0.000332,0.000419,1.497300e-04,17.598801,0.001081,4165576.0,0.000752,0.002310,0.997638,0.000445,23.109600,1.202280,0.000605,0.000565,60796.710596,NaN,NaN,NaN,NaN,NaN,60253.313345,60314.131678,60.818333,60.818333,541,False

In [25]:
print(f"Matched: {len(df_matched):,}")
print(f"Unmatched: {len(df_unmatched):,}")

Matched: 3,835
Unmatched: 13,419

In [27]:
USE_HOST = False 

# Grab our RELAISS features
default_lc_features = constants.lc_features_const.copy()
default_host_features = constants.host_features_const.copy()

def overlap(cols, frame):
    # keep only columns present and drop *_err 
    return [c for c in cols if (c in frame.columns) and (not c.endswith("_err"))]

matchlc_cols   = overlap(default_lc_features, df_matched)
matchhost_cols = overlap(default_host_features, df_matched) if USE_HOST else []
matchfeature_cols = matchlc_cols + matchhost_cols

print(f"Found {len(matchlc_cols)} LC features in filtered data.")
if USE_HOST:
    print(f"Found {len(matchhost_cols)} host features in filtered data.")
print(f"Total candidate features: {len(matchfeature_cols)}")

Found 25 LC features in filtered data.
Total candidate features: 25

In [195]:
unmatchlc_cols   = overlap(default_lc_features, df_unmatched)
unmatchhost_cols = overlap(default_host_features, df_unmatched) if USE_HOST else []
unmatchfeature_cols = unmatchlc_cols + unmatchhost_cols

print(f"Found {len(unmatchlc_cols)} LC features in filtered data.")
if USE_HOST:
    print(f"Found {len(unmatchhost_cols)} host features in filtered data.")
print(f"Total candidate features: {len(unmatchfeature_cols)}")

Found 25 LC features in filtered data.
Total candidate features: 25

In [29]:
zdf = pd.read_csv(ALERCE_EXPLORER_CSV, low_memory=False)

df_cut["ZTFID"].describe()

df_copycut = df_cut.copy()

df_matched = df_copycut.merge(
    zdf,
    on="ZTFID",
    how="inner"   
)

len(set(df_copycut["ZTFID"]) & set(zdf["ZTFID"]))

#df_cut["ZTFID"].isna().sum()
#df_cut["ZTFID"].duplicated().sum()

tmp = df_copycut.merge(
    zdf,
    on="ZTFID",
    how="left",
    indicator=True
)

df_matched   = tmp[tmp["_merge"] == "both"].drop(columns=["_merge"])
df_unmatched = tmp[tmp["_merge"] == "left_only"].drop(columns=["_merge"])

In [31]:
zdf = pd.read_csv(ALERCE_EXPLORER_CSV, low_memory=False)

# ALeRCE explorer export often stores RA as hourangle string and Dec as deg string
alerce_coords = SkyCoord(
    ra=zdf["RA"].astype(str),
    dec=zdf["Dec"].astype(str),
    unit=(u.hourangle, u.deg)
)
zdf = zdf.copy()
zdf["ra_deg"] = alerce_coords.ra.deg
zdf["dec_deg"] = alerce_coords.dec.deg

ref_coords = SkyCoord(ra=df_cut["ra"].values * u.deg, dec=df_cut["dec"].values * u.deg)

idx, sep2d, _ = ref_coords.match_to_catalog_sky(alerce_coords)
mask_match = sep2d < (1.0 * u.arcsec)

df_cut = df_cut.copy()
df_cut["alerce_idx"] = idx
df_cut["matched"] = mask_match

df_matched = df_cut.loc[mask_match].merge(
    zdf[["ra_deg","dec_deg","ZTFID","type","IAUID"]],
    left_on="alerce_idx",
    right_index=True,
    how="left"
)

df_unmatched = df_cut.loc[~mask_match].copy()

print(f"Matched: {len(df_matched):,}")
print(f"Unmatched: {len(df_unmatched):,}")

# After df_matched is created:
print([c for c in df_matched.columns if "ZTF" in c.upper()])

# Common fix:
if "ZTFID_x" in df_matched.columns:
    df_matched = df_matched.rename(columns={"ZTFID_x": "ZTFID"})
elif "ZTFID_y" in df_matched.columns:
    df_matched = df_matched.rename(columns={"ZTFID_y": "ZTFID"})

df_matched[["ZTFID","type","IAUID","ra","dec"]].head()

Matched: 3,835
Unmatched: 13,419
['ZTFID_x', 'ZTFID_y']

           ZTFID   type       IAUID          ra        dec
0   ZTF17aabtvsy  SN Ia   SN2022yei  158.883762  37.649729
1   ZTF17aabvong  SN Ia   SN2024xxq   31.282032  11.248651
23  ZTF18aacnlxz  SN II  SN2020aavr  134.954664  38.109070
27  ZTF18aaczmob      -           -  105.519506  49.059275
28  ZTF18aadaexi      -   AT2021dpr  125.241560  36.312320

## Map labels to classifications
Training set of present classes and an 'unknown/unlabeled' set to score.

In [33]:
TYPE_MAP = {
    # Superluminous
    "SLSN-I": "SLSN",
    "SLSN-II": "SLSN",

    # Type II
    "SN II": "II",
    "SN IIP": "II",

    # Type IIb / IIn
    "SN IIb": "IIb",
    "SN IIn": "IIn",

    # Thermonuclear (Ia family)
    "SN Ia": "Ia",
    "SN Ia-91T": "Ia",
    "SN Ia-91bg": "Ia",
    "SN Ia-SC": "Ia",
    "SN Iax": "Ia",

    # Stripped-envelope
    "SN Ib": "Ibc",
    "SN Ib/c": "Ibc",
    "SN Ic": "Ibc",
    "SN Ic-BL": "Ibc",

    # TDE
    "TDE": "TDE",
    "TDE-He": "TDE",
}

def map_type(t):
    if pd.isna(t):
        return np.nan
    t = str(t).strip()
    return TYPE_MAP.get(t, "UNKNOWN")

In [35]:
df_matched["type_group"] = df_matched["type"].apply(map_type)
print(df_matched["type_group"].value_counts(dropna=False))

known_groups = ["SLSN", "II", "IIb", "IIn", "Ia", "Ibc", "TDE"]

df_train = df_matched[df_matched["type_group"].isin(known_groups)].copy()

df_anom = pd.concat(
    [df_unmatched, df_matched[df_matched["type_group"] == "UNKNOWN"]],
    ignore_index=True
)

print(f"Train rows: {len(df_train):,}")
print(f"To-score rows: {len(df_anom):,}")

type_group
Ia         2116
UNKNOWN    1143
II          320
Ibc         125
IIn          49
IIb          41
SLSN         24
TDE          17
Name: count, dtype: int64
Train rows: 2,692
To-score rows: 14,562

## Feature selection + preprocessing

- Numeric columns are used (avoid `ZTFID` strings)
- handle ±inf → NaN
- KNN impute, then standardise
- Use ReLaiss features

In [37]:
def preprocess(train_df: pd.DataFrame, score_df: pd.DataFrame, matchfeature_cols, n_neighbors=5):
    X_train_raw = train_df[matchfeature_cols].replace([np.inf, -np.inf], np.nan)
    X_score_raw = score_df[matchfeature_cols].replace([np.inf, -np.inf], np.nan)

    imputer = KNNImputer(n_neighbors=n_neighbors, weights="distance")
    X_train_imp = imputer.fit_transform(X_train_raw)
    X_score_imp = imputer.transform(X_score_raw)

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train_imp)
    X_score = scaler.transform(X_score_imp)

    return X_train, X_score, imputer, scaler

X_train, X_score, imputer, scaler = preprocess(df_train, df_anom, matchfeature_cols)
y_train = df_train["type_group"].values

X_train.shape, X_score.shape

((2692, 25), (14562, 25))

## DiMMAD scoring (median-median)
`cluster_agg` controls how each class cluster is aggregated; `metric_agg` controls aggregation across distance metrics.

In [39]:
dimmad_medmed = DistanceAnomaly(
    cluster_agg="median",
    metric_agg="median",
    normalize_scores=True
)

dimmad_medmed.fit(X_train, y_train)
scores_medmed = dimmad_medmed.score_samples(X_score)

df_anom = df_anom.copy()
df_anom["dimmad_medmed"] = scores_medmed

df_anom[["dimmad_medmed"]].describe()
df_anom.head()

,t0,g_peak_mag,g_peak_time,g_rise_time,g_decline_time,g_duration_above_half_flux,g_amplitude,g_skewness,g_beyond_2sigma,r_peak_mag,r_peak_time,r_rise_time,r_decline_time,r_duration_above_half_flux,r_amplitude,r_skewness,r_beyond_2sigma,mean_g-r,g-r_at_g_peak,mean_color_rate,g_n_peaks,g_dt_main_to_secondary_peak,g_dmag_secondary_peak,g_secondary_peak_prominence,g_secondary_peak_width,r_n_peaks,r_dt_main_to_secondary_peak,r_dmag_secondary_peak,r_secondary_peak_prominence,r_secondary_peak_width,g_max_rolling_variance,g_mean_rolling_variance,r_max_rolling_variance,r_mean_rolling_variance,g_rise_local_curvature,g_decline_local_curvature,r_rise_local_curvature,r_decline_local_curvature,features_valid,t0_err,g_peak_mag_err,g_peak_time_err,g_rise_time_err,g_decline_time_err,g_duration_above_half_flux_err,g_amplitude_err,g_skewness_err,g_beyond_2sigma_err,r_peak_mag_err,r_peak_time_err,r_rise_time_err,r_decline_time_err,r_duration_above_half_flux_err,r_amplitude_err,r_skewness_err,r_beyond_2sigma_err,mean_g-r_err,g-r_at_g_peak_err,mean_color_rate_err,g_n_peaks_err,g_dt_main_to_secondary_peak_err,g_dmag_secondary_peak_err,g_secondary_peak_prominence_err,g_secondary_peak_width_err,r_n_peaks_err,r_dt_main_to_secondary_peak_err,r_dmag_secondary_peak_err,r_secondary_peak_prominence_err,r_secondary_peak_width_err,g_max_rolling_variance_err,g_mean_rolling_variance_err,r_max_rolling_variance_err,r_mean_rolling_variance_err,g_rise_local_curvature_err,g_decline_local_curvature_err,r_rise_local_curvature_err,r_decline_local_curvature_err,features_valid_err,ZTFID,ra,dec,Unnamed: 0,idx,best_cat,best_cat_release,query_time,smallcone_posterior,missedcat_posterior,extra_cat_cols,host_objID,host_name,host_total_posterior,host_ra,host_dec,host_redshift_mean,host_redshift_std,host_absmag_mean,host_absmag_std,host_absmag_info,host_offset_mean,...,KronMag,ypsfLikelihood,iinfoFlag,zFPSFFlux,zpsfCore,momentXY,ypsfMinorFWHM,zPSFMag,yraErr,iFApFlux,zPSFMagErr,iPSFFluxErr,rinfoFlag,ipsfMinorFWHM,inFrames,gpsfMinorFWHM,gmomentXX,iKronFluxErr,ng,rpsfCore,raStack,zFKronFlux,uniquePspsSTid,objAltName1,iPSFMag,zApRadius,decStackErr,gmomentR1,yApFluxErr,zinfoFlag,rmomentR1,gzp,iKronFlux,randomID,surveyID,cx,imomentRH,ydec,gyPosErr,rra,rKronRad,zpsfMinorFWHM,yApFillFac,yKronMag,uniquePspsOBid,rpsfTheta,zApMagErr,iippDetectID,iinfoFlag2,ystackDetectID,batchID,rFmeanflxR5,zFmeanflxR7,iEpoch,zxPosErr,rpsfLikelihood,yPSFFlux,yEpoch,rKronMag,gdecErr,zmomentXX,yinfoFlag,zpsfChiSq,zexpTime,zKronMagErr,rKronFluxErr,gKronFluxErr,gKronFlux,rFApFlux,gPSFFlux,gKronMag,iraErr,gstackImageID,yFmeanflxR6,graErr,ipsfQf,iFmeanflxR5,zExtNSigma,ypsfCore,zFmeanflxR6,iFmeanflxR6,mjd_extracted,tns_redshift,latest_magnitude,oldest_alert,newest_alert,peak_phase,antares_oldest_alert,antares_newest_alert,antares_duration,duration_days,alerce_idx,matched,ra_deg,dec_deg,ZTFID_y,type,IAUID,type_group,dimmad_medmed
0,59861.468773,18.025000,0.000000,NaN,1.246246,5.971481,1.945101,0.815205,0.1,18.274099,0.021192,NaN,1.415106,9.945428,1.760750,0.595434,0.090909,-0.098382,-0.249100,0.013544,1,NaN,NaN,NaN,NaN,2,5.954756,0.602849,0.198726,31.826992,0.014541,0.004381,0.019289,0.004223,NaN,0.076705,NaN,0.087738,False,0.0,0.042273,0.000000,NaN,0.240076,1.968606,0.103605,0.153046,1.423831e-17,0.051127,1.643622,0.000000,1.198672,1.987739,0.178663,0.222787,0.020328,0.044112,0.063622,0.014004,0.489360,1.540522,0.171408,0.075891,7.011332,0.695852,1.965831,0.294856,0.083630,10.050958,0.005109,0.001060,0.010062,0.000792,NaN,0.070404,0.089636,0.111978,0.000000,ZTF17aaaycpc,105.863596,32.068390,2.0,10296.0,panstarrs,dr2,8.549133,7.403929e-15,7.403929e-15,"{'raStackErr': 0.0010000000474974, 'cz': 0.530...",1.464811e+17,NaN,0.998975,105.864122,32.068686,0.516699,0.259615,-20.990470,1.067820,r,1.929947,...,21.356400,0.489529,35651585.0,0.000019,0.726127,-0.014049,0.818664,20.723400,0.037106,0.000009,0.055614,7.877810e-07,35651585.0,1.039530,4.0,1.47531,NaN,9.757030e-07,0.0,0.229726,105.864119,0.000017,3.792412e+15,NaN,21.314301,2.50000,0.001,NaN,1.076550e-07,35651585.0,0.858702,24.983700,0.000006,0.006697,0.0,-0.231646,0.790146,32.068698,1.198120,105.864122,2.14675,0.993778,0.868475,20.723101,3.554956e+15,-62.186501,0.005556,6409.0,0.0,2.523191e+18,3554956.0,0.000002,-0.000017,56363.257702,0.095893,-0.552024,0.000019,56073.729985,22.842699,0.299529,0.167133,35651585.0,1.069600,660.0,0.083105,3.242540e-07,NaN,NaN,0.000002,7.793350e-07,NaN,0.032768,4341886.0,0.000043,0.325730,0.998050,0.000004,0.103803,0.943772,0.000014,-0.000006,60796.710596,NaN,NaN,NaN,NaN,NaN,59861.468773,59874.486111,13.017338,13.017338,2025,False,NaN,NaN,NaN,NaN,NaN,NaN,-0.004883
1,60168.430151,19.891600,16.017986,16.017986,NaN,16.017986,0.332001,0.738549,0.0,19.139200,14.040162,12.144228,13.450842,24.071412,1.046000,-0.510378,0.000000,0.557520,0.638637,0.037503,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.000232,0.000045,0.008214,0.001308,0.001968,NaN,0.008372,0.000673,False,0.0,0.133814,6.690610,3.329197,6.939874,0.983905,0.224879,0.564882,0.000000e+00,0.087849,1.218998,1.783097,5.738995,8.249798,0.146477,0.250046,0.037308,0.162770,0.517105,0.029405,0.444262,NaN,NaN,NaN,NaN,0.606977,2.711063,0.164649,0.095495,10.651462,0.001247,0.000232,0.015369,0.001136,0.008206,0.005486,0.027864,0.005755,0.000000,ZTF17aaahhwn,69.419513,15.476838,1.0,4629.0,panstarrs,dr2,8.731575,5.265903e-15,5.265903e-15,"{'rpsfQfPerfect': 0.997987985610962, 'zinfoFla...",1.265707e+17,NaN,0.999887,69.419055,15.475506,0.061477,0.038571,-19.657119,0.877200,r,5.052795,...,17.544001,0.000000,262160391.0,0.000046,0.536181,-0.002680,0.844265,19.620600,0.011020,0.000150,0.017615,4.890330e-07,262160391.0,1.064300,16.0,1.20624,0.358607,2.709190e-06,8.0,0.524166,69.419043,0.000424,3.737647e+15,NaN,19.704500,1.99999,0.001,2.63877,3.794600e-07,262160391.0,3.525280,25.000700,0.000349,0.327321,0.0,0.338785,1.176730,15.475460,0.051028,69.419023,8.81321,0.844592,0.845511,17.066799,3.527800e+15,-69.611900,0.002509,2966.0,1572992.0,2.523173e+18,3527800.0,0.000085,0.000419,56290.682505,0.026276,0.000000,0.000076,55907.662621,18.117399,0.012757,0.181665,262160391.0,6.803540,480.0,0.011566,2.178080e-06,0.000001,0.000082,0.000076,1.341610e-05,19.118000,0.004853,4334244.0,0.000394,0.013486,0.997816,0.000144,33.136902,0.652382,0.000310,0.000227,60796.710596,NaN,NaN,NaN,NaN,NaN,60168.430151,60208.496088,40.065937,40.065937,8502,False,NaN,NaN,NaN,NaN,NaN,NaN,-0.001495
2,59163.441424,NaN,NaN,NaN,NaN,NaN,0.089211,-0.370045,0.0,NaN,NaN,NaN,NaN,NaN,0.134977,-0.670378,0.000000,0.499700,0.374033,-0.013112,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0.000021,0.000008,0.000038,0.000015,-0.004096,NaN,NaN,NaN,False,0.0,0.124332,2.966214,2.169821,2.061728,0.472477,0.145045,0.501863,0.000000e+00,0.108621,2.729212,2.572773,0.982429,0.000000,0.090754,0.475010,0.000000,0.133191,0.186942,0.043897,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000178,0.000078,0.000102,0.000032,0.038685,0.041126,0.025475,0.002856,0.000000,ZTF17aaazjab,117.810147,34.412364,3.0,15712.0,panstarrs,dr2,6.325459,1.979225e-15,1.979225e-15,"{'rnFrames': 15.0, 'ypsfMajorFWHM': 0.91689997...",1.492912e+17,NaN,0.930639,117.810329,34.412576,0.076348,0.019087,-21.537358,0.807840,r,0.940699,...,16.156799,0.000000,262160391.0,0.000632,0.289077,-0.013810,0.884926,17.052099,0.001629,0.001112,0.002535,6.645630e-07,262160391.0,1.090340,29.0,1.06956,0.278656,1.323810e-06,15.0,0.392236,117.810362,0.001259,3.633557e+15,NaN,16.871000,2.50001,0.001,1.89873,8.144340e-07,262160391.0,2.272060,25.008600,0.001348,0.401881,0.0,-0.384896,0.973595,34.412566,0.003250,117.810337,5.68015,1.042310,0.872169,15.933900,3.563442e+15,-86.350700,0.000795,2817.0,524416.0,2.523214e+18,3563442.0,0.000758,0.001335,56593.472794,0.004418,0.000000,0.000663,56032.055520,16.447500,0.000813,0.231648,262160391.0,43.972599,630.0,0.002720,1.450220e-06,0.000001,0.000783,0.000754,4.369490e-04,16.666000,0.000465,4395353.0,0.001485,0.000878,0.997580,0.001095,18.360800,1.024430,0.001202,0.001288,60796.710596,NaN,NaN,NaN,NaN,NaN,59163.441424,59170.444711,7.003287,7.003287,1846,False,NaN,NaN,NaN,NaN,NaN,NaN,-0.005350
3,60635.340544,19.191984,1.946759,1.946759,11.899672,13.043426,0.919960,0.229242,0.0,19.248514,5.002998,4.932164,10.102558,15.034722,0.349546,0.528644,0.000000,0.206339,-0.125611,0.018020,2,7.046778,0.284679,0.148666,30.466405,0,NaN,NaN,NaN,NaN,0.003029,0.000562,0.000576,0.000123,-0.084371,0.023301,-0.007316,0.011983,True,0.0,0.131003,2.172262,2.023882,1.567870,2.242813,0.157982,0.250040,3.417397e-02,0.083200,3.952559,3.857736,3.939719,0.610632,0.151167,0.773426,0.063466,0.090530,0.244201,0.027715,0.812728,2.120356,0.140290,0.118371,23.388351,0.923381,1.550585,0.085013,0.112500,27.728795,0.013609,0.000765,0.009691,0.000423,0.324583,0.049230,0.028030,0.063916,0.510418,ZTF17aadcedu,104.070385,37.029006,15.0,16665.0,panstarrs,dr2,7.338146,2.247694e-15,2.247694e-15,"{'zApMag': 17.15019989013672, 'momentYY': 0.22...",1.524310e+17,NaN,0.982211,104.070475,37.029474,0.151999,0.038000,-22.723023,0.828720,r,1.704147,...,16.574400,0.000000,102776839.0,0.000286,0.120457,-0.021807,0.832674,18.051800,0.003133,0.000410,0.004977,4.497080e-07,102776839.0,0.973961,24.0,1.36127,0.548462,2.052730e-06,13.0,0.367960,104.070468,0.001083,3.777059e+15,NaN,18.307800,2.00000,0.001,3.24535,7.294550e-07,102776839.0,3.463700,25.007299,0.000852,0.664673,0.0,-0.194085,1.070400,37.029517,0.021216,104.070489,8.65925,0.882796,0.872405,16.047501,3.560718e+15,13.907300,0.001126,11112.0,128.0,2.523193e+18,3560718.0,0.000264,0.001068,56683.936732,0.007860,0.000000,0.000320,56144.359124,17.126400,0.005304,0.178281,102776839.0,29.670000,630.0,0.004873,2.299640e-06,0.000002,0.000207,0.000335,5.118510e-05,18.109100,0.001187,4340103.0,0.001057,0.005484,0.996763,0.000473,40.511299,1.120380,0.000869,0.000648,60796.710596,NaN,NaN,NaN,NaN,NaN,60635.340544,60652.332373,16.991829,16.991829,7709,False,NaN,NaN,NaN,NaN,NaN,NaN,-0.002648
4,60253.313345,17.772699,8.019803,7.152844,23.900289,3.961007,1.924301,0.057989,0.0,17.778400,10.048935,8.855082,24.849410,6.086123,0.948299,0.222121,0.000000,0.386144,-0.101989,0.032312,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.008082,0.001833,0.007754,0.001019,0.039968,NaN,0.024831,NaN,False,0.0,0.042966,0.723765,0.934349,3.276472,1.486930,0.096331,0.084314,0.000000e+00,0.037942,0.976601,0.949144,1.587273,13.278388,0.080242,0.104527,0.000000,0.050053,0.067983,0.005198,0.307794,0.000000,0.027784,0.119625,2.822687,0.366348,0.071190,0.036253,0.017134,6.576485,0.003898,0.000295,0.002922,0.000227,0.014790,NaN,0.017540,NaN,0.000000,ZTF17aacpbmv,49.465938,-0.104966,12.0,9831.0,panstarrs,dr2,5.166699,1.515270e-15,1.515270e-15,"{'gxPos': 2156.4599609375, 'yPSFMag': 17.88459...",1.078705e+17,NaN,0.999649,49.465826,-0.104993,0.031643,0.013094,-18.818527,0.844675,r,0.424008,...,16.893499,0.000000,262160391.0,0.000216,0.234125,0.007385,0.726455,18.125601,0.002523,0.000466,0.005446,5.415220e-07,262160391.0,0.933417,18.0,1.07518,0.302363,1.678240e-06,8.0,0.508974,49.465770,0.000700,3.700477e+15,NaN,18.044100,2.00000,0.001,2.26232,5.274740e-07,262160391.0,2.404890,25.009899,0.000635,0.160407,0.0,0.649900,1.026690,-0.104996,0.008682,49.465764,6.01222,0.867595,0.840537,16.641899,3.506425e+15,-77.396004,0.001432,2804.0,524416.0,2.523134e+18,3506425.0,0.000391,0.000686,56598.879284,0.008145,0.000000,0.000255,55914.690547,17.097099,0.002171,0.163975,262160391.0,14.377100,480.0,0.005883,1.418030e-06,0.000001,0.000332,0.000419,1.497300e-04,17.598801,0.001081,4165576.0,0.000752,0.002310,0.997638,0.000445,23.109600,1.202280,0.000605,0.000565,60796.710596,NaN,NaN,NaN,NaN,NaN,60253.313345,60314.131678,60.818333,60.818333,541,False,NaN,NaN,NaN,NaN,NaN,NaN,-0.001224

In [41]:
# Rank top anomalies
df_ranked_med = df_anom.sort_values("dimmad_medmed", ascending=True).copy()
df_ranked_med[["ZTFID","dimmad_medmed"]].head(20)

              ZTFID  dimmad_medmed
460    ZTF20abyrxie      -0.756196
12601  ZTF24abrirtr      -0.574733
5660   ZTF22aahfzfd      -0.506736
5826   ZTF22aajbpuo      -0.489937
13088  ZTF25aadnvfe      -0.481751
5616   ZTF22aagwane      -0.443242
4340   ZTF21abwntdi      -0.431223
9296   ZTF23aaqrlwy      -0.427159
5835   ZTF22aajfxrx      -0.424419
12153  ZTF24abgoksi      -0.422766
12320  ZTF24abkmlip      -0.410375
5889   ZTF22aajujbt      -0.410182
13090  ZTF25aadnxtg      -0.405394
7287   ZTF22abhjmfy      -0.402515
9135   ZTF23aaomzth      -0.396778
5883   ZTF22aajssgv      -0.391993
5828   ZTF22aajbqel      -0.391733
5982   ZTF22aakmpud      -0.391489
7061   ZTF22abfbqae      -0.388128
7000   ZTF22abdvslh      -0.385596

In [210]:
df_out = (
    df_anom[["ZTFID", "dimmad_medmed"]]
    .sort_values("dimmad_medmed", ascending=True)
    .reset_index(drop=True)
)

df_out["rank"] = df_out.index + 1

rank_path = OUT_DIR / "relaissranked_medmed_.csv"
df_out[["ZTFID", "rank"]].to_csv(rank_path, index=False)

rank_path

PosixPath('outputs/relaissranked_medmed_.csv')

In [211]:
from pathlib import Path
from joblib import dump

MODEL_DIR = Path("models")
MODEL_DIR.mkdir(exist_ok=True)

bundle_path = MODEL_DIR / "dimmad_medmed_relaiss_bundle.joblib"

dump(
    {
        "feature_cols": matchfeature_cols,   # the RELAISS-only feature list
        "imputer": imputer,                  # fitted
        "scaler": scaler,                    # fitted
        "model": dimmad_medmed,              # trained DiMMAD (medmed)
    },
    bundle_path,
)

bundle_path

PosixPath('models/dimmad_medmed_relaiss_bundle.joblib')

## Compare aggregation choices (min-median)

In [59]:
dimmad_minmed = DistanceAnomaly(
    cluster_agg="min",
    metric_agg="median",
    normalize_scores=True
)

dimmad_minmed.fit(X_train, y_train)
scores_minmed = dimmad_minmed.score_samples(X_score)

df_anom["dimmad_minmed"] = scores_minmed
df_anom[["dimmad_medmed","dimmad_minmed"]].head()

   dimmad_medmed  dimmad_minmed
0  -4.187967e-12      -0.001503
1  -2.158663e-14      -0.001324
2  -1.202602e-13      -0.001224
3  -6.721686e-14      -0.001417
4  -5.004757e-14      -0.000662

In [60]:
df_ranked_min = df_anom.sort_values("dimmad_minmed", ascending=True).copy()
df_ranked_min[["ZTFID","dimmad_minmed"]].head(20)

              ZTFID  dimmad_minmed
11570  ZTF24aaemydm      -0.975135
6342   ZTF22aakdbia      -0.935496
9370   ZTF23aaixyan      -0.692445
6263   ZTF22aajfxrx      -0.272871
9139   ZTF23aaflnxp      -0.263776
6760   ZTF22aaoonxc      -0.230819
6256   ZTF22aajbqel      -0.210001
6293   ZTF22aajkifc      -0.203057
6255   ZTF22aajbpzc      -0.194996
6426   ZTF22aakmpud      -0.148340
7918   ZTF22abkblgi      -0.122062
6068   ZTF22aahfzfd      -0.109725
6852   ZTF22aapkjio      -0.104258
6826   ZTF22aapfhmh      -0.091278
7697   ZTF22abgbhji      -0.090345
6254   ZTF22aajbpuo      -0.086808
6423   ZTF22aakmpmf      -0.085838
6662   ZTF22aanmbrl      -0.079756
6724   ZTF22aaokitb      -0.076257
6663   ZTF22aanmbsd      -0.073282

## Fetch lightcurves / cutouts from ALeRCE

In [43]:
from joblib import load

# Load DiMMAD bundle
DIMMAD_BUNDLE_PATH = "models/dimmad_medmed_relaiss_bundle.joblib"
art_dm = load(DIMMAD_BUNDLE_PATH)

dimmad_val       = art_dm["model"]
knn_imp_dm       = art_dm["imputer"]
scaler_dm        = art_dm["scaler"]
dm_feature_cols  = art_dm["feature_cols"]

In [91]:
from alerce.core import Alerce
from tqdm import tqdm
alerce = Alerce()

oids = objs_top["oid"].tolist()
print(f"Fetched {len(oids)} transient candidates from ALeRCE")

DIMMAD_BUNDLE_PATH = "models/dimmad_medmed_relaiss_bundle.joblib"
art_dm = load(DIMMAD_BUNDLE_PATH)

dimmad_val       = art_dm["model"]
knn_imp_dm       = art_dm["imputer"]
scaler_dm        = art_dm["scaler"]
dm_feature_cols  = art_dm["feature_cols"]

# Fetch up to 1000 recent objects classified as Transient by ALeRCE lc_classifier
objs_top = alerce.query_objects(
    classifier="lc_classifier_top",
    class_name="Transient",
    probability=0.7,
    page_size=1000,
    order_by="lastmjd",
    order_mode="DESC",
    format="pandas"
).drop_duplicates("oid")

oids = objs_top["oid"].tolist()
print(f"Fetched {len(oids)} transient candidates from ALeRCE")

Fetched 1000 transient candidates from ALeRCE
Fetched 1000 transient candidates from ALeRCE

In [93]:
# Cross-check with stamp classifier to keep high-confidence SNe
probs_list = []
for oid in tqdm(oids, desc="Fetching probabilities"):
    try:
        p = alerce.query_probabilities(oid, format="pandas", survey="ztf")
        if p is not None and not p.empty:
            p["oid"] = oid
            probs_list.append(p)
    except Exception as e:
        print(f"Failed for {oid}: {e}")

probs_stamp = pd.concat(probs_list, ignore_index=True) if probs_list else pd.DataFrame()

wide = probs_stamp.pivot_table(
    index="oid", columns="class_name", values="probability", aggfunc="max"
).fillna(0.0)

if "SN" not in wide.columns:
    wide["SN"] = 0.0

cand    = wide[wide["SN"] >= 0.7].index
sn_objs = objs_top[objs_top["oid"].isin(cand)].copy()
oids    = sn_objs["oid"].tolist()

print(f"Total Transients: {len(objs_top)}  |  Likely SNe (stamp P ≥ 0.7): {len(sn_objs)}")
sn_objs.head()

Fetching probabilities: 100%|███████████████| 1000/1000 [14:44<00:00,  1.13it/s]

Total Transients: 1000  |  Likely SNe (stamp P ≥ 0.7): 185

,oid,ndethist,ncovhist,mjdstarthist,mjdendhist,corrected,stellar,ndet,g_r_max,g_r_max_corr,g_r_mean,g_r_mean_corr,firstmjd,lastmjd,deltajd,meanra,meandec,sigmara,sigmadec,class,classifier,probability,step_id_corr
7,ZTF18admikzo,1032,2385,58261.482188,61125.518704,True,False,263,None,None,None,None,59733.354375,61125.518704,1392.164329,287.130284,-0.415086,0.004706,0.004706,Transient,lc_classifier_top,0.824,27.5.7a32.dev1
10,ZTF19addazgo,114,1906,58642.274525,61125.501586,False,False,36,None,None,None,None,59806.174028,61125.501586,1319.327558,265.153586,-4.061844,0.012201,0.012170,Transient,lc_classifier_top,0.994,27.5.7a32.dev1
12,ZTF18aaxxfah,110,1450,58258.251586,61125.486250,False,False,31,None,None,None,None,58273.315718,61125.486250,2852.170532,223.701664,5.507450,0.012603,0.012545,Transient,lc_classifier_top,0.904,27.5.7a32.dev1
14,ZTF18abltdkd,203,4041,58249.330359,61125.468218,True,False,26,None,None,None,None,58337.183438,61125.468218,2788.284780,243.586172,3.231931,0.002751,0.002746,Transient,lc_classifier_top,0.910,27.5.7a32.dev1
15,ZTF19aavhxby,305,3045,58243.335359,61125.464919,False,False,81,None,None,None,None,58628.313229,61125.464919,2497.151690,224.137059,-2.106456,0.002174,0.002173,Transient,lc_classifier_top,1.000,27.5.7a32.dev1

In [63]:
probs_list = []
for oid in tqdm(oids, desc="Fetching probabilities"):
    try:
        p = alerce.query_probabilities(oid, format="pandas", survey="ztf")
        if p is not None and not p.empty:
            p["oid"] = oid
            probs_list.append(p)
    except Exception as e:
        print(f"Failed for {oid}: {e}")

Fetching probabilities: 100%|███████████████| 1000/1000 [14:18<00:00,  1.16it/s]

In [69]:
probs_stamp = pd.concat(probs_list, ignore_index=True) if probs_list else pd.DataFrame()
wide = probs_stamp.pivot_table(
    index="oid", columns="class_name", values="probability", aggfunc="max"
).fillna(0.0)
if "SN" not in wide.columns:
    wide["SN"] = 0.0

cand    = wide[wide["SN"] >= 0.7].index
sn_objs = objs_top[objs_top["oid"].isin(cand)].copy()
oids    = sn_objs["oid"].tolist()
print(f"Likely SNe (stamp P >= 0.7): {len(sn_objs)}")

Likely SNe (stamp P >= 0.7): 185

In [75]:
# Features
rows = []
for oid in tqdm(oids, desc="Fetching features"):
    try:
        f = alerce.query_features(oid, format="pandas")
        if f is not None and not f.empty:
            fw = f.pivot_table(
                index="oid", columns="name", values="value", aggfunc="first"
            )
            rows.append(fw)
        else:
            rows.append(pd.DataFrame(index=pd.Index([oid], name="oid")))
    except:
        rows.append(pd.DataFrame(index=pd.Index([oid], name="oid")))

df_new = pd.concat(rows, axis=0) if rows else pd.DataFrame()
print(f"Features fetched for {len(df_new)} objects")

Fetching features: 100%|██████████████████████| 185/185 [03:01<00:00,  1.02it/s]

Features fetched for 185 objects

In [77]:
#  Load DiMMAD bundle and score
art_dm          = load("models/dimmad_medmed_relaiss_bundle.joblib")
dimmad_val      = art_dm["model"]
knn_imp_dm      = art_dm["imputer"]
scaler_dm       = art_dm["scaler"]
dm_feature_cols = art_dm["feature_cols"]

# Align columns
for c in dm_feature_cols:
    if c not in df_new.columns:
        df_new[c] = np.nan

X_dm_new    = df_new[dm_feature_cols].replace([np.inf, -np.inf], np.nan)
X_dm_imp    = knn_imp_dm.transform(X_dm_new)
X_dm_scaled = scaler_dm.transform(X_dm_imp)
scores_dm   = dimmad_val.score_samples(X_dm_scaled)

In [79]:
# Step 4: Rank and display results
res_dm = pd.DataFrame({
    "oid":          df_new.index,
    "dimmad_score": scores_dm,
}).reset_index(drop=True)

res_dm["dimmad_rank"] = res_dm["dimmad_score"].rank(
    method="first", ascending=False
).astype(int)

keep_cols = [c for c in ["oid", "meanra", "meandec", "ndet", "firstmjd", "lastmjd"]
             if c in sn_objs.columns]
res_dm = res_dm.merge(sn_objs[keep_cols], on="oid", how="left")

print(f"\nDiMMAD ALeRCE validation — {len(res_dm)} objects scored")
print(f"Score range: {scores_dm.min():.4f} to {scores_dm.max():.4f}")
print(f"Top 10 anomaly candidates:")
print(res_dm.sort_values("dimmad_rank").head(10))

DiMMAD ALeRCE validation — 185 objects scored
Score range: -0.0000 to -0.0000
Top 10 anomaly candidates:
            oid  dimmad_score  dimmad_rank      meanra    meandec  ndet  \
0  ZTF18admikzo          -0.0            1  287.130284  -0.415086   263
1  ZTF19addazgo          -0.0            2  265.153586  -4.061844    36
2  ZTF18aaxxfah          -0.0            3  223.701664   5.507450    31
3  ZTF18abltdkd          -0.0            4  243.586172   3.231931    26
4  ZTF19aavhxby          -0.0            5  224.137059  -2.106456    81
5  ZTF19aawkakl          -0.0            6  272.318841   8.220046    38
6  ZTF20actnzzk          -0.0            7  186.415800  -2.949805    68
7  ZTF20actnzxm          -0.0            8  184.467619  -0.908026    81
8  ZTF20acuosvy          -0.0            9  187.209440  -1.944074    57
9  ZTF20aaawwkl          -0.0           10  152.560818  23.108912   612

       firstmjd       lastmjd
0  59733.354375  61125.518704
1  59806.174028  61125.501586
2  58273.315718  61125.486250
3  58337.183438  61125.468218
4  58628.313229  61125.464919
5  58635.361377  61125.455764
6  59177.526354  61125.344560
7  59177.526354  61125.344560
8  59177.526354  61125.344560
9  58849.454028  61125.325069

In [81]:
# Check feature matrix before and after preprocessing
print("=== Raw features ===")
print(f"All NaN: {X_dm_new.isna().all(axis=1).sum()} rows")
print(f"Any values: {X_dm_new.notna().any(axis=1).sum()} rows")
print(X_dm_new.iloc[0])

print("\n=== After imputation ===")
print(f"Any non-zero: {(X_dm_imp != 0).any()}")
print(f"Unique values sample: {np.unique(X_dm_imp.flatten())[:10]}")

print("\n=== After scaling ===")
print(f"Any non-zero: {(X_dm_scaled != 0).any()}")
print(f"Unique values sample: {np.unique(X_dm_scaled.flatten())[:10]}")

print("\n=== Raw scores ===")
print(f"Unique scores: {np.unique(scores_dm)}")
print(f"Score dtype: {scores_dm.dtype}")

print("\n=== Feature column match ===")
alerce_cols = set(df_new.columns)
dm_cols = set(dm_feature_cols)
print(f"DiMMAD expects {len(dm_feature_cols)} features")
print(f"Found in ALeRCE data: {len(alerce_cols & dm_cols)}")
print(f"Missing from ALeRCE: {dm_cols - alerce_cols}")

=== Raw features ===
All NaN: 185 rows
Any values: 0 rows
g_peak_time                  NaN
r_peak_time                  NaN
g_rise_time                  NaN
g_decline_time               NaN
r_rise_time                  NaN
r_decline_time               NaN
g_duration_above_half_flux   NaN
r_duration_above_half_flux   NaN
g_amplitude                  NaN
r_amplitude                  NaN
g_skewness                   NaN
r_skewness                   NaN
g_beyond_2sigma              NaN
r_beyond_2sigma              NaN
mean_g-r                     NaN
g-r_at_g_peak                NaN
mean_color_rate              NaN
g_max_rolling_variance       NaN
r_max_rolling_variance       NaN
g_mean_rolling_variance      NaN
r_mean_rolling_variance      NaN
g_rise_local_curvature       NaN
g_decline_local_curvature    NaN
r_rise_local_curvature       NaN
r_decline_local_curvature    NaN
Name: ZTF18admikzo, dtype: float64

=== After imputation ===
Any non-zero: True
Unique values sample: [-1.59157981e+00 -1.99703256e-02 -6.98210713e-04  2.70840303e-03
  3.28091938e-03  1.22503315e-02  2.14997855e-02  2.35391757e-02
  2.36659573e-02  3.85167109e-02]

=== After scaling ===
Any non-zero: True
Unique values sample: [-0.00442855 -0.00211835  0.          0.00012576  0.00029906  0.00056934
  0.00066983  0.00106632  0.00433723  0.0052928 ]

=== Raw scores ===
Unique scores: [-0.]
Score dtype: float64

=== Feature column match ===
DiMMAD expects 25 features
Found in ALeRCE data: 25
Missing from ALeRCE: set()

In [83]:
print(dm_feature_cols[:10])

['g_peak_time', 'r_peak_time', 'g_rise_time', 'g_decline_time', 'r_rise_time', 'r_decline_time', 'g_duration_above_half_flux', 'r_duration_above_half_flux', 'g_amplitude', 'r_amplitude']

In [89]:
# Make sure you're using the filtered oids
print(f"sn_objs count: {len(sn_objs)}")
print(f"oids count: {len(oids)}")

# Re-fetch using only the filtered SN oids
oids_sn = sn_objs["oid"].tolist()
df_new, bad = fetch_features(oids_sn, keep_placeholders=True)
print(f"Non-empty rows: {df_new.notna().any(axis=1).sum()}")
print(df_new.iloc[0])

sn_objs count: 185
oids count: 185

NameError: name 'fetch_features' is not defined